import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "minecraft-hunger-calculator",
  matrixSlug: "minecraft-hunger",
  icon: "Beef",
  name: "Minecraft Hunger and Saturation Calculator",
  description:
    "Simulate hunger, saturation, exhaustion, and natural regeneration tick by tick, verified against decompiled game code.",
  category: "Minecraft",
  keywords: [
    "minecraft hunger calculator",
    "minecraft saturation chart",
    "minecraft best food",
    "minecraft food saturation list",
    "minecraft exhaustion",
    "minecraft natural regeneration",
    "minecraft starvation damage",
  ],
  searchTerms: [
    "what is the best food in minecraft",
    "golden carrot vs steak",
    "how long does the hunger bar last",
    "why is my hunger draining so fast",
    "minecraft sprinting hunger",
    "saturation hidden stat",
    "how fast do you heal in minecraft",
    "starving to death minecraft",
    "food for a long trip",
    "minecraft hunger points",
    "minecraft food chart",
    "hunger bar calculator",
    "steak vs golden carrot",
    "hunger shank calculator",
    "rabbit stew best food",
    "does sprinting drain hunger",
    "how much food for a mining trip",
    "exhaustion calculator minecraft",
    "food comparison chart minecraft",
    "hunger drain simulator",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "drain",
      options: [
        {
          value: "drain",
          label: "Hunger drain",
          synonyms: ["how long", "bar empties", "exhaustion", "sprint drain", "starve timer"],
        },
        {
          value: "sustain",
          label: "Food needed",
          synonyms: ["how much food", "per hour", "stock up", "trip planning"],
        },
        {
          value: "regen",
          label: "Regeneration",
          synonyms: ["healing", "hearts", "natural regeneration", "heal time"],
        },
        {
          value: "compare",
          label: "Compare foods",
          synonyms: ["best food", "ranking", "saturation table", "tier list"],
        },
      ],
    },
    {
      kind: "select",
      id: "version",
      label: "Minecraft version",
      default: "1.21.11",
      options: [
        { value: "1.16.5", label: "1.16.5", synonyms: ["1 16 5", "nether update"] },
        { value: "1.18.2", label: "1.18.2", synonyms: ["1 18 2", "caves and cliffs"] },
        { value: "1.20.6", label: "1.20.6", synonyms: ["1 20 6", "trails and tales"] },
        { value: "1.21.1", label: "1.21.1", synonyms: ["1 21 1", "tricky trials"] },
        { value: "1.21.11", label: "1.21.11", synonyms: ["1 21 11"] },
        { value: "26.2", label: "26.2 (latest)", synonyms: ["26 2", "latest", "newest"] },
      ],
    },
    {
      kind: "select",
      id: "difficulty",
      label: "Difficulty",
      default: "normal",
      options: [
        { value: "peaceful", label: "Peaceful", synonyms: ["no drain", "easy mode"] },
        { value: "easy", label: "Easy", synonyms: ["floor 5 hearts"] },
        { value: "normal", label: "Normal", synonyms: ["default", "floor half heart"] },
        { value: "hard", label: "Hard", synonyms: ["starvation kills", "hardcore"] },
      ],
    },
    {
      kind: "select",
      id: "food",
      label: "Food",
      default: "cooked_beef",
      groups: [
        {
          label: "Meat",
          synonyms: ["meat", "cooked", "animal"],
          options: [
            { value: "cooked_beef", label: "Steak", synonyms: ["steak", "cooked beef", "cow"] },
            {
              value: "cooked_porkchop",
              label: "Cooked Porkchop",
              synonyms: ["pork", "pig", "bacon"],
            },
            { value: "cooked_mutton", label: "Cooked Mutton", synonyms: ["sheep", "lamb"] },
            { value: "cooked_chicken", label: "Cooked Chicken", synonyms: ["chicken"] },
            { value: "cooked_rabbit", label: "Cooked Rabbit", synonyms: ["rabbit"] },
            { value: "beef", label: "Raw Beef", synonyms: ["raw steak", "cow"] },
            { value: "porkchop", label: "Raw Porkchop", synonyms: ["raw pork"] },
            { value: "mutton", label: "Raw Mutton", synonyms: ["raw sheep"] },
            { value: "chicken", label: "Raw Chicken", synonyms: ["raw chicken", "hunger effect"] },
            { value: "rabbit", label: "Raw Rabbit", synonyms: ["raw rabbit"] },
            {
              value: "rotten_flesh",
              label: "Rotten Flesh",
              synonyms: ["zombie flesh", "junk food"],
            },
          ],
        },
        {
          label: "Fish",
          synonyms: ["fish", "seafood", "ocean"],
          options: [
            { value: "cooked_salmon", label: "Cooked Salmon", synonyms: ["salmon"] },
            { value: "cooked_cod", label: "Cooked Cod", synonyms: ["cod", "fish"] },
            { value: "salmon", label: "Raw Salmon", synonyms: ["raw fish"] },
            { value: "cod", label: "Raw Cod", synonyms: ["raw fish"] },
            { value: "tropical_fish", label: "Tropical Fish", synonyms: ["clownfish"] },
            { value: "pufferfish", label: "Pufferfish", synonyms: ["puffer", "poison"] },
            { value: "dried_kelp", label: "Dried Kelp", synonyms: ["kelp", "fast food"] },
          ],
        },
        {
          label: "Crops and plants",
          synonyms: ["crops", "farming", "vegetables", "fruit"],
          options: [
            { value: "bread", label: "Bread", synonyms: ["wheat"] },
            { value: "baked_potato", label: "Baked Potato", synonyms: ["potato"] },
            { value: "carrot", label: "Carrot", synonyms: ["carrots"] },
            { value: "potato", label: "Potato", synonyms: ["raw potato"] },
            { value: "beetroot", label: "Beetroot", synonyms: ["beet"] },
            { value: "apple", label: "Apple", synonyms: ["oak leaves"] },
            { value: "melon_slice", label: "Melon Slice", synonyms: ["melon"] },
            { value: "sweet_berries", label: "Sweet Berries", synonyms: ["berries", "bush"] },
            { value: "chorus_fruit", label: "Chorus Fruit", synonyms: ["end", "teleport"] },
            { value: "poisonous_potato", label: "Poisonous Potato", synonyms: ["poison potato"] },
            { value: "spider_eye", label: "Spider Eye", synonyms: ["poison"] },
          ],
        },
        {
          label: "Baked and crafted",
          synonyms: ["baked", "crafted", "cooking"],
          options: [
            { value: "pumpkin_pie", label: "Pumpkin Pie", synonyms: ["pie", "pumpkin"] },
            { value: "cookie", label: "Cookie", synonyms: ["cocoa"] },
            { value: "cake_slice", label: "Cake (one slice)", synonyms: ["cake", "slice"] },
          ],
        },
        {
          label: "Stews and bottles",
          synonyms: ["stew", "soup", "bowl", "bottle"],
          options: [
            { value: "rabbit_stew", label: "Rabbit Stew", synonyms: ["stew", "best per item"] },
            { value: "mushroom_stew", label: "Mushroom Stew", synonyms: ["soup", "mooshroom"] },
            { value: "beetroot_soup", label: "Beetroot Soup", synonyms: ["soup"] },
            {
              value: "suspicious_stew",
              label: "Suspicious Stew",
              synonyms: ["sus stew", "flower"],
            },
            { value: "honey_bottle", label: "Honey Bottle", synonyms: ["honey", "beehive"] },
          ],
        },
        {
          label: "Golden and rare",
          synonyms: ["golden", "rare", "gold"],
          options: [
            {
              value: "golden_carrot",
              label: "Golden Carrot",
              synonyms: ["best saturation", "gold carrot"],
            },
            { value: "golden_apple", label: "Golden Apple", synonyms: ["gapple"] },
            {
              value: "enchanted_golden_apple",
              label: "Enchanted Golden Apple",
              synonyms: ["god apple", "notch apple", "napple"],
            },
          ],
        },
      ],
    },
    {
      kind: "number",
      id: "startFood",
      label: "Starting hunger (0 to 20 points)",
      default: 20,
      min: 0,
      max: 20,
      step: 1,
    },
    {
      kind: "number",
      id: "startSaturation",
      label: "Starting saturation (0 to 20 points)",
      default: 5,
      min: 0,
      max: 20,
      step: 0.1,
    },
    {
      kind: "number",
      id: "startHealth",
      label: "Starting health (Regeneration mode)",
      default: 10,
      min: 0,
      max: 20,
      step: 0.5,
    },
    {
      kind: "number",
      id: "hearts",
      label: "Hearts to regenerate (Regeneration mode)",
      default: 5,
      min: 0.5,
      max: 10,
      step: 0.5,
    },
    {
      kind: "number",
      id: "sprintBlocksPerMinute",
      label: "Blocks sprinted per minute",
      default: 337,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "swimBlocksPerMinute",
      label: "Blocks swum per minute",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "jumpsPerMinute",
      label: "Jumps per minute",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "blocksMinedPerMinute",
      label: "Blocks broken per minute",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "hitsPerMinute",
      label: "Hits landed per minute",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "hitsTakenPerMinute",
      label: "Hits taken per minute",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
  ],
  copy: {
    what: "A real simulation of the Minecraft hunger system, not a copied table. Describe what you are doing (sprinting, jumping, mining, fighting, swimming, taking hits) and see the exhaustion it costs, how long your hunger bar and hidden saturation last, when sprinting cuts out, and when starvation starts biting. A food comparison ranks every edible item by hearts per item, hearts per inventory slot, and hearts per full inventory, so the usual answers (golden carrot, steak, cooked porkchop, rabbit stew) come out of the game's own numbers instead of being asserted. A regeneration planner runs the game's tick loop to time how long healing a given number of hearts takes and what it costs you in food. Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.",
    how: "Pick your version and difficulty, set your starting hunger and saturation, then set the activity rates for how you actually play: blocks sprinted per minute, jumps, blocks broken, hits landed, seconds spent swimming, and hits taken. The tiles update live with exhaustion per second, time to empty the bar, and time until sprinting stops. Switch to the food table to rank every food in that version, or open the regeneration card to time healing from a given health, hunger, and saturation. Everything lives in the page address, so a link reproduces your exact setup.",
    why: "Most Minecraft food charts are copies of a copy with no version attached, and none of them model exhaustion at all, which is the part that actually explains why your hunger bar empties. The numbers here were verified against the game's own decompiled code for 1.16.5, 1.18.2, 1.20.6, 1.21.1, 1.21.11, and 26.2: the food table comes from Foods.java for the older releases and from the vanilla item component data for 1.20.5 and later, the constants come from FoodConstants and FoodData, and every exhaustion amount is checked against its real call site in Player, ServerPlayer, Block, and the Hunger effect. The hunger loop itself is reimplemented as a per-tick simulation of FoodData#tick, so the regeneration and starvation timings are the game's own, and the golden vectors under mc-pipeline/vectors/hunger record the class and method each value came from. The math runs in your browser with no ads and no limits, and your files and inputs never leave your device.",
    faq: [
      {
        q: "What is the best food in Minecraft?",
        a: "Per inventory slot it is steak or cooked porkchop, at about 444 hearts of healing from one full stack. Both restore 8 hunger points and 12.8 saturation, which is 20.8 points, and every 3 points is one heart of natural regeneration. The golden carrot has the highest saturation in the game at 14.4, so it lasts longest before the hunger bar starts moving, but its 6 nutrition puts it slightly behind on total value. Rabbit stew is the best single item at 22 points, and the worst per slot of the three, because it stacks to 1.",
      },
      {
        q: "Why does my hunger bar drain so fast when I sprint?",
        a: "Sprinting costs 0.1 exhaustion per block, and every 4 exhaustion burns one point of saturation, or one point of the hunger bar once saturation is gone. Walking and crouching are free, swimming costs 0.01 per block, a jump costs 0.05, a sprint jump costs 0.2, breaking any block costs 0.005, and landing or taking a hit costs 0.1. Natural regeneration is usually the biggest drain of all: healing one health point adds 6 exhaustion, so a full heal from half a heart to full costs about 29 hunger and saturation points.",
      },
      {
        q: "Have the hunger mechanics changed between Minecraft versions?",
        a: "The mechanic itself has not. FoodData#tick is equivalent in all six verified versions: the 4 exhaustion cascade, the 80 tick normal heal at hunger 18 or more, the 10 tick saturated heal at a full bar, the 6 exhaustion per health point, and the starvation floors (Easy stops at 10 health, Normal at 1, Hard kills) are all unchanged. The food table moved: 1.17 added glow berries and made suspicious stew always edible, 1.20.5 moved food from Foods.java into item components and switched saturation from a modifier to an absolute value, 1.21 added the ominous bottle as a one point food and gave Peaceful a saturation refill, and 1.21.2 made honey bottles always drinkable while removing the ominous bottle's food component and adding food components to fish buckets that are still not edible.",
      },
    ],
  },
};
