/**
 * Curated OAuth scope catalog for the oauth-scope-decoder tool.
 *
 * Hand written from each provider's own scope reference. Only scopes whose
 * exact string and meaning are well established are listed; anything uncertain
 * is deliberately absent so the tool falls back to an honest "not in the
 * catalog" heuristic row instead of inventing a definition.
 *
 * `pattern` is either an exact scope string or a prefix pattern ending in `*`.
 * Exact matches always win; among prefix patterns the longest prefix wins.
 *
 * `risk` describes what the scope PERMITS. It is never a claim that a given
 * app misuses it.
 */

export type Risk = 'low' | 'moderate' | 'high' | 'critical';

export interface ScopeEntry {
  /** Exact scope string, or a prefix pattern ending in '*'. */
  pattern: string;
  /** Provider the scope belongs to, as users would name it. */
  provider: string;
  /** Short human label for the capability. */
  label: string;
  /** One sentence: what the app can DO with this. */
  plainEnglish: string;
  risk: Risk;
  /** Short reason the risk level is what it is. */
  riskWhy: string;
}

/** Google API scopes are namespaced under this prefix. */
export const GOOGLE_AUTH_PREFIX = 'https://www.googleapis.com/auth/';

/** Microsoft Graph permissions are often sent as fully qualified resource URIs. */
export const RESOURCE_PREFIXES = [
  'https://graph.microsoft.com/',
  'https://outlook.office.com/',
  'https://api.botframework.com/',
];

const G = GOOGLE_AUTH_PREFIX;

export const SCOPES: readonly ScopeEntry[] = [
  // ---------------------------------------------------------------- OpenID
  {
    pattern: 'openid',
    provider: 'OpenID Connect',
    label: 'Sign in',
    plainEnglish: 'Confirm who you are and receive a stable user id for you.',
    risk: 'low',
    riskWhy: 'Identity only. No access to your content.',
  },
  {
    pattern: 'profile',
    provider: 'OpenID Connect',
    label: 'Basic profile',
    plainEnglish: 'See your name, profile picture, locale and other basic profile fields.',
    risk: 'low',
    riskWhy: 'Public facing profile data only.',
  },
  {
    pattern: 'email',
    provider: 'OpenID Connect',
    label: 'Email address',
    plainEnglish: 'See the email address on your account and whether it is verified.',
    risk: 'low',
    riskWhy: 'One identifier, no mailbox access.',
  },
  {
    pattern: 'address',
    provider: 'OpenID Connect',
    label: 'Postal address',
    plainEnglish: 'See the postal address stored on your account.',
    risk: 'moderate',
    riskWhy: 'A home address is personal data worth more than a login identifier.',
  },
  {
    pattern: 'phone',
    provider: 'OpenID Connect',
    label: 'Phone number',
    plainEnglish: 'See the phone number stored on your account.',
    risk: 'moderate',
    riskWhy: 'Phone numbers are reused for account recovery and identity matching.',
  },
  {
    pattern: 'offline_access',
    provider: 'OpenID Connect',
    label: 'Refresh token',
    plainEnglish: 'Keep using the access it was granted after you close the app.',
    risk: 'moderate',
    riskWhy: 'Access continues while you are away and lasts until you revoke it.',
  },
  {
    pattern: '.default',
    provider: 'Microsoft identity platform',
    label: 'Previously consented permissions',
    plainEnglish:
      'Request every permission an administrator has already consented to for this app.',
    risk: 'moderate',
    riskWhy: 'The real access is whatever was consented earlier, which this list does not show.',
  },

  // ---------------------------------------------------------------- Google: Gmail
  {
    pattern: 'https://mail.google.com/',
    provider: 'Google',
    label: 'Full Gmail control',
    plainEnglish:
      'Read, send, change and permanently delete anything in your Gmail mailbox.',
    risk: 'critical',
    riskWhy: 'The widest Gmail scope there is, including irreversible deletion.',
  },
  {
    pattern: `${G}gmail.readonly`,
    provider: 'Google',
    label: 'Read all mail',
    plainEnglish: 'Read every message, thread, attachment and label in your Gmail account.',
    risk: 'high',
    riskWhy: 'Mailboxes hold password resets, invoices and private threads.',
  },
  {
    pattern: `${G}gmail.modify`,
    provider: 'Google',
    label: 'Read and change mail',
    plainEnglish: 'Read all your mail and also label, archive and trash messages.',
    risk: 'high',
    riskWhy: 'Full read plus the ability to hide or trash what arrives.',
  },
  {
    pattern: `${G}gmail.send`,
    provider: 'Google',
    label: 'Send mail',
    plainEnglish: 'Send email that comes from your address, without reading your existing mail.',
    risk: 'moderate',
    riskWhy: 'Recipients see and trust your address on anything it sends.',
  },
  {
    pattern: `${G}gmail.compose`,
    provider: 'Google',
    label: 'Drafts and sending',
    plainEnglish: 'Create, read, update and delete drafts, and send messages as you.',
    risk: 'high',
    riskWhy: 'Draft access plus send rights covers most of what a mailbox is used for.',
  },
  {
    pattern: `${G}gmail.labels`,
    provider: 'Google',
    label: 'Labels only',
    plainEnglish: 'Create, read and delete Gmail labels without touching message content.',
    risk: 'low',
    riskWhy: 'Organisational metadata only.',
  },
  {
    pattern: `${G}gmail.metadata`,
    provider: 'Google',
    label: 'Headers only',
    plainEnglish: 'Read message headers, labels and timestamps but not bodies or attachments.',
    risk: 'moderate',
    riskWhy: 'Headers still reveal who you talk to, how often and about what subject.',
  },
  {
    pattern: `${G}gmail.insert`,
    provider: 'Google',
    label: 'Insert mail',
    plainEnglish: 'Insert messages straight into your mailbox as if they had arrived.',
    risk: 'moderate',
    riskWhy: 'Inserted mail can be indistinguishable from real delivered mail.',
  },
  {
    pattern: `${G}gmail.settings.basic`,
    provider: 'Google',
    label: 'Gmail settings',
    plainEnglish: 'Change Gmail settings such as filters, signatures and vacation replies.',
    risk: 'high',
    riskWhy: 'A filter can silently archive or redirect incoming mail.',
  },
  {
    pattern: `${G}gmail.settings.sharing`,
    provider: 'Google',
    label: 'Forwarding and delegation',
    plainEnglish: 'Change Gmail forwarding addresses, delegation and send as identities.',
    risk: 'critical',
    riskWhy: 'Forwarding or delegation hands a copy of your mail to another account.',
  },
  {
    pattern: `${G}gmail.*`,
    provider: 'Google',
    label: 'Some Gmail access',
    plainEnglish: 'Reach part of your Gmail account under a scope not named in this catalog.',
    risk: 'high',
    riskWhy: 'Gmail scopes touch real message content unless they are metadata only.',
  },

  // ---------------------------------------------------------------- Google: Drive
  {
    pattern: `${G}drive`,
    provider: 'Google',
    label: 'Full Drive access',
    plainEnglish: 'See, create, change and delete every file in your Google Drive.',
    risk: 'critical',
    riskWhy: 'Covers all Drive content including files other people shared with you.',
  },
  {
    pattern: `${G}drive.readonly`,
    provider: 'Google',
    label: 'Read all of Drive',
    plainEnglish: 'Read every file and folder in your Google Drive, including their contents.',
    risk: 'high',
    riskWhy: 'Whole document archives, exports and backups are readable in one pass.',
  },
  {
    pattern: `${G}drive.file`,
    provider: 'Google',
    label: 'Per file access',
    plainEnglish: 'See and change only the files you explicitly open or create with this app.',
    risk: 'low',
    riskWhy: 'Scoped to files you hand it, one at a time.',
  },
  {
    pattern: `${G}drive.appdata`,
    provider: 'Google',
    label: 'Hidden app folder',
    plainEnglish: 'Read and write a hidden configuration folder only this app can see.',
    risk: 'low',
    riskWhy: 'Isolated from the rest of your Drive.',
  },
  {
    pattern: `${G}drive.metadata`,
    provider: 'Google',
    label: 'Drive metadata',
    plainEnglish: 'See and change file names, folders and sharing settings but not file contents.',
    risk: 'moderate',
    riskWhy: 'Changing sharing can expose a file without ever reading it.',
  },
  {
    pattern: `${G}drive.metadata.readonly`,
    provider: 'Google',
    label: 'Drive listing',
    plainEnglish: 'List file names, folders and sharing settings without reading contents.',
    risk: 'low',
    riskWhy: 'File names still leak topics, but no content is read.',
  },
  {
    pattern: `${G}drive.activity.readonly`,
    provider: 'Google',
    label: 'Drive activity',
    plainEnglish: 'Read the history of who viewed, edited and shared your Drive files.',
    risk: 'low',
    riskWhy: 'Activity records only, not file contents.',
  },
  {
    pattern: `${G}drive.scripts`,
    provider: 'Google',
    label: 'Apps Script files',
    plainEnglish: 'Change Google Apps Script project files stored in your Drive.',
    risk: 'moderate',
    riskWhy: 'Script files are code that can later run with your own access.',
  },
  {
    pattern: `${G}drive.*`,
    provider: 'Google',
    label: 'Some Drive access',
    plainEnglish: 'Reach part of your Google Drive under a scope not named in this catalog.',
    risk: 'high',
    riskWhy: 'Drive scopes usually reach file contents.',
  },

  // ---------------------------------------------------------------- Google: Calendar
  {
    pattern: `${G}calendar`,
    provider: 'Google',
    label: 'Full calendar access',
    plainEnglish: 'See, create, change and delete every calendar and event you own.',
    risk: 'moderate',
    riskWhy: 'Includes deleting events and changing who is invited.',
  },
  {
    pattern: `${G}calendar.readonly`,
    provider: 'Google',
    label: 'Read calendars',
    plainEnglish: 'Read all your calendars and the events on them.',
    risk: 'low',
    riskWhy: 'Read only, though event titles and guest lists are revealing.',
  },
  {
    pattern: `${G}calendar.events`,
    provider: 'Google',
    label: 'Manage events',
    plainEnglish: 'See, create, change and delete events on your calendars.',
    risk: 'moderate',
    riskWhy: 'Can add or remove meetings and invite people as you.',
  },
  {
    pattern: `${G}calendar.events.readonly`,
    provider: 'Google',
    label: 'Read events',
    plainEnglish: 'Read the events on your calendars.',
    risk: 'low',
    riskWhy: 'Read only.',
  },
  {
    pattern: `${G}calendar.settings.readonly`,
    provider: 'Google',
    label: 'Calendar settings',
    plainEnglish: 'Read your calendar settings such as time zone and working hours.',
    risk: 'low',
    riskWhy: 'Preferences only.',
  },

  // ---------------------------------------------------------------- Google: People
  {
    pattern: `${G}contacts`,
    provider: 'Google',
    label: 'Manage contacts',
    plainEnglish: 'See, create, change and delete the contacts in your account.',
    risk: 'moderate',
    riskWhy: 'Your address book is personal data about other people too.',
  },
  {
    pattern: `${G}contacts.readonly`,
    provider: 'Google',
    label: 'Read contacts',
    plainEnglish: 'Read your contacts, including names, email addresses and phone numbers.',
    risk: 'moderate',
    riskWhy: 'Contact lists map your whole personal and professional network.',
  },
  {
    pattern: `${G}contacts.other.readonly`,
    provider: 'Google',
    label: 'Read other contacts',
    plainEnglish: 'Read the automatic contacts Google built from people you have emailed.',
    risk: 'moderate',
    riskWhy: 'Often much larger than the address book you curated yourself.',
  },
  {
    pattern: `${G}directory.readonly`,
    provider: 'Google',
    label: 'Read the org directory',
    plainEnglish: 'Read the people directory of the organization your account belongs to.',
    risk: 'moderate',
    riskWhy: 'Exposes colleagues who never used this app.',
  },
  {
    pattern: `${G}userinfo.email`,
    provider: 'Google',
    label: 'Email address',
    plainEnglish: 'See the primary email address on your Google Account.',
    risk: 'low',
    riskWhy: 'One identifier, no mailbox access.',
  },
  {
    pattern: `${G}userinfo.profile`,
    provider: 'Google',
    label: 'Basic profile',
    plainEnglish: 'See your name, profile picture and other public profile details.',
    risk: 'low',
    riskWhy: 'Public facing profile data only.',
  },

  // ---------------------------------------------------------------- Google: Workspace docs
  {
    pattern: `${G}spreadsheets`,
    provider: 'Google',
    label: 'Manage Sheets',
    plainEnglish: 'See, create and change all your Google Sheets spreadsheets.',
    risk: 'high',
    riskWhy: 'Spreadsheets hold finance, customer and credential data more often than people expect.',
  },
  {
    pattern: `${G}spreadsheets.readonly`,
    provider: 'Google',
    label: 'Read Sheets',
    plainEnglish: 'Read all your Google Sheets spreadsheets.',
    risk: 'moderate',
    riskWhy: 'Read only, but it covers every spreadsheet you can open.',
  },
  {
    pattern: `${G}documents`,
    provider: 'Google',
    label: 'Manage Docs',
    plainEnglish: 'See, create and change all your Google Docs documents.',
    risk: 'high',
    riskWhy: 'Covers every document in the account, not just one.',
  },
  {
    pattern: `${G}documents.readonly`,
    provider: 'Google',
    label: 'Read Docs',
    plainEnglish: 'Read all your Google Docs documents.',
    risk: 'moderate',
    riskWhy: 'Read only across the whole account.',
  },
  {
    pattern: `${G}presentations`,
    provider: 'Google',
    label: 'Manage Slides',
    plainEnglish: 'See, create and change all your Google Slides presentations.',
    risk: 'high',
    riskWhy: 'Covers every presentation in the account.',
  },
  {
    pattern: `${G}presentations.readonly`,
    provider: 'Google',
    label: 'Read Slides',
    plainEnglish: 'Read all your Google Slides presentations.',
    risk: 'moderate',
    riskWhy: 'Read only across the whole account.',
  },
  {
    pattern: `${G}forms.body`,
    provider: 'Google',
    label: 'Manage Forms',
    plainEnglish: 'See and change the structure and settings of your Google Forms.',
    risk: 'moderate',
    riskWhy: 'Form questions can be rewritten to collect something else.',
  },
  {
    pattern: `${G}forms.responses.readonly`,
    provider: 'Google',
    label: 'Read form responses',
    plainEnglish: 'Read every answer people submitted to your Google Forms.',
    risk: 'moderate',
    riskWhy: 'Responses are data other people gave you in confidence.',
  },
  {
    pattern: `${G}script.projects`,
    provider: 'Google',
    label: 'Apps Script projects',
    plainEnglish: 'Create, read and update Google Apps Script projects in your account.',
    risk: 'high',
    riskWhy: 'Apps Script code runs later with your own account access.',
  },
  {
    pattern: `${G}tasks`,
    provider: 'Google',
    label: 'Manage tasks',
    plainEnglish: 'See, create, change and delete your Google Tasks.',
    risk: 'low',
    riskWhy: 'Task lists are narrow and usually low value to an attacker.',
  },
  {
    pattern: `${G}tasks.readonly`,
    provider: 'Google',
    label: 'Read tasks',
    plainEnglish: 'Read your Google Tasks lists and items.',
    risk: 'low',
    riskWhy: 'Read only, narrow surface.',
  },

  // ---------------------------------------------------------------- Google: YouTube
  {
    pattern: `${G}youtube`,
    provider: 'Google',
    label: 'Manage YouTube account',
    plainEnglish: 'Manage your YouTube account, including videos, playlists and subscriptions.',
    risk: 'high',
    riskWhy: 'Can change or remove published content and channel settings.',
  },
  {
    pattern: `${G}youtube.readonly`,
    provider: 'Google',
    label: 'Read YouTube account',
    plainEnglish: 'Read your YouTube account, including private videos and playlists.',
    risk: 'moderate',
    riskWhy: 'Private and unlisted uploads are visible.',
  },
  {
    pattern: `${G}youtube.upload`,
    provider: 'Google',
    label: 'Upload videos',
    plainEnglish: 'Upload videos to your YouTube channel.',
    risk: 'moderate',
    riskWhy: 'Anything uploaded is published under your channel name.',
  },
  {
    pattern: `${G}youtube.force-ssl`,
    provider: 'Google',
    label: 'Full YouTube access',
    plainEnglish:
      'Read and change everything in your YouTube account, including comments and live chat.',
    risk: 'high',
    riskWhy: 'The broadest YouTube scope, covering content and public interactions.',
  },
  {
    pattern: `${G}youtubepartner`,
    provider: 'Google',
    label: 'YouTube content management',
    plainEnglish: 'Manage your YouTube assets, channels and rights claims.',
    risk: 'high',
    riskWhy: 'Rights and channel management affects revenue and ownership.',
  },
  {
    pattern: `${G}yt-analytics.readonly`,
    provider: 'Google',
    label: 'YouTube analytics',
    plainEnglish: 'Read viewing statistics for your YouTube channels.',
    risk: 'low',
    riskWhy: 'Aggregate reporting data only.',
  },
  {
    pattern: `${G}yt-analytics-monetary.readonly`,
    provider: 'Google',
    label: 'YouTube revenue analytics',
    plainEnglish: 'Read revenue and monetary reports for your YouTube channels.',
    risk: 'moderate',
    riskWhy: 'Earnings figures are commercially sensitive.',
  },

  // ---------------------------------------------------------------- Google: Photos
  {
    pattern: `${G}photoslibrary`,
    provider: 'Google',
    label: 'Manage photo library',
    plainEnglish: 'View, upload and organize the photos and videos in your Google Photos library.',
    risk: 'high',
    riskWhy: 'Personal photo libraries are among the most sensitive data an account holds.',
  },
  {
    pattern: `${G}photoslibrary.readonly`,
    provider: 'Google',
    label: 'Read photo library',
    plainEnglish: 'View every photo, video and album in your Google Photos library.',
    risk: 'high',
    riskWhy: 'Photos carry faces, locations and documents people forget they photographed.',
  },
  {
    pattern: `${G}photoslibrary.appendonly`,
    provider: 'Google',
    label: 'Add photos only',
    plainEnglish: 'Add new photos and videos to your library without seeing existing ones.',
    risk: 'low',
    riskWhy: 'Write only, no read of what is already there.',
  },
  {
    pattern: `${G}photoslibrary.sharing`,
    provider: 'Google',
    label: 'Shared albums',
    plainEnglish: 'Create and manage shared albums and their share links on your behalf.',
    risk: 'moderate',
    riskWhy: 'Share links make photos reachable by anyone who has the link.',
  },

  // ---------------------------------------------------------------- Google Workspace admin
  {
    pattern: `${G}admin.directory.user`,
    provider: 'Google Workspace admin',
    label: 'Manage all users',
    plainEnglish: 'Create, change, suspend and delete any user in the Workspace domain.',
    risk: 'critical',
    riskWhy: 'Domain wide account control, including resetting passwords.',
  },
  {
    pattern: `${G}admin.directory.user.readonly`,
    provider: 'Google Workspace admin',
    label: 'Read all users',
    plainEnglish: 'Read every user account and profile in the Workspace domain.',
    risk: 'high',
    riskWhy: 'A full staff list is the starting point for targeted phishing.',
  },
  {
    pattern: `${G}admin.directory.user.security`,
    provider: 'Google Workspace admin',
    label: 'User security settings',
    plainEnglish:
      'Manage security settings for users, including app passwords and sign in tokens.',
    risk: 'critical',
    riskWhy: 'Can revoke or issue credentials that bypass normal sign in.',
  },
  {
    pattern: `${G}admin.directory.group`,
    provider: 'Google Workspace admin',
    label: 'Manage groups',
    plainEnglish: 'Create, change and delete groups and their membership across the domain.',
    risk: 'critical',
    riskWhy: 'Group membership usually decides who can read what.',
  },
  {
    pattern: `${G}admin.directory.group.readonly`,
    provider: 'Google Workspace admin',
    label: 'Read groups',
    plainEnglish: 'Read every group and its members across the domain.',
    risk: 'high',
    riskWhy: 'Reveals the access map of the whole organization.',
  },
  {
    pattern: `${G}admin.directory.orgunit`,
    provider: 'Google Workspace admin',
    label: 'Manage org units',
    plainEnglish: 'Create, change and delete organizational units in the domain.',
    risk: 'critical',
    riskWhy: 'Org units carry policy, so moving a user changes what rules apply.',
  },
  {
    pattern: `${G}admin.directory.device.mobile`,
    provider: 'Google Workspace admin',
    label: 'Manage mobile devices',
    plainEnglish: 'Manage mobile devices enrolled in the domain, including wiping them.',
    risk: 'critical',
    riskWhy: 'A remote wipe destroys data on a real person device.',
  },
  {
    pattern: `${G}admin.directory.rolemanagement`,
    provider: 'Google Workspace admin',
    label: 'Manage admin roles',
    plainEnglish: 'Create admin roles and assign them to any user in the domain.',
    risk: 'critical',
    riskWhy: 'Role assignment can promote any account to full administrator.',
  },
  {
    pattern: `${G}admin.directory.domain`,
    provider: 'Google Workspace admin',
    label: 'Manage domains',
    plainEnglish: 'Add, verify and remove domains on the Workspace account.',
    risk: 'critical',
    riskWhy: 'Domain control decides which addresses the organization trusts.',
  },
  {
    pattern: `${G}admin.reports.audit.readonly`,
    provider: 'Google Workspace admin',
    label: 'Read audit logs',
    plainEnglish: 'Read the domain wide audit log of who did what and when.',
    risk: 'high',
    riskWhy: 'Audit logs describe the behaviour of every person in the domain.',
  },
  {
    pattern: `${G}admin.reports.usage.readonly`,
    provider: 'Google Workspace admin',
    label: 'Read usage reports',
    plainEnglish: 'Read usage and adoption reports for all users in the domain.',
    risk: 'moderate',
    riskWhy: 'Aggregate reporting, but per user rows are included.',
  },
  {
    pattern: `${G}admin.directory.*`,
    provider: 'Google Workspace admin',
    label: 'Directory administration',
    plainEnglish: 'Read or change Workspace directory data for the whole domain.',
    risk: 'critical',
    riskWhy: 'Admin directory scopes act on every account in the organization.',
  },
  {
    pattern: `${G}admin.reports.*`,
    provider: 'Google Workspace admin',
    label: 'Domain reports',
    plainEnglish: 'Read Workspace audit or usage reporting for the whole domain.',
    risk: 'high',
    riskWhy: 'Reporting covers every user, not only the person consenting.',
  },

  // ---------------------------------------------------------------- Google Cloud
  {
    pattern: `${G}cloud-platform`,
    provider: 'Google Cloud',
    label: 'Full cloud access',
    plainEnglish: 'Act as you across every Google Cloud service and all data in your projects.',
    risk: 'critical',
    riskWhy: 'One scope that covers databases, storage, compute, keys and billing.',
  },
  {
    pattern: `${G}cloud-platform.read-only`,
    provider: 'Google Cloud',
    label: 'Read all cloud data',
    plainEnglish: 'Read data and configuration across every Google Cloud service in your projects.',
    risk: 'high',
    riskWhy: 'Read only, but it still spans every service and dataset.',
  },
  {
    pattern: `${G}devstorage.read_only`,
    provider: 'Google Cloud',
    label: 'Read Cloud Storage',
    plainEnglish: 'Read objects and buckets in your Cloud Storage projects.',
    risk: 'moderate',
    riskWhy: 'Buckets often hold backups and exports.',
  },
  {
    pattern: `${G}devstorage.read_write`,
    provider: 'Google Cloud',
    label: 'Read and write Cloud Storage',
    plainEnglish: 'Read, upload and overwrite objects in your Cloud Storage buckets.',
    risk: 'high',
    riskWhy: 'Overwriting an object can change what your own systems later serve.',
  },
  {
    pattern: `${G}devstorage.full_control`,
    provider: 'Google Cloud',
    label: 'Full Cloud Storage control',
    plainEnglish: 'Full control of your Cloud Storage buckets, objects and their permissions.',
    risk: 'critical',
    riskWhy: 'Includes deletion and making private buckets public.',
  },
  {
    pattern: `${G}bigquery`,
    provider: 'Google Cloud',
    label: 'BigQuery access',
    plainEnglish: 'Run queries and manage datasets, tables and jobs in BigQuery.',
    risk: 'high',
    riskWhy: 'Warehouses usually contain the joined version of everything sensitive.',
  },
  {
    pattern: `${G}bigquery.readonly`,
    provider: 'Google Cloud',
    label: 'Read BigQuery',
    plainEnglish: 'Read data and metadata in your BigQuery datasets.',
    risk: 'moderate',
    riskWhy: 'Read only, but analytics warehouses aggregate personal data.',
  },
  {
    pattern: `${G}compute`,
    provider: 'Google Cloud',
    label: 'Manage Compute Engine',
    plainEnglish: 'Create, change and delete Compute Engine resources in your projects.',
    risk: 'critical',
    riskWhy: 'Machine control means code execution and cost exposure.',
  },
  {
    pattern: `${G}compute.readonly`,
    provider: 'Google Cloud',
    label: 'Read Compute Engine',
    plainEnglish: 'Read the configuration of Compute Engine resources in your projects.',
    risk: 'moderate',
    riskWhy: 'Infrastructure layout is useful reconnaissance.',
  },
  {
    pattern: `${G}cloud-billing`,
    provider: 'Google Cloud',
    label: 'Manage billing',
    plainEnglish: 'View and manage billing accounts and which projects they pay for.',
    risk: 'critical',
    riskWhy: 'Billing changes can move real money and disable projects.',
  },
  {
    pattern: `${G}cloud-billing.readonly`,
    provider: 'Google Cloud',
    label: 'Read billing',
    plainEnglish: 'View billing accounts, budgets and charges.',
    risk: 'low',
    riskWhy: 'Financial totals only, no changes.',
  },
  {
    pattern: `${G}logging.read`,
    provider: 'Google Cloud',
    label: 'Read logs',
    plainEnglish: 'Read log entries from your Cloud projects.',
    risk: 'moderate',
    riskWhy: 'Application logs frequently contain tokens and user data by accident.',
  },
  {
    pattern: `${G}logging.write`,
    provider: 'Google Cloud',
    label: 'Write logs',
    plainEnglish: 'Write new log entries into your Cloud projects.',
    risk: 'low',
    riskWhy: 'Append only, no reading of existing logs.',
  },
  {
    pattern: `${G}pubsub`,
    provider: 'Google Cloud',
    label: 'Pub/Sub messaging',
    plainEnglish: 'Publish and consume messages on your Pub/Sub topics and subscriptions.',
    risk: 'high',
    riskWhy: 'Message streams often carry the live contents of your systems.',
  },
  {
    pattern: `${G}datastore`,
    provider: 'Google Cloud',
    label: 'Firestore and Datastore',
    plainEnglish: 'Read and write records in your Firestore and Datastore databases.',
    risk: 'high',
    riskWhy: 'Direct database access on the application data store.',
  },
  {
    pattern: `${G}firebase`,
    provider: 'Google Cloud',
    label: 'Manage Firebase',
    plainEnglish: 'View and manage your Firebase projects and their configuration.',
    risk: 'high',
    riskWhy: 'Project configuration decides how your apps authenticate users.',
  },
  {
    pattern: `${G}analytics.readonly`,
    provider: 'Google',
    label: 'Read Analytics',
    plainEnglish: 'Read the reports and data in your Google Analytics accounts.',
    risk: 'low',
    riskWhy: 'Aggregate traffic reporting.',
  },
  {
    pattern: `${G}analytics`,
    provider: 'Google',
    label: 'Manage Analytics',
    plainEnglish: 'View and manage your Google Analytics accounts, properties and data.',
    risk: 'moderate',
    riskWhy: 'Configuration changes can break or redirect measurement.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: identity
  {
    pattern: 'User.Read',
    provider: 'Microsoft Graph',
    label: 'Sign in and read your profile',
    plainEnglish: 'Sign you in and read your own user profile.',
    risk: 'low',
    riskWhy: 'Your own profile only.',
  },
  {
    pattern: 'User.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Change your profile',
    plainEnglish: 'Read and update your own user profile.',
    risk: 'moderate',
    riskWhy: 'Profile fields such as contact details can be rewritten.',
  },
  {
    pattern: 'User.ReadBasic.All',
    provider: 'Microsoft Graph',
    label: 'Read basic profiles of all users',
    plainEnglish: 'Read the basic profile of every user in the organization.',
    risk: 'moderate',
    riskWhy: 'Covers colleagues who never consented to this app.',
  },
  {
    pattern: 'User.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all user profiles',
    plainEnglish: 'Read the full profile of every user in the organization.',
    risk: 'high',
    riskWhy: 'The All suffix means the whole tenant, not just you.',
  },
  {
    pattern: 'User.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage all users',
    plainEnglish: 'Read and change every user account in the organization.',
    risk: 'critical',
    riskWhy: 'Tenant wide account control, including profile and account state.',
  },
  {
    pattern: 'People.Read',
    provider: 'Microsoft Graph',
    label: 'Read relevant people',
    plainEnglish: 'Read the list of people most relevant to you.',
    risk: 'low',
    riskWhy: 'A relevance ranked contact list, no message content.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: mail
  {
    pattern: 'Mail.Read',
    provider: 'Microsoft Graph',
    label: 'Read your mail',
    plainEnglish: 'Read every message and attachment in your mailbox.',
    risk: 'high',
    riskWhy: 'Mailboxes hold password resets and confidential threads.',
  },
  {
    pattern: 'Mail.ReadBasic',
    provider: 'Microsoft Graph',
    label: 'Read mail metadata',
    plainEnglish: 'Read your mail except the message body, attachments and extended properties.',
    risk: 'moderate',
    riskWhy: 'Subjects and correspondents are still visible.',
  },
  {
    pattern: 'Mail.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your mail',
    plainEnglish: 'Read, create, change and delete mail in your mailbox.',
    risk: 'high',
    riskWhy: 'Full read plus the ability to delete or alter messages.',
  },
  {
    pattern: 'Mail.Send',
    provider: 'Microsoft Graph',
    label: 'Send mail as you',
    plainEnglish: 'Send email that comes from your address.',
    risk: 'moderate',
    riskWhy: 'Recipients trust mail that arrives from your account.',
  },
  {
    pattern: 'Mail.Read.Shared',
    provider: 'Microsoft Graph',
    label: 'Read shared mailboxes',
    plainEnglish: 'Read your mail and any mailbox that has been shared with you.',
    risk: 'high',
    riskWhy: 'Reaches mailboxes belonging to other people.',
  },
  {
    pattern: 'Mail.ReadWrite.Shared',
    provider: 'Microsoft Graph',
    label: 'Manage shared mailboxes',
    plainEnglish: 'Read, change and delete mail in your mailbox and in mailboxes shared with you.',
    risk: 'high',
    riskWhy: 'Write access to other people mailboxes.',
  },
  {
    pattern: 'Mail.Send.Shared',
    provider: 'Microsoft Graph',
    label: 'Send as or on behalf of others',
    plainEnglish: 'Send mail as you or on behalf of accounts that granted you delegate rights.',
    risk: 'moderate',
    riskWhy: 'Messages can appear to come from someone else.',
  },
  {
    pattern: 'MailboxSettings.Read',
    provider: 'Microsoft Graph',
    label: 'Read mailbox settings',
    plainEnglish: 'Read your mailbox settings, including rules, automatic replies and time zone.',
    risk: 'moderate',
    riskWhy: 'Rules reveal how mail is routed and hidden.',
  },
  {
    pattern: 'MailboxSettings.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Change mailbox settings',
    plainEnglish: 'Read and change your mailbox settings, including inbox rules and forwarding.',
    risk: 'high',
    riskWhy: 'An inbox rule can forward or delete incoming mail without you noticing.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: calendar and contacts
  {
    pattern: 'Calendars.Read',
    provider: 'Microsoft Graph',
    label: 'Read your calendars',
    plainEnglish: 'Read the events on your calendars.',
    risk: 'moderate',
    riskWhy: 'Event titles and attendee lists describe your work in detail.',
  },
  {
    pattern: 'Calendars.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your calendars',
    plainEnglish: 'Read, create, change and delete events on your calendars.',
    risk: 'moderate',
    riskWhy: 'Can send invitations and cancellations as you.',
  },
  {
    pattern: 'Calendars.Read.Shared',
    provider: 'Microsoft Graph',
    label: 'Read shared calendars',
    plainEnglish: 'Read your calendars and any calendar shared with you.',
    risk: 'moderate',
    riskWhy: 'Reaches calendars belonging to other people.',
  },
  {
    pattern: 'Calendars.ReadWrite.Shared',
    provider: 'Microsoft Graph',
    label: 'Manage shared calendars',
    plainEnglish: 'Read and change your calendars and any calendar shared with you.',
    risk: 'high',
    riskWhy: 'Write access to other people calendars.',
  },
  {
    pattern: 'Contacts.Read',
    provider: 'Microsoft Graph',
    label: 'Read your contacts',
    plainEnglish: 'Read the contacts stored in your mailbox.',
    risk: 'moderate',
    riskWhy: 'Address books are personal data about other people.',
  },
  {
    pattern: 'Contacts.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your contacts',
    plainEnglish: 'Read, create, change and delete the contacts in your mailbox.',
    risk: 'moderate',
    riskWhy: 'Contact records can be altered, including email addresses.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: files
  {
    pattern: 'Files.Read',
    provider: 'Microsoft Graph',
    label: 'Read your files',
    plainEnglish: 'Read the files in your own OneDrive.',
    risk: 'moderate',
    riskWhy: 'Covers your whole personal drive, not selected files.',
  },
  {
    pattern: 'Files.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all files you can access',
    plainEnglish: 'Read every file you can reach, across OneDrive and SharePoint.',
    risk: 'high',
    riskWhy: 'Includes team sites and files other people shared with you.',
  },
  {
    pattern: 'Files.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your files',
    plainEnglish: 'Read, create, change and delete files in your own OneDrive.',
    risk: 'high',
    riskWhy: 'Deletion and overwriting apply to your whole drive.',
  },
  {
    pattern: 'Files.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage all files you can access',
    plainEnglish:
      'Read, create, change and delete every file you can reach, across OneDrive and SharePoint.',
    risk: 'critical',
    riskWhy: 'Write and delete across organization wide document storage.',
  },
  {
    pattern: 'Files.ReadWrite.AppFolder',
    provider: 'Microsoft Graph',
    label: 'App folder only',
    plainEnglish: 'Read and write only inside a folder created for this app.',
    risk: 'low',
    riskWhy: 'Isolated from the rest of your drive.',
  },
  {
    pattern: 'Sites.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all SharePoint sites',
    plainEnglish: 'Read items and lists in all SharePoint sites you can access.',
    risk: 'high',
    riskWhy: 'SharePoint is where organizations keep shared documents.',
  },
  {
    pattern: 'Sites.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage all SharePoint sites',
    plainEnglish: 'Read and change items and lists in all SharePoint sites you can access.',
    risk: 'critical',
    riskWhy: 'Write access across organization wide document storage.',
  },
  {
    pattern: 'Sites.Manage.All',
    provider: 'Microsoft Graph',
    label: 'Manage SharePoint lists and sites',
    plainEnglish: 'Create and delete lists, items and sites in SharePoint.',
    risk: 'critical',
    riskWhy: 'Structural changes to shared sites affect everyone using them.',
  },
  {
    pattern: 'Sites.FullControl.All',
    provider: 'Microsoft Graph',
    label: 'Full SharePoint control',
    plainEnglish: 'Full control of all SharePoint sites, including permissions.',
    risk: 'critical',
    riskWhy: 'Permission control can open shared sites to anyone.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: directory and governance
  {
    pattern: 'Directory.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read directory data',
    plainEnglish: 'Read directory data for the whole tenant: users, groups, apps and roles.',
    risk: 'high',
    riskWhy: 'A complete map of the organization and its access model.',
  },
  {
    pattern: 'Directory.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage directory data',
    plainEnglish: 'Read and change directory data across the whole tenant.',
    risk: 'critical',
    riskWhy: 'Tenant wide write access to users, groups and applications.',
  },
  {
    pattern: 'Directory.AccessAsUser.All',
    provider: 'Microsoft Graph',
    label: 'Act on the directory as you',
    plainEnglish: 'Perform directory operations with exactly the rights your account has.',
    risk: 'critical',
    riskWhy: 'If you are an administrator, so is the app.',
  },
  {
    pattern: 'Group.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all groups',
    plainEnglish: 'Read all groups in the tenant, including membership and group content.',
    risk: 'high',
    riskWhy: 'Group content can include Teams conversations and files.',
  },
  {
    pattern: 'Group.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage all groups',
    plainEnglish: 'Create, change and delete any group in the tenant, including membership.',
    risk: 'critical',
    riskWhy: 'Group membership is how most access is granted.',
  },
  {
    pattern: 'GroupMember.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read group membership',
    plainEnglish: 'Read the membership of all groups in the tenant.',
    risk: 'moderate',
    riskWhy: 'Membership lists reveal who can reach what.',
  },
  {
    pattern: 'GroupMember.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Change group membership',
    plainEnglish: 'Add and remove members from any group in the tenant.',
    risk: 'high',
    riskWhy: 'Adding an account to a group silently grants its access.',
  },
  {
    pattern: 'Application.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read app registrations',
    plainEnglish: 'Read all application registrations and service principals in the tenant.',
    risk: 'high',
    riskWhy: 'Shows which apps hold which permissions.',
  },
  {
    pattern: 'Application.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage app registrations',
    plainEnglish: 'Create and change application registrations, including their credentials.',
    risk: 'critical',
    riskWhy: 'Adding a client secret to an existing app is a durable back door.',
  },
  {
    pattern: 'AppRoleAssignment.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Grant app permissions',
    plainEnglish: 'Grant application permissions to any app in the tenant.',
    risk: 'critical',
    riskWhy: 'An app that can grant permissions can escalate itself.',
  },
  {
    pattern: 'RoleManagement.ReadWrite.Directory',
    provider: 'Microsoft Graph',
    label: 'Manage admin roles',
    plainEnglish: 'Assign and remove directory roles, including administrator roles.',
    risk: 'critical',
    riskWhy: 'Direct path to full tenant administration.',
  },
  {
    pattern: 'Policy.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read policies',
    plainEnglish: 'Read the tenant policies, including conditional access rules.',
    risk: 'moderate',
    riskWhy: 'Reveals exactly which sign in protections exist.',
  },
  {
    pattern: 'Policy.ReadWrite.ConditionalAccess',
    provider: 'Microsoft Graph',
    label: 'Change conditional access',
    plainEnglish: 'Read and change conditional access policies for the tenant.',
    risk: 'critical',
    riskWhy: 'Conditional access decides who may sign in and whether MFA is required.',
  },
  {
    pattern: 'AuditLog.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read audit logs',
    plainEnglish: 'Read the tenant sign in logs and directory audit logs.',
    risk: 'high',
    riskWhy: 'Audit data describes every account in the tenant.',
  },
  {
    pattern: 'Reports.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read usage reports',
    plainEnglish: 'Read usage reports for the tenant, including per user activity.',
    risk: 'moderate',
    riskWhy: 'Activity reporting about people who never used this app.',
  },
  {
    pattern: 'Device.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all devices',
    plainEnglish: 'Read the properties of all devices registered in the tenant.',
    risk: 'moderate',
    riskWhy: 'Device inventory is useful reconnaissance.',
  },
  {
    pattern: 'DeviceManagementManagedDevices.ReadWrite.All',
    provider: 'Microsoft Graph',
    label: 'Manage enrolled devices',
    plainEnglish: 'Read and change managed devices in Intune, including remote wipe and retire.',
    risk: 'critical',
    riskWhy: 'A remote wipe destroys data on someone real device.',
  },

  // ---------------------------------------------------------------- Microsoft Graph: Teams and notes
  {
    pattern: 'Team.ReadBasic.All',
    provider: 'Microsoft Graph',
    label: 'List teams',
    plainEnglish: 'Read the names and descriptions of teams you belong to.',
    risk: 'low',
    riskWhy: 'Names only, no message content.',
  },
  {
    pattern: 'Channel.ReadBasic.All',
    provider: 'Microsoft Graph',
    label: 'List channels',
    plainEnglish: 'Read the names and descriptions of channels in teams you belong to.',
    risk: 'low',
    riskWhy: 'Names only, no message content.',
  },
  {
    pattern: 'ChannelMessage.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read channel messages',
    plainEnglish: 'Read every message in the Teams channels you can access.',
    risk: 'high',
    riskWhy: 'Channel history is where working conversations and links live.',
  },
  {
    pattern: 'ChannelMessage.Send',
    provider: 'Microsoft Graph',
    label: 'Post channel messages',
    plainEnglish: 'Post messages to Teams channels as you.',
    risk: 'moderate',
    riskWhy: 'Colleagues will read the messages as coming from you.',
  },
  {
    pattern: 'Chat.Read',
    provider: 'Microsoft Graph',
    label: 'Read your chats',
    plainEnglish: 'Read the messages in your Teams chats.',
    risk: 'high',
    riskWhy: 'Private one to one conversations are included.',
  },
  {
    pattern: 'Chat.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Read and send chats',
    plainEnglish: 'Read your Teams chats and send messages in them as you.',
    risk: 'high',
    riskWhy: 'Read and write on private conversations.',
  },
  {
    pattern: 'Presence.Read',
    provider: 'Microsoft Graph',
    label: 'Read your presence',
    plainEnglish: 'See whether you are available, busy or away.',
    risk: 'low',
    riskWhy: 'Status only.',
  },
  {
    pattern: 'Notes.Read',
    provider: 'Microsoft Graph',
    label: 'Read your notebooks',
    plainEnglish: 'Read your OneNote notebooks and their pages.',
    risk: 'moderate',
    riskWhy: 'Notebooks often hold drafts, notes and copied credentials.',
  },
  {
    pattern: 'Notes.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your notebooks',
    plainEnglish: 'Read and change your OneNote notebooks and pages.',
    risk: 'moderate',
    riskWhy: 'Notes can be altered as well as read.',
  },
  {
    pattern: 'Notes.Read.All',
    provider: 'Microsoft Graph',
    label: 'Read all notebooks',
    plainEnglish: 'Read every OneNote notebook you can access, including shared ones.',
    risk: 'high',
    riskWhy: 'Reaches notebooks belonging to teams and other people.',
  },
  {
    pattern: 'Tasks.Read',
    provider: 'Microsoft Graph',
    label: 'Read your tasks',
    plainEnglish: 'Read your To Do task lists and items.',
    risk: 'low',
    riskWhy: 'Narrow surface.',
  },
  {
    pattern: 'Tasks.ReadWrite',
    provider: 'Microsoft Graph',
    label: 'Manage your tasks',
    plainEnglish: 'Read, create, change and delete your To Do tasks.',
    risk: 'low',
    riskWhy: 'Narrow surface.',
  },

  // ---------------------------------------------------------------- GitHub
  {
    pattern: 'repo',
    provider: 'GitHub',
    label: 'Full repository access',
    plainEnglish:
      'Read and write every repository you can access, public and private, including code, issues and settings.',
    risk: 'high',
    riskWhy: 'Covers all private source code, not one repository.',
  },
  {
    pattern: 'public_repo',
    provider: 'GitHub',
    label: 'Public repositories',
    plainEnglish: 'Read and write your public repositories only.',
    risk: 'moderate',
    riskWhy: 'No private code, but it can push commits under your name.',
  },
  {
    pattern: 'repo:status',
    provider: 'GitHub',
    label: 'Commit statuses',
    plainEnglish: 'Read and write commit status checks, without access to code.',
    risk: 'low',
    riskWhy: 'Status metadata only.',
  },
  {
    pattern: 'repo_deployment',
    provider: 'GitHub',
    label: 'Deployment statuses',
    plainEnglish: 'Read and write deployment statuses, without access to code.',
    risk: 'low',
    riskWhy: 'Deployment metadata only.',
  },
  {
    pattern: 'repo:invite',
    provider: 'GitHub',
    label: 'Repository invitations',
    plainEnglish: 'Accept and decline repository collaboration invitations.',
    risk: 'low',
    riskWhy: 'Invitation handling only.',
  },
  {
    pattern: 'security_events',
    provider: 'GitHub',
    label: 'Security alerts',
    plainEnglish: 'Read and write code scanning and secret scanning alerts.',
    risk: 'moderate',
    riskWhy: 'Alerts describe unfixed vulnerabilities in your code.',
  },
  {
    pattern: 'delete_repo',
    provider: 'GitHub',
    label: 'Delete repositories',
    plainEnglish: 'Delete repositories that you administer.',
    risk: 'critical',
    riskWhy: 'Deletion is immediate and recovery is limited.',
  },
  {
    pattern: 'workflow',
    provider: 'GitHub',
    label: 'Update Actions workflows',
    plainEnglish: 'Add and update GitHub Actions workflow files in your repositories.',
    risk: 'high',
    riskWhy: 'Workflow files run code in CI with access to repository secrets.',
  },
  {
    pattern: 'codespace',
    provider: 'GitHub',
    label: 'Manage codespaces',
    plainEnglish: 'Create, start, stop and delete codespaces on your account.',
    risk: 'high',
    riskWhy: 'A codespace runs code in an environment holding your repository access.',
  },
  {
    pattern: 'admin:org',
    provider: 'GitHub',
    label: 'Organization administration',
    plainEnglish: 'Fully manage organizations you administer, including members, teams and settings.',
    risk: 'critical',
    riskWhy: 'Org admin can add outside collaborators to every private repository.',
  },
  {
    pattern: 'write:org',
    provider: 'GitHub',
    label: 'Write org membership',
    plainEnglish: 'Read and change organization membership and team membership.',
    risk: 'high',
    riskWhy: 'Team membership decides repository access.',
  },
  {
    pattern: 'read:org',
    provider: 'GitHub',
    label: 'Read org membership',
    plainEnglish: 'Read organization membership, teams and projects.',
    risk: 'low',
    riskWhy: 'Membership listing only.',
  },
  {
    pattern: 'admin:org_hook',
    provider: 'GitHub',
    label: 'Organization webhooks',
    plainEnglish: 'Create, change and delete webhooks on organizations you administer.',
    risk: 'high',
    riskWhy: 'An org webhook can stream every event to an outside server.',
  },
  {
    pattern: 'admin:repo_hook',
    provider: 'GitHub',
    label: 'Repository webhooks',
    plainEnglish: 'Create, change and delete webhooks on your repositories.',
    risk: 'high',
    riskWhy: 'A webhook can forward every push and comment somewhere else.',
  },
  {
    pattern: 'write:repo_hook',
    provider: 'GitHub',
    label: 'Write repository webhooks',
    plainEnglish: 'Create and change webhooks on your repositories.',
    risk: 'moderate',
    riskWhy: 'Can add a listener for repository events.',
  },
  {
    pattern: 'read:repo_hook',
    provider: 'GitHub',
    label: 'Read repository webhooks',
    plainEnglish: 'Read the webhooks configured on your repositories.',
    risk: 'low',
    riskWhy: 'Configuration listing only.',
  },
  {
    pattern: 'admin:public_key',
    provider: 'GitHub',
    label: 'Manage SSH keys',
    plainEnglish: 'Add, list and remove SSH public keys on your account.',
    risk: 'moderate',
    riskWhy: 'A new SSH key keeps working after the token itself is revoked.',
  },
  {
    pattern: 'write:public_key',
    provider: 'GitHub',
    label: 'Add SSH keys',
    plainEnglish: 'Create and list SSH public keys on your account.',
    risk: 'moderate',
    riskWhy: 'Adds durable access outside the OAuth token.',
  },
  {
    pattern: 'read:public_key',
    provider: 'GitHub',
    label: 'Read SSH keys',
    plainEnglish: 'List the SSH public keys on your account.',
    risk: 'low',
    riskWhy: 'Public key material only.',
  },
  {
    pattern: 'admin:gpg_key',
    provider: 'GitHub',
    label: 'Manage GPG keys',
    plainEnglish: 'Add, list and remove GPG signing keys on your account.',
    risk: 'moderate',
    riskWhy: 'Signing keys affect whether commits appear verified.',
  },
  {
    pattern: 'write:gpg_key',
    provider: 'GitHub',
    label: 'Add GPG keys',
    plainEnglish: 'Create and list GPG signing keys on your account.',
    risk: 'moderate',
    riskWhy: 'Affects commit signature verification.',
  },
  {
    pattern: 'read:gpg_key',
    provider: 'GitHub',
    label: 'Read GPG keys',
    plainEnglish: 'List the GPG signing keys on your account.',
    risk: 'low',
    riskWhy: 'Public key material only.',
  },
  {
    pattern: 'gist',
    provider: 'GitHub',
    label: 'Manage gists',
    plainEnglish: 'Create, change and delete gists on your account, including secret gists.',
    risk: 'moderate',
    riskWhy: 'Secret gists often hold snippets people meant to keep private.',
  },
  {
    pattern: 'notifications',
    provider: 'GitHub',
    label: 'Read notifications',
    plainEnglish: 'Read your notifications and mark them as read.',
    risk: 'low',
    riskWhy: 'Notification metadata only.',
  },
  {
    pattern: 'user',
    provider: 'GitHub',
    label: 'Manage your profile',
    plainEnglish: 'Read and change your profile data, including email addresses and follows.',
    risk: 'moderate',
    riskWhy: 'Changing a primary email address affects account recovery.',
  },
  {
    pattern: 'read:user',
    provider: 'GitHub',
    label: 'Read your profile',
    plainEnglish: 'Read your profile data.',
    risk: 'low',
    riskWhy: 'Profile read only.',
  },
  {
    pattern: 'user:email',
    provider: 'GitHub',
    label: 'Read your email addresses',
    plainEnglish: 'Read the email addresses on your account, including private ones.',
    risk: 'low',
    riskWhy: 'Email addresses only, no mailbox access.',
  },
  {
    pattern: 'user:follow',
    provider: 'GitHub',
    label: 'Follow and unfollow',
    plainEnglish: 'Follow and unfollow other GitHub users as you.',
    risk: 'low',
    riskWhy: 'Public social actions only.',
  },
  {
    pattern: 'write:discussion',
    provider: 'GitHub',
    label: 'Write discussions',
    plainEnglish: 'Read and write team discussions as you.',
    risk: 'moderate',
    riskWhy: 'Posts appear under your name.',
  },
  {
    pattern: 'read:discussion',
    provider: 'GitHub',
    label: 'Read discussions',
    plainEnglish: 'Read team discussions.',
    risk: 'low',
    riskWhy: 'Read only.',
  },
  {
    pattern: 'write:packages',
    provider: 'GitHub',
    label: 'Publish packages',
    plainEnglish: 'Upload and publish packages to GitHub Packages.',
    risk: 'high',
    riskWhy: 'A published package runs on whatever machine installs it.',
  },
  {
    pattern: 'read:packages',
    provider: 'GitHub',
    label: 'Download packages',
    plainEnglish: 'Download packages from GitHub Packages.',
    risk: 'low',
    riskWhy: 'Read only.',
  },
  {
    pattern: 'delete:packages',
    provider: 'GitHub',
    label: 'Delete packages',
    plainEnglish: 'Delete published packages from GitHub Packages.',
    risk: 'high',
    riskWhy: 'Removing a package can break every build that depends on it.',
  },
  {
    pattern: 'project',
    provider: 'GitHub',
    label: 'Manage projects',
    plainEnglish: 'Read and write GitHub Projects boards you can access.',
    risk: 'moderate',
    riskWhy: 'Boards often describe unreleased plans.',
  },
  {
    pattern: 'read:project',
    provider: 'GitHub',
    label: 'Read projects',
    plainEnglish: 'Read GitHub Projects boards you can access.',
    risk: 'low',
    riskWhy: 'Read only.',
  },
  {
    pattern: 'admin:enterprise',
    provider: 'GitHub',
    label: 'Enterprise administration',
    plainEnglish: 'Fully manage the enterprise account, its settings and its organizations.',
    risk: 'critical',
    riskWhy: 'The highest level of control GitHub offers.',
  },
  {
    pattern: 'manage_billing:enterprise',
    provider: 'GitHub',
    label: 'Enterprise billing',
    plainEnglish: 'Read and change billing settings for the enterprise account.',
    risk: 'high',
    riskWhy: 'Billing changes have direct financial effect.',
  },
  {
    pattern: 'read:enterprise',
    provider: 'GitHub',
    label: 'Read enterprise data',
    plainEnglish: 'Read profile data and settings for the enterprise account.',
    risk: 'moderate',
    riskWhy: 'Reveals the shape of the whole enterprise.',
  },

  // ---------------------------------------------------------------- Slack
  {
    pattern: 'channels:read',
    provider: 'Slack',
    label: 'List public channels',
    plainEnglish: 'List public channels in the workspace and see their basic information.',
    risk: 'low',
    riskWhy: 'Channel names and membership, no message content.',
  },
  {
    pattern: 'channels:history',
    provider: 'Slack',
    label: 'Read public channel history',
    plainEnglish: 'Read the full message history of public channels the app is in.',
    risk: 'high',
    riskWhy: 'Public channels routinely carry internal detail and pasted credentials.',
  },
  {
    pattern: 'channels:join',
    provider: 'Slack',
    label: 'Join public channels',
    plainEnglish: 'Join public channels in the workspace.',
    risk: 'low',
    riskWhy: 'Joining is visible to everyone in the channel.',
  },
  {
    pattern: 'channels:manage',
    provider: 'Slack',
    label: 'Manage public channels',
    plainEnglish: 'Create, rename, archive and set the topic of public channels.',
    risk: 'high',
    riskWhy: 'Archiving a channel removes it from everyday use for everyone.',
  },
  {
    pattern: 'groups:read',
    provider: 'Slack',
    label: 'List private channels',
    plainEnglish: 'List the private channels the app has been added to.',
    risk: 'moderate',
    riskWhy: 'Private channel names alone can be sensitive.',
  },
  {
    pattern: 'groups:history',
    provider: 'Slack',
    label: 'Read private channel history',
    plainEnglish: 'Read the message history of private channels the app has been added to.',
    risk: 'high',
    riskWhy: 'Private channels are where the sensitive conversations happen.',
  },
  {
    pattern: 'im:read',
    provider: 'Slack',
    label: 'List direct messages',
    plainEnglish: 'List the direct message conversations the app can see.',
    risk: 'moderate',
    riskWhy: 'Reveals who talks to whom privately.',
  },
  {
    pattern: 'im:history',
    provider: 'Slack',
    label: 'Read direct messages',
    plainEnglish: 'Read the history of direct message conversations the app can see.',
    risk: 'high',
    riskWhy: 'One to one messages are the most private content in Slack.',
  },
  {
    pattern: 'mpim:read',
    provider: 'Slack',
    label: 'List group DMs',
    plainEnglish: 'List the group direct messages the app can see.',
    risk: 'moderate',
    riskWhy: 'Reveals private conversation groupings.',
  },
  {
    pattern: 'mpim:history',
    provider: 'Slack',
    label: 'Read group DMs',
    plainEnglish: 'Read the history of group direct messages the app can see.',
    risk: 'high',
    riskWhy: 'Private multi person conversations are fully readable.',
  },
  {
    pattern: 'chat:write',
    provider: 'Slack',
    label: 'Post messages',
    plainEnglish: 'Send messages into conversations the app is a member of.',
    risk: 'moderate',
    riskWhy: 'Messages appear inside your workspace as a trusted source.',
  },
  {
    pattern: 'chat:write.public',
    provider: 'Slack',
    label: 'Post to any public channel',
    plainEnglish: 'Send messages to public channels the app has not joined.',
    risk: 'moderate',
    riskWhy: 'No membership needed, so posting is unbounded across public channels.',
  },
  {
    pattern: 'chat:write.customize',
    provider: 'Slack',
    label: 'Post with a custom identity',
    plainEnglish: 'Send messages with a chosen display name and avatar.',
    risk: 'moderate',
    riskWhy: 'A custom identity can make an automated message look like a colleague.',
  },
  {
    pattern: 'users:read',
    provider: 'Slack',
    label: 'Read the member list',
    plainEnglish: 'Read the list of people in the workspace and their basic profiles.',
    risk: 'low',
    riskWhy: 'Directory information only.',
  },
  {
    pattern: 'users:read.email',
    provider: 'Slack',
    label: 'Read member emails',
    plainEnglish: 'Read the email address of every member of the workspace.',
    risk: 'moderate',
    riskWhy: 'A full staff email list is what phishing campaigns start from.',
  },
  {
    pattern: 'users.profile:read',
    provider: 'Slack',
    label: 'Read profiles',
    plainEnglish: 'Read the detailed profile fields of workspace members.',
    risk: 'low',
    riskWhy: 'Profile fields only.',
  },
  {
    pattern: 'users.profile:write',
    provider: 'Slack',
    label: 'Change your profile',
    plainEnglish: 'Change your own Slack profile, including name, photo and status.',
    risk: 'moderate',
    riskWhy: 'How you appear to colleagues can be rewritten.',
  },
  {
    pattern: 'files:read',
    provider: 'Slack',
    label: 'Read files',
    plainEnglish: 'Read and download files shared in conversations the app can see.',
    risk: 'high',
    riskWhy: 'Shared files include contracts, exports and screenshots.',
  },
  {
    pattern: 'files:write',
    provider: 'Slack',
    label: 'Upload files',
    plainEnglish: 'Upload, edit and delete files in conversations the app can see.',
    risk: 'moderate',
    riskWhy: 'Includes deleting files other people uploaded.',
  },
  {
    pattern: 'search:read',
    provider: 'Slack',
    label: 'Search the workspace',
    plainEnglish: 'Search all messages and files your account can see.',
    risk: 'high',
    riskWhy: 'Search reaches everything you can read, in one query.',
  },
  {
    pattern: 'reactions:read',
    provider: 'Slack',
    label: 'Read reactions',
    plainEnglish: 'See the emoji reactions on messages.',
    risk: 'low',
    riskWhy: 'Reaction metadata only.',
  },
  {
    pattern: 'reactions:write',
    provider: 'Slack',
    label: 'Add reactions',
    plainEnglish: 'Add and remove emoji reactions on messages.',
    risk: 'low',
    riskWhy: 'Low impact interaction.',
  },
  {
    pattern: 'pins:read',
    provider: 'Slack',
    label: 'Read pinned items',
    plainEnglish: 'See which messages and files are pinned in a conversation.',
    risk: 'low',
    riskWhy: 'Pin metadata only.',
  },
  {
    pattern: 'pins:write',
    provider: 'Slack',
    label: 'Pin items',
    plainEnglish: 'Pin and unpin messages and files in a conversation.',
    risk: 'low',
    riskWhy: 'Low impact interaction.',
  },
  {
    pattern: 'emoji:read',
    provider: 'Slack',
    label: 'Read custom emoji',
    plainEnglish: 'Read the custom emoji defined in the workspace.',
    risk: 'low',
    riskWhy: 'Emoji list only.',
  },
  {
    pattern: 'team:read',
    provider: 'Slack',
    label: 'Read workspace info',
    plainEnglish: 'Read the name, domain and settings of the workspace.',
    risk: 'low',
    riskWhy: 'Workspace level metadata only.',
  },
  {
    pattern: 'commands',
    provider: 'Slack',
    label: 'Slash commands',
    plainEnglish: 'Add slash commands that people can run in the workspace.',
    risk: 'low',
    riskWhy: 'The app only receives what someone types at it.',
  },
  {
    pattern: 'incoming-webhook',
    provider: 'Slack',
    label: 'Post via webhook',
    plainEnglish: 'Post messages to one channel you choose during install.',
    risk: 'low',
    riskWhy: 'Write only, into a single channel you pick.',
  },
  {
    pattern: 'admin',
    provider: 'Slack',
    label: 'Workspace administration',
    plainEnglish: 'Administer the workspace as you, across users, channels and settings.',
    risk: 'critical',
    riskWhy: 'The broadest Slack scope, equivalent to your admin rights.',
  },
  {
    pattern: 'admin.users:read',
    provider: 'Slack',
    label: 'Read all accounts',
    plainEnglish: 'Read every user account in the workspace or organization.',
    risk: 'high',
    riskWhy: 'Full account inventory including guests and admins.',
  },
  {
    pattern: 'admin.users:write',
    provider: 'Slack',
    label: 'Manage all accounts',
    plainEnglish: 'Invite, deactivate and change any user account in the workspace.',
    risk: 'critical',
    riskWhy: 'Account control over everyone, not only you.',
  },
  {
    pattern: 'admin.conversations:read',
    provider: 'Slack',
    label: 'Read all conversations metadata',
    plainEnglish: 'Read information about every channel in the organization.',
    risk: 'high',
    riskWhy: 'Covers private channels the app was never invited to.',
  },
  {
    pattern: 'admin.conversations:write',
    provider: 'Slack',
    label: 'Manage all conversations',
    plainEnglish: 'Create, archive, convert and change any channel in the organization.',
    risk: 'critical',
    riskWhy: 'Can convert a private channel to public.',
  },

  // ---------------------------------------------------------------- Discord
  {
    pattern: 'identify',
    provider: 'Discord',
    label: 'Basic account info',
    plainEnglish: 'See your username, avatar, discriminator and user id.',
    risk: 'low',
    riskWhy: 'Public profile data only, no email.',
  },
  {
    pattern: 'connections',
    provider: 'Discord',
    label: 'Linked accounts',
    plainEnglish: 'See the third party accounts linked to your Discord profile.',
    risk: 'moderate',
    riskWhy: 'Links your Discord identity to your accounts elsewhere.',
  },
  {
    pattern: 'guilds',
    provider: 'Discord',
    label: 'Server list',
    plainEnglish: 'See the list of servers you are a member of.',
    risk: 'low',
    riskWhy: 'Server names only, no message content.',
  },
  {
    pattern: 'guilds.join',
    provider: 'Discord',
    label: 'Join servers for you',
    plainEnglish: 'Add your account to a Discord server without asking again.',
    risk: 'moderate',
    riskWhy: 'You can end up in servers you did not choose.',
  },
  {
    pattern: 'guilds.members.read',
    provider: 'Discord',
    label: 'Read your server membership',
    plainEnglish: 'Read your nickname, roles and join date in servers you are in.',
    risk: 'moderate',
    riskWhy: 'Roles reveal what you can do in each server.',
  },
  {
    pattern: 'bot',
    provider: 'Discord',
    label: 'Add a bot',
    plainEnglish: 'Add the application bot to a server with the permissions shown at install.',
    risk: 'high',
    riskWhy: 'The real power comes from the permissions bitfield next to this scope.',
  },
  {
    pattern: 'webhook.incoming',
    provider: 'Discord',
    label: 'Create a webhook',
    plainEnglish: 'Create a webhook that can post messages to a channel you choose.',
    risk: 'moderate',
    riskWhy: 'A webhook URL can post to that channel forever unless deleted.',
  },
  {
    pattern: 'messages.read',
    provider: 'Discord',
    label: 'Read messages locally',
    plainEnglish: 'Read messages in your local Discord client through the RPC interface.',
    risk: 'high',
    riskWhy: 'This reads real message content, and is restricted to approved apps.',
  },
  {
    pattern: 'rpc',
    provider: 'Discord',
    label: 'Control the local client',
    plainEnglish: 'Control your local Discord client, such as voice settings and activity.',
    risk: 'moderate',
    riskWhy: 'Local client control, restricted to approved apps.',
  },
  {
    pattern: 'applications.commands',
    provider: 'Discord',
    label: 'Add slash commands',
    plainEnglish: 'Add application commands to a server.',
    risk: 'low',
    riskWhy: 'The app only receives explicit command invocations.',
  },

  // ---------------------------------------------------------------- Shopify
  {
    pattern: 'read_products',
    provider: 'Shopify',
    label: 'Read products',
    plainEnglish: 'Read products, variants, collections and their inventory information.',
    risk: 'low',
    riskWhy: 'Catalog data, most of which is already public on the storefront.',
  },
  {
    pattern: 'write_products',
    provider: 'Shopify',
    label: 'Manage products',
    plainEnglish: 'Create, change and delete products, variants and collections.',
    risk: 'moderate',
    riskWhy: 'Product and price changes are visible to shoppers immediately.',
  },
  {
    pattern: 'read_orders',
    provider: 'Shopify',
    label: 'Read recent orders',
    plainEnglish: 'Read orders from the last 60 days, including customer and shipping details.',
    risk: 'high',
    riskWhy: 'Orders contain names, addresses and purchase history.',
  },
  {
    pattern: 'write_orders',
    provider: 'Shopify',
    label: 'Manage orders',
    plainEnglish: 'Create, change and cancel orders in the store.',
    risk: 'high',
    riskWhy: 'Order changes affect fulfilment and money.',
  },
  {
    pattern: 'read_all_orders',
    provider: 'Shopify',
    label: 'Read full order history',
    plainEnglish: 'Read the entire order history of the store, not just the last 60 days.',
    risk: 'high',
    riskWhy: 'The complete customer purchase record in one place.',
  },
  {
    pattern: 'read_customers',
    provider: 'Shopify',
    label: 'Read customers',
    plainEnglish: 'Read customer records, including names, emails, phone numbers and addresses.',
    risk: 'high',
    riskWhy: 'This is the store personal data list.',
  },
  {
    pattern: 'write_customers',
    provider: 'Shopify',
    label: 'Manage customers',
    plainEnglish: 'Create, change and delete customer records.',
    risk: 'high',
    riskWhy: 'Customer records can be altered or removed.',
  },
  {
    pattern: 'read_inventory',
    provider: 'Shopify',
    label: 'Read inventory',
    plainEnglish: 'Read stock levels and inventory locations.',
    risk: 'low',
    riskWhy: 'Operational data with limited personal content.',
  },
  {
    pattern: 'write_inventory',
    provider: 'Shopify',
    label: 'Manage inventory',
    plainEnglish: 'Change stock levels and inventory locations.',
    risk: 'moderate',
    riskWhy: 'Wrong stock levels can oversell or hide products.',
  },
  {
    pattern: 'read_fulfillments',
    provider: 'Shopify',
    label: 'Read fulfillments',
    plainEnglish: 'Read fulfillment records and shipment tracking.',
    risk: 'moderate',
    riskWhy: 'Includes shipping destinations.',
  },
  {
    pattern: 'write_fulfillments',
    provider: 'Shopify',
    label: 'Manage fulfillments',
    plainEnglish: 'Create and change fulfillments and tracking information.',
    risk: 'moderate',
    riskWhy: 'Fulfillment changes trigger customer notifications.',
  },
  {
    pattern: 'read_draft_orders',
    provider: 'Shopify',
    label: 'Read draft orders',
    plainEnglish: 'Read draft orders and their customer details.',
    risk: 'moderate',
    riskWhy: 'Drafts carry the same customer data as orders.',
  },
  {
    pattern: 'write_draft_orders',
    provider: 'Shopify',
    label: 'Manage draft orders',
    plainEnglish: 'Create, change and delete draft orders and send their invoices.',
    risk: 'high',
    riskWhy: 'Draft order invoices go out to real customers.',
  },
  {
    pattern: 'read_content',
    provider: 'Shopify',
    label: 'Read store content',
    plainEnglish: 'Read pages, blog posts, comments and other store content.',
    risk: 'low',
    riskWhy: 'Mostly published storefront content.',
  },
  {
    pattern: 'write_content',
    provider: 'Shopify',
    label: 'Manage store content',
    plainEnglish: 'Create, change and delete pages, blog posts and comments.',
    risk: 'moderate',
    riskWhy: 'Published content changes are visible to shoppers.',
  },
  {
    pattern: 'read_themes',
    provider: 'Shopify',
    label: 'Read themes',
    plainEnglish: 'Read the theme files and assets of the storefront.',
    risk: 'moderate',
    riskWhy: 'Theme files can contain keys developers left in place.',
  },
  {
    pattern: 'write_themes',
    provider: 'Shopify',
    label: 'Manage themes',
    plainEnglish: 'Create, change and delete theme files and assets.',
    risk: 'critical',
    riskWhy: 'Theme files run on the checkout facing storefront, so they can skim payments.',
  },
  {
    pattern: 'read_price_rules',
    provider: 'Shopify',
    label: 'Read price rules',
    plainEnglish: 'Read the discount price rules configured for the store.',
    risk: 'low',
    riskWhy: 'Pricing configuration only.',
  },
  {
    pattern: 'write_discounts',
    provider: 'Shopify',
    label: 'Manage discounts',
    plainEnglish: 'Create, change and delete discount codes and automatic discounts.',
    risk: 'high',
    riskWhy: 'Discount codes are a direct route to giving away revenue.',
  },
  {
    pattern: 'read_analytics',
    provider: 'Shopify',
    label: 'Read analytics',
    plainEnglish: 'Read store analytics and sales reports.',
    risk: 'moderate',
    riskWhy: 'Revenue figures are commercially sensitive.',
  },
  {
    pattern: 'read_shipping',
    provider: 'Shopify',
    label: 'Read shipping settings',
    plainEnglish: 'Read shipping zones, rates and carrier settings.',
    risk: 'low',
    riskWhy: 'Configuration only.',
  },
  {
    pattern: 'write_shipping',
    provider: 'Shopify',
    label: 'Manage shipping settings',
    plainEnglish: 'Create and change shipping zones, rates and carrier settings.',
    risk: 'moderate',
    riskWhy: 'Shipping rate changes affect what every customer pays.',
  },

  // ---------------------------------------------------------------- Stripe
  {
    pattern: 'read_write',
    provider: 'Stripe',
    label: 'Full account access',
    plainEnglish:
      'Read and write on the connected Stripe account, including charges, refunds and payouts.',
    risk: 'critical',
    riskWhy: 'This is money movement on a live payments account.',
  },
  {
    pattern: 'read_only',
    provider: 'Stripe',
    label: 'Read only access',
    plainEnglish: 'Read data on the connected Stripe account, including customers and charges.',
    risk: 'high',
    riskWhy: 'Payment records are financial and personal data even without write access.',
  },

  // ---------------------------------------------------------------- Zoom
  {
    pattern: 'user:read',
    provider: 'Zoom',
    label: 'Read your Zoom profile',
    plainEnglish: 'Read your own Zoom user profile and settings.',
    risk: 'low',
    riskWhy: 'Your own profile only.',
  },
  {
    pattern: 'user:write',
    provider: 'Zoom',
    label: 'Change your Zoom profile',
    plainEnglish: 'Read and change your own Zoom user profile and settings.',
    risk: 'moderate',
    riskWhy: 'Meeting security defaults live in these settings.',
  },
  {
    pattern: 'user:read:admin',
    provider: 'Zoom',
    label: 'Read all Zoom users',
    plainEnglish: 'Read every user in the Zoom account.',
    risk: 'high',
    riskWhy: 'The admin suffix means the whole account, not just you.',
  },
  {
    pattern: 'user:write:admin',
    provider: 'Zoom',
    label: 'Manage all Zoom users',
    plainEnglish: 'Create, change and delete any user in the Zoom account.',
    risk: 'critical',
    riskWhy: 'Account wide user control.',
  },
  {
    pattern: 'meeting:read',
    provider: 'Zoom',
    label: 'Read your meetings',
    plainEnglish: 'Read your meetings, including join links and passcodes.',
    risk: 'moderate',
    riskWhy: 'A join link plus passcode is enough to enter the meeting.',
  },
  {
    pattern: 'meeting:write',
    provider: 'Zoom',
    label: 'Manage your meetings',
    plainEnglish: 'Create, change and delete your Zoom meetings.',
    risk: 'moderate',
    riskWhy: 'Meetings can be created or cancelled in your name.',
  },
  {
    pattern: 'meeting:read:admin',
    provider: 'Zoom',
    label: 'Read all meetings',
    plainEnglish: 'Read the meetings of every user in the Zoom account.',
    risk: 'high',
    riskWhy: 'Covers meetings belonging to colleagues.',
  },
  {
    pattern: 'meeting:write:admin',
    provider: 'Zoom',
    label: 'Manage all meetings',
    plainEnglish: 'Create, change and delete meetings for any user in the Zoom account.',
    risk: 'critical',
    riskWhy: 'Account wide control over meetings.',
  },
  {
    pattern: 'recording:read',
    provider: 'Zoom',
    label: 'Read your recordings',
    plainEnglish: 'Read and download your cloud recordings and their transcripts.',
    risk: 'high',
    riskWhy: 'Recordings are complete transcripts of private conversations.',
  },
  {
    pattern: 'recording:write',
    provider: 'Zoom',
    label: 'Manage your recordings',
    plainEnglish: 'Change, share and delete your cloud recordings.',
    risk: 'high',
    riskWhy: 'Recordings can be shared out or destroyed.',
  },
  {
    pattern: 'webinar:read',
    provider: 'Zoom',
    label: 'Read your webinars',
    plainEnglish: 'Read your webinars, including registrant lists.',
    risk: 'moderate',
    riskWhy: 'Registrant lists contain attendee personal data.',
  },
  {
    pattern: 'webinar:write',
    provider: 'Zoom',
    label: 'Manage your webinars',
    plainEnglish: 'Create, change and delete your webinars and their registrants.',
    risk: 'moderate',
    riskWhy: 'Registration changes reach real attendees.',
  },
  {
    pattern: 'account:read:admin',
    provider: 'Zoom',
    label: 'Read account settings',
    plainEnglish: 'Read the settings of the whole Zoom account.',
    risk: 'moderate',
    riskWhy: 'Reveals which security settings are enforced.',
  },

  // ---------------------------------------------------------------- Dropbox
  {
    pattern: 'account_info.read',
    provider: 'Dropbox',
    label: 'Read account info',
    plainEnglish: 'Read your Dropbox account information, such as name and email.',
    risk: 'low',
    riskWhy: 'Profile data only.',
  },
  {
    pattern: 'account_info.write',
    provider: 'Dropbox',
    label: 'Change account info',
    plainEnglish: 'Change your Dropbox account information and settings.',
    risk: 'moderate',
    riskWhy: 'Account settings can be altered.',
  },
  {
    pattern: 'files.metadata.read',
    provider: 'Dropbox',
    label: 'List files',
    plainEnglish: 'List the names, sizes and paths of your files without reading their contents.',
    risk: 'low',
    riskWhy: 'File names still hint at their content, but nothing is downloaded.',
  },
  {
    pattern: 'files.metadata.write',
    provider: 'Dropbox',
    label: 'Move and rename files',
    plainEnglish: 'Rename, move and delete your files without reading their contents.',
    risk: 'moderate',
    riskWhy: 'Deletion is possible without ever reading a file.',
  },
  {
    pattern: 'files.content.read',
    provider: 'Dropbox',
    label: 'Download files',
    plainEnglish: 'Download the contents of every file in your Dropbox.',
    risk: 'high',
    riskWhy: 'Full read of a personal or company file store.',
  },
  {
    pattern: 'files.content.write',
    provider: 'Dropbox',
    label: 'Upload and overwrite files',
    plainEnglish: 'Upload, overwrite and delete the contents of files in your Dropbox.',
    risk: 'high',
    riskWhy: 'Overwriting is as damaging as deleting.',
  },
  {
    pattern: 'sharing.read',
    provider: 'Dropbox',
    label: 'Read sharing settings',
    plainEnglish: 'Read the shared links and shared folder settings on your account.',
    risk: 'moderate',
    riskWhy: 'Shared links may work for anyone who has them.',
  },
  {
    pattern: 'sharing.write',
    provider: 'Dropbox',
    label: 'Manage sharing',
    plainEnglish: 'Create and change shared links and shared folder membership.',
    risk: 'high',
    riskWhy: 'A new public link exposes a file to anyone with the URL.',
  },
  {
    pattern: 'file_requests.read',
    provider: 'Dropbox',
    label: 'Read file requests',
    plainEnglish: 'Read the file requests you have created.',
    risk: 'low',
    riskWhy: 'Request metadata only.',
  },
  {
    pattern: 'file_requests.write',
    provider: 'Dropbox',
    label: 'Manage file requests',
    plainEnglish: 'Create, change and close file requests on your account.',
    risk: 'moderate',
    riskWhy: 'File requests collect uploads from other people.',
  },
  {
    pattern: 'contacts.read',
    provider: 'Dropbox',
    label: 'Read Dropbox contacts',
    plainEnglish: 'Read the contacts stored on your Dropbox account.',
    risk: 'moderate',
    riskWhy: 'Contact data about other people.',
  },
  {
    pattern: 'contacts.write',
    provider: 'Dropbox',
    label: 'Manage Dropbox contacts',
    plainEnglish: 'Add and delete contacts on your Dropbox account.',
    risk: 'moderate',
    riskWhy: 'Contact records can be altered.',
  },

  // ---------------------------------------------------------------- Spotify
  {
    pattern: 'user-read-email',
    provider: 'Spotify',
    label: 'Read your email',
    plainEnglish: 'See the email address on your Spotify account.',
    risk: 'low',
    riskWhy: 'One identifier.',
  },
  {
    pattern: 'user-read-private',
    provider: 'Spotify',
    label: 'Read your subscription',
    plainEnglish: 'See your subscription level, country and explicit content setting.',
    risk: 'low',
    riskWhy: 'Account attributes only.',
  },
  {
    pattern: 'playlist-read-private',
    provider: 'Spotify',
    label: 'Read private playlists',
    plainEnglish: 'Read your private playlists as well as public ones.',
    risk: 'low',
    riskWhy: 'Listening data, sensitive mainly as personal taste.',
  },
  {
    pattern: 'playlist-read-collaborative',
    provider: 'Spotify',
    label: 'Read collaborative playlists',
    plainEnglish: 'Read the collaborative playlists you take part in.',
    risk: 'low',
    riskWhy: 'Shared listening data.',
  },
  {
    pattern: 'playlist-modify-public',
    provider: 'Spotify',
    label: 'Change public playlists',
    plainEnglish: 'Create and change your public playlists.',
    risk: 'moderate',
    riskWhy: 'Public playlists carry your name.',
  },
  {
    pattern: 'playlist-modify-private',
    provider: 'Spotify',
    label: 'Change private playlists',
    plainEnglish: 'Create and change your private playlists.',
    risk: 'moderate',
    riskWhy: 'Playlists can be edited or emptied.',
  },
  {
    pattern: 'user-library-read',
    provider: 'Spotify',
    label: 'Read your library',
    plainEnglish: 'Read the tracks, albums and shows saved in your library.',
    risk: 'low',
    riskWhy: 'Listening data only.',
  },
  {
    pattern: 'user-library-modify',
    provider: 'Spotify',
    label: 'Change your library',
    plainEnglish: 'Save and remove tracks, albums and shows in your library.',
    risk: 'moderate',
    riskWhy: 'Saved items can be removed.',
  },
  {
    pattern: 'user-top-read',
    provider: 'Spotify',
    label: 'Read your top items',
    plainEnglish: 'See your most played artists and tracks.',
    risk: 'low',
    riskWhy: 'Aggregated listening history.',
  },
  {
    pattern: 'user-read-playback-state',
    provider: 'Spotify',
    label: 'Read playback state',
    plainEnglish: 'See what is playing right now and on which device.',
    risk: 'low',
    riskWhy: 'Reveals device presence and activity times.',
  },
  {
    pattern: 'user-modify-playback-state',
    provider: 'Spotify',
    label: 'Control playback',
    plainEnglish: 'Start, pause, skip and change volume on your devices.',
    risk: 'low',
    riskWhy: 'Playback control only.',
  },
  {
    pattern: 'streaming',
    provider: 'Spotify',
    label: 'Play audio',
    plainEnglish: 'Play Spotify audio in the app, which requires a Premium account.',
    risk: 'low',
    riskWhy: 'Playback only.',
  },

  // ---------------------------------------------------------------- Atlassian
  {
    pattern: 'read:me',
    provider: 'Atlassian',
    label: 'Read your profile',
    plainEnglish: 'Read your Atlassian account profile.',
    risk: 'low',
    riskWhy: 'Profile data only.',
  },
  {
    pattern: 'read:jira-user',
    provider: 'Atlassian',
    label: 'Read Jira users',
    plainEnglish: 'Read the user records and groups in the Jira site.',
    risk: 'moderate',
    riskWhy: 'A staff list for the whole site.',
  },
  {
    pattern: 'read:jira-work',
    provider: 'Atlassian',
    label: 'Read Jira issues',
    plainEnglish: 'Read projects, issues, comments and attachments in Jira.',
    risk: 'high',
    riskWhy: 'Issue trackers hold unreleased plans and security tickets.',
  },
  {
    pattern: 'write:jira-work',
    provider: 'Atlassian',
    label: 'Change Jira issues',
    plainEnglish: 'Create, change, transition and delete Jira issues and comments.',
    risk: 'high',
    riskWhy: 'Write access on the record of what your team is doing.',
  },
  {
    pattern: 'manage:jira-project',
    provider: 'Atlassian',
    label: 'Manage Jira projects',
    plainEnglish: 'Create and change Jira projects, versions and their configuration.',
    risk: 'critical',
    riskWhy: 'Project configuration decides who can see which issues.',
  },
  {
    pattern: 'manage:jira-configuration',
    provider: 'Atlassian',
    label: 'Manage Jira settings',
    plainEnglish: 'Change site wide Jira configuration and administrative settings.',
    risk: 'critical',
    riskWhy: 'Site administration for the whole Jira instance.',
  },
  {
    pattern: 'read:confluence-content.all',
    provider: 'Atlassian',
    label: 'Read Confluence content',
    plainEnglish: 'Read all Confluence pages, blogs, comments and attachments you can access.',
    risk: 'high',
    riskWhy: 'Wikis are where internal documentation and runbooks live.',
  },
  {
    pattern: 'write:confluence-content',
    provider: 'Atlassian',
    label: 'Change Confluence content',
    plainEnglish: 'Create, change and delete Confluence pages and blog posts.',
    risk: 'high',
    riskWhy: 'Documentation can be rewritten or removed.',
  },

  // ---------------------------------------------------------------- Salesforce
  {
    pattern: 'api',
    provider: 'Salesforce',
    label: 'API access',
    plainEnglish: 'Access Salesforce data and APIs with the same rights your user has.',
    risk: 'high',
    riskWhy: 'CRM records are customer personal data and pipeline value.',
  },
  {
    pattern: 'full',
    provider: 'Salesforce',
    label: 'Full access',
    plainEnglish: 'Access everything your Salesforce user can, across all data and features.',
    risk: 'critical',
    riskWhy: 'The widest Salesforce scope, matching your own permissions exactly.',
  },
  {
    pattern: 'refresh_token',
    provider: 'Salesforce',
    label: 'Refresh token',
    plainEnglish: 'Receive a refresh token so access continues after you close the app.',
    risk: 'moderate',
    riskWhy: 'Access persists while you are away until you revoke it.',
  },
  {
    pattern: 'web',
    provider: 'Salesforce',
    label: 'Web session access',
    plainEnglish: 'Open a Salesforce web session on your behalf using the issued token.',
    risk: 'high',
    riskWhy: 'A web session behaves as if you had logged in yourself.',
  },

  // ---------------------------------------------------------------- X (Twitter)
  {
    pattern: 'tweet.read',
    provider: 'X (Twitter)',
    label: 'Read posts',
    plainEnglish: 'Read posts and timelines that your account can see.',
    risk: 'low',
    riskWhy: 'Mostly public content.',
  },
  {
    pattern: 'tweet.write',
    provider: 'X (Twitter)',
    label: 'Post and delete',
    plainEnglish: 'Create and delete posts as your account.',
    risk: 'high',
    riskWhy: 'Anything posted is published under your name to your followers.',
  },
  {
    pattern: 'users.read',
    provider: 'X (Twitter)',
    label: 'Read profiles',
    plainEnglish: 'Read your profile and the profiles of other accounts.',
    risk: 'low',
    riskWhy: 'Public profile data.',
  },
  {
    pattern: 'follows.read',
    provider: 'X (Twitter)',
    label: 'Read follows',
    plainEnglish: 'Read who you follow and who follows you.',
    risk: 'low',
    riskWhy: 'Public social graph.',
  },
  {
    pattern: 'follows.write',
    provider: 'X (Twitter)',
    label: 'Follow and unfollow',
    plainEnglish: 'Follow and unfollow accounts as you.',
    risk: 'moderate',
    riskWhy: 'Follows are public endorsements made in your name.',
  },
  {
    pattern: 'like.read',
    provider: 'X (Twitter)',
    label: 'Read likes',
    plainEnglish: 'Read the posts you have liked.',
    risk: 'low',
    riskWhy: 'Public interaction data.',
  },
  {
    pattern: 'like.write',
    provider: 'X (Twitter)',
    label: 'Like and unlike',
    plainEnglish: 'Like and unlike posts as you.',
    risk: 'moderate',
    riskWhy: 'Likes are public and attributed to you.',
  },
  {
    pattern: 'dm.read',
    provider: 'X (Twitter)',
    label: 'Read direct messages',
    plainEnglish: 'Read your direct message conversations.',
    risk: 'high',
    riskWhy: 'Direct messages are private correspondence.',
  },
  {
    pattern: 'dm.write',
    provider: 'X (Twitter)',
    label: 'Send direct messages',
    plainEnglish: 'Send direct messages from your account.',
    risk: 'high',
    riskWhy: 'Messages arrive as if you personally sent them.',
  },
  {
    pattern: 'offline.access',
    provider: 'X (Twitter)',
    label: 'Refresh token',
    plainEnglish: 'Keep the granted access after you close the app, using a refresh token.',
    risk: 'moderate',
    riskWhy: 'Access continues while you are away until you revoke it.',
  },

  // ---------------------------------------------------------------- LinkedIn
  {
    pattern: 'r_liteprofile',
    provider: 'LinkedIn',
    label: 'Read basic profile',
    plainEnglish: 'Read your name, headline and profile picture.',
    risk: 'low',
    riskWhy: 'Public profile fields only.',
  },
  {
    pattern: 'r_emailaddress',
    provider: 'LinkedIn',
    label: 'Read your email',
    plainEnglish: 'See the primary email address on your LinkedIn account.',
    risk: 'low',
    riskWhy: 'One identifier.',
  },
  {
    pattern: 'w_member_social',
    provider: 'LinkedIn',
    label: 'Post as you',
    plainEnglish: 'Create, change and delete posts, comments and reactions as you.',
    risk: 'high',
    riskWhy: 'Posts are published to your professional network under your name.',
  },
];

/** Fast exact lookup, built once at module load. */
export const BY_PATTERN: ReadonlyMap<string, ScopeEntry> = new Map(
  SCOPES.filter((s) => !s.pattern.endsWith('*')).map((s) => [s.pattern, s]),
);

/** Same lookup, lowercased, for providers whose docs vary in case (Microsoft Graph). */
export const BY_PATTERN_LOWER: ReadonlyMap<string, ScopeEntry> = new Map(
  SCOPES.filter((s) => !s.pattern.endsWith('*')).map((s) => [s.pattern.toLowerCase(), s]),
);

/** Prefix patterns, longest first so the most specific one wins. */
export const PREFIXES: readonly ScopeEntry[] = SCOPES.filter((s) => s.pattern.endsWith('*')).slice()
  .sort((a, b) => b.pattern.length - a.pattern.length);
