/**
 * "Is this tool new?", answered from the checked-in snapshot in
 * src/tools/added-dates.ts (generated by scripts/tool-added-dates.mjs).
 *
 * Pure: `now` is always passed in, never read from the clock here, so the tests
 * do not have to fake time and a caller can render the same answer on the
 * server and on the client.
 *
 * A date the map does not have, or one that does not parse, is not new. That is
 * the right answer for a tool that has not been committed yet, and it means a
 * stale snapshot degrades to no badge rather than to a wrong one.
 *
 * The count cap exists because this site shipped in batches: on the day it was
 * written, every tool in the registry was under 30 days old, so a bare 30 day
 * rule would have put a "New" badge on all 187 cards, which says nothing at
 * all. `newBadgeSlugs` is what the surfaces call, and it badges the newest
 * tools only, up to NEW_BADGE_MAX of them.
 *
 * The cap counts whole days, never part of one. Tools that landed together were
 * announced together, so splitting a day's batch across the cap would make the
 * badge look arbitrary to the one person who would notice. The newest day is
 * always badged in full, even when it alone is over the cap.
 */

import { ADDED_DATES } from "@/tools/added-dates";

/** How recently a tool has to have landed to count as new. */
export const NEW_TOOL_DAYS = 30;

/** Roughly how many cards may wear the badge. Whole days round this up. */
export const NEW_BADGE_MAX = 12;

const DAY_MS = 86_400_000;

/** The stored `YYYY-MM-DD` for `slug`, or undefined when it has none. */
export function addedDate(
  slug: string,
  dates: Record<string, string> = ADDED_DATES,
): string | undefined {
  return dates[slug];
}

/**
 * True when `slug` landed within the last `days` days of `now`.
 * `now` may be a Date or an epoch milliseconds number.
 */
export function isNewTool(
  slug: string,
  now: Date | number,
  days = NEW_TOOL_DAYS,
  dates: Record<string, string> = ADDED_DATES,
): boolean {
  if (days <= 0) return false;
  const raw = dates[slug];
  if (!raw) return false;
  const added = Date.parse(raw);
  if (Number.isNaN(added)) return false;
  const at = typeof now === "number" ? now : now.getTime();
  if (Number.isNaN(at)) return false;
  const age = at - added;
  // A date in the future is a bad snapshot, not a brand new tool.
  return age >= 0 && age < days * DAY_MS;
}

/**
 * Which of `slugs` should actually wear a "New" badge: the newest ones inside
 * the window, taken a whole day at a time until the next day would push the
 * total past `max`. The newest day always makes it in.
 */
export function newBadgeSlugs(
  slugs: readonly string[],
  now: Date | number,
  days = NEW_TOOL_DAYS,
  dates: Record<string, string> = ADDED_DATES,
  max = NEW_BADGE_MAX,
): Set<string> {
  const out = new Set<string>();
  if (max <= 0) return out;

  // Group the fresh slugs by the day they landed.
  const byDay = new Map<string, string[]>();
  for (const slug of slugs) {
    if (!isNewTool(slug, now, days, dates)) continue;
    const day = dates[slug];
    const bucket = byDay.get(day);
    if (bucket) bucket.push(slug);
    else byDay.set(day, [slug]);
  }

  // Newest day first, and stop before the day that would overflow the cap.
  for (const day of [...byDay.keys()].sort().reverse()) {
    const bucket = byDay.get(day) ?? [];
    if (out.size > 0 && out.size + bucket.length > max) break;
    for (const slug of bucket) out.add(slug);
    if (out.size >= max) break;
  }
  return out;
}
