import { describe, expect, it } from "vitest";
import {
  filamentWeight,
  formatDuration,
  layerStats,
  parseGcode,
  renderAllLayersSvg,
  renderLayerSvg,
  run,
  summarize,
} from "./index";
import { ToolError } from "../types";

const OPTS = { svg: false, layer: 0, showTravel: false, colorBy: "type" };

/**
 * Hand written sample: PrusaSlicer style layer markers, two layers, a square
 * on each, a travel move between them, relative extrusion, and a quarter arc.
 */
const SAMPLE = [
  "; hand written sample",
  ";LAYER_COUNT:2",
  "G21",
  "G90",
  "M82",
  "M104 S200",
  "M140 S60",
  "M109 S200",
  "M190 S60",
  "M106 S255",
  "G28",
  "M83",
  "G1 F1200",
  ";LAYER_CHANGE",
  ";Z:0.2",
  "G0 X10 Y10 Z0.2 F3000",
  "G1 X20 Y10 E0.5 F1200",
  "G1 X20 Y20 E0.5",
  "G1 X10 Y20 E0.5",
  "G1 X10 Y10 E0.5",
  ";LAYER_CHANGE",
  ";Z:0.4",
  "G0 Z0.4",
  "G0 X30 Y10 F3000",
  "G1 X40 Y10 E0.5 F1200",
  "G1 X40 Y20 E0.5 F2400",
  "G1 X30 Y20 E0.5 F1200",
  "G1 X30 Y10 E0.5",
  "G2 X40 Y20 I10 J0 E1.5",
  "M107",
].join("\n");

/** Cura writes ";LAYER:n" markers and an absolute extruder. */
const CURA = [
  ";FLAVOR:Marlin",
  ";TIME:120",
  ";Filament used: 1.234m",
  ";Layer height: 0.2",
  ";Generated with Cura_SteamEngine 5.4.0",
  ";LAYER_COUNT:2",
  "M82",
  "G0 F3000 X0 Y0 Z0.2",
  ";LAYER:0",
  "G1 F1200 X10 Y0 E1",
  ";LAYER:1",
  "G0 Z0.4",
  "G1 X10 Y10 E2",
].join("\n");

/** No comments at all, so layers can only come from the Z changes. */
const NO_MARKERS = [
  "G90",
  "M82",
  "G1 F1200 Z0.2",
  "G1 X10 Y0 E1",
  "G1 X10 Y10 E2",
  "G1 Z0.4",
  "G1 X0 Y10 E3",
  "G1 X0 Y0 E4",
].join("\n");

const PRUSA = [
  "; generated by PrusaSlicer 2.6.1+win64 on 2024-01-01 at 12:00:00 UTC",
  ";LAYER_CHANGE",
  ";Z:0.2",
  "G1 F1200 X10 Y10 E1",
  "G1 X20 Y10 E2",
  "; estimated printing time (normal mode) = 1h 5m 30s",
  "; filament used [mm] = 1234.5",
  "; filament used [g] = 3.68",
].join("\n");

function codeOf(fn: () => unknown): string {
  try {
    fn();
  } catch (error) {
    if (error instanceof ToolError) return error.code;
    return `not-a-tool-error: ${String(error)}`;
  }
  return "no-error";
}

describe("parseGcode", () => {
  it("splits the sample into two layers at the right heights", () => {
    const model = parseGcode(SAMPLE);
    expect(model.layers).toHaveLength(2);
    expect(model.layers[0].z).toBe(0.2);
    expect(model.layers[1].z).toBe(0.4);
    expect(model.layerDetection).toBe("marker");
  });

  it("counts the segments on each layer", () => {
    const model = parseGcode(SAMPLE);
    // One travel in, then the four sides of the square.
    expect(model.layers[0].segments).toHaveLength(5);
    expect(model.layers[0].segments.filter((s) => s.extruding)).toHaveLength(4);
    // One travel, four sides, then the twelve pieces of the arc.
    expect(model.layers[1].segments).toHaveLength(17);
    expect(model.layers[1].segments.filter((s) => s.extruding)).toHaveLength(16);
  });

  it("adds up relative extrusion exactly", () => {
    const model = parseGcode(SAMPLE);
    expect(model.totalFilamentMm).toBe(5.5);
    expect(model.layers[0].filamentMm).toBe(2);
    expect(model.layers[1].filamentMm).toBe(3.5);
  });

  it("measures the printed extent, not the machine envelope", () => {
    const model = parseGcode(SAMPLE);
    expect(model.bounds).toEqual({
      minX: 10,
      maxX: 40,
      minY: 10,
      maxY: 20,
      minZ: 0.2,
      maxZ: 0.4,
    });
    expect(model.layers[0].extrudingLength).toBeCloseTo(40, 9);
  });

  it("approximates a G2 arc with its endpoints exact", () => {
    const model = parseGcode(SAMPLE);
    const arc = model.layers[1].segments.slice(5);
    expect(arc.length).toBeGreaterThanOrEqual(8);
    expect(arc).toHaveLength(12);
    expect(arc[0].x1).toBe(30);
    expect(arc[0].y1).toBe(10);
    expect(arc[11].x2).toBe(40);
    expect(arc[11].y2).toBe(20);
    for (const s of arc) {
      expect(Math.hypot(s.x2 - 40, s.y2 - 10)).toBeCloseTo(10, 9);
      expect(s.extruding).toBe(true);
    }
  });

  it("records temperatures, fan, and the total distance", () => {
    const model = parseGcode(SAMPLE);
    expect(model.temps.maxHotend).toBe(200);
    expect(model.temps.maxBed).toBe(60);
    expect(model.fan.maxPercent).toBe(100);
    expect(model.fan.used).toBe(true);
    expect(model.toolChanges).toBe(0);
    // Two squares of 40 mm plus a quarter circle of radius 10.
    expect(model.extrudingDistance).toBeCloseTo(80 + 5 * Math.PI, 1);
    expect(model.estimatedTimeSec).toBeGreaterThan(0);
  });

  it("reads Cura style ;LAYER:n markers and an absolute extruder", () => {
    const model = parseGcode(CURA);
    expect(model.layers).toHaveLength(2);
    expect(model.layers[0].z).toBe(0.2);
    expect(model.layers[1].z).toBe(0.4);
    expect(model.totalFilamentMm).toBe(2);
    expect(model.slicer).toContain("Cura");
    expect(model.printTimeFromSlicer).toBe("2m 0s");
    expect(model.filamentUsedFromSlicer).toBe("1.234 m");
  });

  it("falls back to Z changes when the file has no layer markers", () => {
    const model = parseGcode(NO_MARKERS);
    expect(model.layerDetection).toBe("z-change");
    expect(model.layers).toHaveLength(2);
    expect(model.layers[0].z).toBe(0.2);
    expect(model.layers[1].z).toBe(0.4);
    expect(model.layers[0].segments).toHaveLength(2);
    expect(model.layers[1].segments).toHaveLength(2);
  });

  it("detects PrusaSlicer and its own estimates from the comments", () => {
    const model = parseGcode(PRUSA);
    expect(model.slicer).toContain("PrusaSlicer");
    expect(model.printTimeFromSlicer).toBe("1h 5m 30s");
    expect(model.filamentUsedFromSlicer).toBe("1234.5 mm, 3.68 g");
  });

  it("handles relative positioning and G92 resets", () => {
    const relative = parseGcode(
      [
        "G90",
        "M83",
        "G1 F1200 X10 Y10",
        "G91",
        "G1 X10 Y0 E1",
        "G1 X0 Y10 E1",
        "G90",
        "M83",
        "G1 X10 Y20 E1",
      ].join("\n"),
    );
    const segments = relative.layers[0].segments;
    expect(segments[segments.length - 1].x2).toBe(10);
    expect(segments[segments.length - 1].y2).toBe(20);
    expect(relative.totalFilamentMm).toBe(3);

    const reset = parseGcode(
      ["G90", "M82", "G1 F1200 X10 Y10 E5", "G92 E0", "G1 X20 Y10 E2"].join("\n"),
    );
    expect(reset.totalFilamentMm).toBe(7);
  });

  it("lets G91 make the extruder relative too, the way firmware does", () => {
    // The end gcode every Ender 3 ships with: G91 then a relative retract.
    const model = parseGcode(["M82", "G1 F1200 X10 Y0 E5", "G91", "G1 X0 Y10 E2"].join("\n"));
    expect(model.totalFilamentMm).toBe(7);
  });

  it("stops at the maxLines cap", () => {
    const model = parseGcode(SAMPLE, { maxLines: 20 });
    expect(model.truncated).toBe(true);
    expect(model.lineCount).toBe(20);
    expect(model.layers).toHaveLength(1);
  });
});

describe("layerStats", () => {
  it("reports counts, lengths and the feed range of one layer", () => {
    const model = parseGcode(SAMPLE);
    const stats = layerStats(model, 1);
    expect(stats.index).toBe(1);
    expect(stats.z).toBe(0.4);
    expect(stats.layerHeight).toBeCloseTo(0.2, 9);
    expect(stats.segments).toBe(17);
    expect(stats.extrudingSegments).toBe(16);
    expect(stats.travelSegments).toBe(1);
    expect(stats.filamentMm).toBe(3.5);
    expect(stats.minFeed).toBe(1200);
    expect(stats.maxFeed).toBe(2400);
    expect(stats.bounds.minX).toBe(30);
    expect(stats.bounds.maxX).toBe(40);
  });
});

describe("renderLayerSvg", () => {
  it("draws one extrusion path and is deterministic", () => {
    const model = parseGcode(SAMPLE);
    const svg = renderLayerSvg(model, 0, { showTravel: false, colorBy: "type" });
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg.endsWith("</svg>")).toBe(true);
    expect(svg.match(/<path/g)).toHaveLength(1);
    expect(svg).toContain("Layer 1 at Z 0.20 mm");
    expect(renderLayerSvg(model, 0, { showTravel: false, colorBy: "type" })).toBe(svg);
  });

  it("adds a dashed travel path when travel is shown", () => {
    const model = parseGcode(SAMPLE);
    const svg = renderLayerSvg(model, 0, { showTravel: true, colorBy: "type" });
    expect(svg.match(/<path/g)).toHaveLength(2);
    expect(svg).toContain("stroke-dasharray");
  });

  it("splits the strokes by feed rate when coloring by speed", () => {
    const model = parseGcode(SAMPLE);
    const svg = renderLayerSvg(model, 1, { showTravel: false, colorBy: "speed" });
    expect(svg.match(/<path/g)).toHaveLength(2);
    expect(svg).not.toContain("NaN");
    expect(svg).not.toContain("-0 ");
  });

  it("stacks every layer with the lower ones faded", () => {
    const model = parseGcode(SAMPLE);
    const svg = renderAllLayersSvg(model, { width: 300, height: 300 });
    expect(svg.match(/<path/g)).toHaveLength(2);
    expect(svg).toContain('stroke-opacity="0.18"');
    expect(renderAllLayersSvg(model, { width: 300, height: 300 })).toBe(svg);
    expect(renderAllLayersSvg(model, { upToLayer: 0 }).match(/<path/g)).toHaveLength(1);
  });
});

describe("helpers", () => {
  it("weighs filament from its length", () => {
    // 1000 mm of 1.75 mm PLA is a bit under 3 g.
    expect(filamentWeight(1000)).toBeCloseTo(2.983, 3);
    expect(filamentWeight(1000, 2.85, 1.24)).toBeCloseTo(7.91, 2);
    expect(filamentWeight(0)).toBe(0);
  });

  it("formats durations", () => {
    expect(formatDuration(0)).toBe("0s");
    expect(formatDuration(45)).toBe("45s");
    expect(formatDuration(3930)).toBe("1h 5m 30s");
  });
});

describe("summarize", () => {
  it("produces the labeled rows", () => {
    const rows = summarize(parseGcode(SAMPLE));
    expect(Object.keys(rows)).toEqual([
      "Slicer",
      "Layers",
      "Layer height",
      "Bounds",
      "Filament",
      "Distance",
      "Rough time",
      "Temperatures",
      "Fan",
      "Tool changes",
      "Lines read",
    ]);
    expect(rows.Layers).toContain("2 layers");
    expect(rows["Layer height"]).toContain("0.20 mm average");
    expect(rows.Bounds).toContain("X 10.00 to 40.00 mm");
    expect(rows.Filament).toContain("5.50 mm");
    expect(rows.Temperatures).toBe("hotend 200 C, bed 60 C");
    expect(rows.Fan).toBe("100% at the fastest");
    expect(rows["Tool changes"]).toContain("None");
    expect(rows.Slicer).toBe("Not detected");
  });

  it("adds the slicer estimates when the file carries them", () => {
    const rows = summarize(parseGcode(PRUSA));
    expect(rows["Slicer time"]).toBe("1h 5m 30s");
    expect(rows["Slicer filament"]).toBe("1234.5 mm, 3.68 g");
  });
});

describe("run", () => {
  it("summarizes a dropped file without an SVG by default", () => {
    const bytes = new TextEncoder().encode(SAMPLE);
    const rows = run(bytes, OPTS);
    expect(rows.Layers).toContain("2 layers");
    expect(Object.keys(rows).some((k) => k.includes("SVG"))).toBe(false);
  });

  it("adds the stack and the middle layer when layer is 0", () => {
    const rows = run(SAMPLE, { ...OPTS, svg: true });
    expect(rows["All layers SVG"]).toContain("<svg");
    expect(rows["Layer 1 SVG"]).toContain("<svg");
  });

  it("draws the requested layer, clamped to the top one", () => {
    const rows = run(SAMPLE, { ...OPTS, svg: true, layer: 2, showTravel: true });
    expect(rows["Layer 2 SVG"]).toContain("<svg");
    expect(run(SAMPLE, { ...OPTS, svg: true, layer: 900 })["Layer 2 SVG"]).toContain("<svg");
  });

  it("throws empty-input on nothing at all", () => {
    expect(codeOf(() => run("", OPTS))).toBe("empty-input");
    expect(codeOf(() => run("   \n  ", OPTS))).toBe("empty-input");
    expect(codeOf(() => run(new Uint8Array(0), OPTS))).toBe("empty-input");
    expect(codeOf(() => parseGcode(""))).toBe("empty-input");
  });

  it("throws not-gcode when the file holds no moves", () => {
    expect(codeOf(() => run("hello world\nthis is not a program\n", OPTS))).toBe("not-gcode");
    expect(codeOf(() => run("; only comments\n;LAYER:0\n", OPTS))).toBe("not-gcode");
  });

  it("throws too-large past 100 MB", () => {
    expect(codeOf(() => run(new Uint8Array(100 * 1024 * 1024 + 1), OPTS))).toBe("too-large");
  });

  it("throws bad-option on an unknown coloring or layer number", () => {
    expect(codeOf(() => run(SAMPLE, { ...OPTS, colorBy: "rainbow" }))).toBe("bad-option");
    expect(codeOf(() => run(SAMPLE, { ...OPTS, layer: -1 }))).toBe("bad-option");
    expect(codeOf(() => run(SAMPLE, { ...OPTS, layer: 1.5 }))).toBe("bad-option");
    expect(codeOf(() => run(SAMPLE, { ...OPTS, layer: 99999 }))).toBe("bad-option");
    expect(codeOf(() => layerStats(parseGcode(SAMPLE), 9))).toBe("bad-option");
    expect(codeOf(() => renderLayerSvg(parseGcode(SAMPLE), 9))).toBe("bad-option");
  });
});
