import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "nfpa-704-fire-diamond",
  icon: "ShieldAlert",
  name: "NFPA 704 Fire Diamond",
  description:
    "Search chemicals by their NFPA 704 diamond, or look one up by name, and download the diamond as an SVG.",
  category: "Chemistry",
  keywords: [
    "nfpa 704",
    "fire diamond",
    "hazard diamond",
    "nfpa diamond generator",
    "nfpa 704 lookup",
    "health flammability reactivity rating",
  ],
  searchTerms: [
    "fire diamond",
    "hazmat diamond",
    "hazard placard",
    "704 rating",
    "health fire reactivity",
    "instability rating",
    "water reactive",
    "oxidiser",
    "oxidizer",
    "simple asphyxiant",
    "nfpa sign maker",
    "chemical hazard rating",
    "flammability rating",
    "safety diamond",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "health",
      label: "Health (blue)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["all", "unset", "wildcard", "no filter"] },
        { value: "0", label: "0", synonyms: ["none", "no hazard", "ordinary combustible"] },
        { value: "1", label: "1", synonyms: ["irritant", "minor injury"] },
        { value: "2", label: "2", synonyms: ["incapacitating", "prolonged exposure"] },
        { value: "3", label: "3", synonyms: ["serious injury", "short exposure"] },
        { value: "4", label: "4", synonyms: ["deadly", "lethal", "fatal"] },
      ],
    },
    {
      kind: "select",
      id: "fire",
      label: "Fire (red)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["all", "unset", "wildcard", "no filter"] },
        { value: "0", label: "0", synonyms: ["will not burn", "nonflammable"] },
        { value: "1", label: "1", synonyms: ["needs preheating", "high flash point"] },
        { value: "2", label: "2", synonyms: ["moderate heat", "combustible"] },
        { value: "3", label: "3", synonyms: ["flammable", "ignites at ambient"] },
        { value: "4", label: "4", synonyms: ["extremely flammable", "flammable gas"] },
      ],
    },
    {
      kind: "select",
      id: "instability",
      label: "Instability (yellow)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["all", "unset", "wildcard", "no filter"] },
        { value: "0", label: "0", synonyms: ["stable", "reactivity 0"] },
        { value: "1", label: "1", synonyms: ["unstable when heated"] },
        { value: "2", label: "2", synonyms: ["violent chemical change"] },
        { value: "3", label: "3", synonyms: ["shock sensitive", "may detonate"] },
        { value: "4", label: "4", synonyms: ["explosive", "readily detonates"] },
      ],
    },
    {
      kind: "select",
      id: "water",
      label: "W (reacts with water)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["either", "no filter", "ignore"] },
        { value: "require", label: "Require", synonyms: ["must have", "only", "water reactive"] },
        { value: "exclude", label: "Exclude", synonyms: ["without", "not", "hide"] },
      ],
    },
    {
      kind: "select",
      id: "oxidizer",
      label: "OX (oxidizer)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["either", "no filter", "ignore"] },
        { value: "require", label: "Require", synonyms: ["must have", "only", "oxidiser"] },
        { value: "exclude", label: "Exclude", synonyms: ["without", "not", "hide"] },
      ],
    },
    {
      kind: "select",
      id: "asphyxiant",
      label: "SA (simple asphyxiant)",
      default: "any",
      ui: "segmented",
      options: [
        { value: "any", label: "Any", synonyms: ["either", "no filter", "ignore"] },
        {
          value: "require",
          label: "Require",
          synonyms: ["must have", "only", "asphyxiant gas", "inert gas"],
        },
        { value: "exclude", label: "Exclude", synonyms: ["without", "not", "hide"] },
      ],
    },
    { kind: "boolean", id: "svg", label: "Include the diamond as SVG", default: false },
  ],
  http: { method: "GET", contentType: "application/json" },
  copy: {
    what: "Two searches over the same data. Set the health, fire, and instability quadrants and the three special symbols to see every chemical carrying that exact NFPA 704 diamond, or type a name, synonym, CAS number, or formula to have the quadrants filled in for you. The diamond itself is drawn as an SVG you can download, optionally captioned with the chemical name. Ratings come from PubChem's NFPA annotations and from English Wikipedia chembox parameters, and when the two disagree both are shown rather than one being picked silently.",
    how: "Pick a value from 0 to 4 for each quadrant, or leave it on Any to keep it open. Set W, OX, and SA to Require or Exclude to narrow the white quadrant. Results are sorted by name with a count, and when a combination has only a few matches the closest other ratings are listed too. To go the other way, type a chemical into the search box and pick a result to load its diamond.",
    why: "The NFPA 704 pages that rank well are either a single static image or a paid sign builder. This one is a real search over a few thousand rated chemicals, it draws a downloadable diamond, it tells you which source each rating came from, and it runs entirely in your browser, so your inputs never leave your device.",
    faq: [
      {
        q: "Can I use this to label a container at work?",
        a: "No. This is a reference, not a compliance tool. Nothing here is a basis for a workplace safety decision. Verify every rating against the safety data sheet, NFPA 704 itself, and the authority having jurisdiction before anything gets placarded.",
      },
      {
        q: "Why do some chemicals show two different diamonds?",
        a: "Because PubChem and Wikipedia disagree about them. Rather than pick a winner, both ratings are shown with their source. PubChem's annotations also frequently leave the white quadrant empty, so a search for W or OX matches against the union of the two sources.",
      },
      {
        q: "What do W, OX, and SA mean?",
        a: "W with a line through it means the chemical reacts dangerously with water, so water should not be used to fight the fire. OX means it is an oxidizer. SA means simple asphyxiant, and it is reserved for nitrogen, helium, neon, argon, krypton, xenon, and a handful of other gases that displace breathable air.",
      },
    ],
  },
};
