/**
 * Curated Unicode dataset for the unicode-picker tool.
 *
 * GENERATED from the Unicode Character Database (UnicodeData.txt) — every
 * `name` is the official Unicode name lowercased, every `codepoint` is derived
 * from the character itself, and every `htmlEntity` was round-trip validated
 * (HTML4 legacy name where one exists, else an HTML5 name, else numeric hex).
 * index.test.ts re-verifies the codepoint/entity invariants, so hand edits that
 * break them fail the suite.
 *
 * Invisible characters are written as \uXXXX escapes on purpose.
 */

export interface UnicodeEntry {
  /** The character itself — this is what the user copies. */
  char: string;
  /** Official Unicode name, lowercased (e.g. "rightwards arrow"). */
  name: string;
  /** Category id — matches an id in CATEGORIES. */
  category: string;
  /** "U+XXXX" form of the code point. */
  codepoint: string;
  /** Named HTML entity where one exists, else numeric ("&#xXXXX;"). */
  htmlEntity: string;
}

export interface UnicodeCategory {
  id: string;
  label: string;
}

/** Every category present in ENTRIES, in display order. */
export const CATEGORIES: readonly UnicodeCategory[] = [
  { id: 'arrows', label: 'Arrows' },
  { id: 'math', label: 'Maths & logic' },
  { id: 'greek', label: 'Greek letters' },
  { id: 'currency', label: 'Currency' },
  { id: 'punctuation', label: 'Punctuation & dashes' },
  { id: 'box', label: 'Box drawing' },
  { id: 'superscript', label: 'Superscript & subscript' },
  { id: 'symbols', label: 'Checks, stars & bullets' },
  { id: 'legal', label: 'Legal & editorial' },
  { id: 'invisible', label: 'Invisible characters' },
];

export const ENTRIES: readonly UnicodeEntry[] = [
  { char: '←', name: 'leftwards arrow', category: 'arrows', codepoint: 'U+2190', htmlEntity: '&larr;' },
  { char: '↑', name: 'upwards arrow', category: 'arrows', codepoint: 'U+2191', htmlEntity: '&ShortUpArrow;' },
  { char: '→', name: 'rightwards arrow', category: 'arrows', codepoint: 'U+2192', htmlEntity: '&rarr;' },
  { char: '↓', name: 'downwards arrow', category: 'arrows', codepoint: 'U+2193', htmlEntity: '&darr;' },
  { char: '↔', name: 'left right arrow', category: 'arrows', codepoint: 'U+2194', htmlEntity: '&harr;' },
  { char: '↕', name: 'up down arrow', category: 'arrows', codepoint: 'U+2195', htmlEntity: '&updownarrow;' },
  { char: '↖', name: 'north west arrow', category: 'arrows', codepoint: 'U+2196', htmlEntity: '&nwarr;' },
  { char: '↗', name: 'north east arrow', category: 'arrows', codepoint: 'U+2197', htmlEntity: '&nearr;' },
  { char: '↘', name: 'south east arrow', category: 'arrows', codepoint: 'U+2198', htmlEntity: '&LowerRightArrow;' },
  { char: '↙', name: 'south west arrow', category: 'arrows', codepoint: 'U+2199', htmlEntity: '&LowerLeftArrow;' },
  { char: '↚', name: 'leftwards arrow with stroke', category: 'arrows', codepoint: 'U+219A', htmlEntity: '&nlarr;' },
  { char: '↛', name: 'rightwards arrow with stroke', category: 'arrows', codepoint: 'U+219B', htmlEntity: '&nrarr;' },
  { char: '↞', name: 'leftwards two headed arrow', category: 'arrows', codepoint: 'U+219E', htmlEntity: '&Larr;' },
  { char: '↠', name: 'rightwards two headed arrow', category: 'arrows', codepoint: 'U+21A0', htmlEntity: '&Rarr;' },
  { char: '↢', name: 'leftwards arrow with tail', category: 'arrows', codepoint: 'U+21A2', htmlEntity: '&larrtl;' },
  { char: '↣', name: 'rightwards arrow with tail', category: 'arrows', codepoint: 'U+21A3', htmlEntity: '&rarrtl;' },
  { char: '↤', name: 'leftwards arrow from bar', category: 'arrows', codepoint: 'U+21A4', htmlEntity: '&LeftTeeArrow;' },
  { char: '↦', name: 'rightwards arrow from bar', category: 'arrows', codepoint: 'U+21A6', htmlEntity: '&map;' },
  { char: '↩', name: 'leftwards arrow with hook', category: 'arrows', codepoint: 'U+21A9', htmlEntity: '&hookleftarrow;' },
  { char: '↪', name: 'rightwards arrow with hook', category: 'arrows', codepoint: 'U+21AA', htmlEntity: '&hookrightarrow;' },
  { char: '↰', name: 'upwards arrow with tip leftwards', category: 'arrows', codepoint: 'U+21B0', htmlEntity: '&lsh;' },
  { char: '↱', name: 'upwards arrow with tip rightwards', category: 'arrows', codepoint: 'U+21B1', htmlEntity: '&rsh;' },
  { char: '↲', name: 'downwards arrow with tip leftwards', category: 'arrows', codepoint: 'U+21B2', htmlEntity: '&ldsh;' },
  { char: '↳', name: 'downwards arrow with tip rightwards', category: 'arrows', codepoint: 'U+21B3', htmlEntity: '&rdsh;' },
  { char: '↵', name: 'downwards arrow with corner leftwards', category: 'arrows', codepoint: 'U+21B5', htmlEntity: '&crarr;' },
  { char: '↶', name: 'anticlockwise top semicircle arrow', category: 'arrows', codepoint: 'U+21B6', htmlEntity: '&cularr;' },
  { char: '↷', name: 'clockwise top semicircle arrow', category: 'arrows', codepoint: 'U+21B7', htmlEntity: '&curarr;' },
  { char: '↸', name: 'north west arrow to long bar', category: 'arrows', codepoint: 'U+21B8', htmlEntity: '&#x21B8;' },
  { char: '↺', name: 'anticlockwise open circle arrow', category: 'arrows', codepoint: 'U+21BA', htmlEntity: '&circlearrowleft;' },
  { char: '↻', name: 'clockwise open circle arrow', category: 'arrows', codepoint: 'U+21BB', htmlEntity: '&circlearrowright;' },
  { char: '↼', name: 'leftwards harpoon with barb upwards', category: 'arrows', codepoint: 'U+21BC', htmlEntity: '&leftharpoonup;' },
  { char: '↽', name: 'leftwards harpoon with barb downwards', category: 'arrows', codepoint: 'U+21BD', htmlEntity: '&DownLeftVector;' },
  { char: '⇀', name: 'rightwards harpoon with barb upwards', category: 'arrows', codepoint: 'U+21C0', htmlEntity: '&rharu;' },
  { char: '⇁', name: 'rightwards harpoon with barb downwards', category: 'arrows', codepoint: 'U+21C1', htmlEntity: '&DownRightVector;' },
  { char: '⇄', name: 'rightwards arrow over leftwards arrow', category: 'arrows', codepoint: 'U+21C4', htmlEntity: '&RightArrowLeftArrow;' },
  { char: '⇅', name: 'upwards arrow leftwards of downwards arrow', category: 'arrows', codepoint: 'U+21C5', htmlEntity: '&udarr;' },
  { char: '⇆', name: 'leftwards arrow over rightwards arrow', category: 'arrows', codepoint: 'U+21C6', htmlEntity: '&LeftArrowRightArrow;' },
  { char: '⇇', name: 'leftwards paired arrows', category: 'arrows', codepoint: 'U+21C7', htmlEntity: '&leftleftarrows;' },
  { char: '⇉', name: 'rightwards paired arrows', category: 'arrows', codepoint: 'U+21C9', htmlEntity: '&rightrightarrows;' },
  { char: '⇋', name: 'leftwards harpoon over rightwards harpoon', category: 'arrows', codepoint: 'U+21CB', htmlEntity: '&leftrightharpoons;' },
  { char: '⇌', name: 'rightwards harpoon over leftwards harpoon', category: 'arrows', codepoint: 'U+21CC', htmlEntity: '&Equilibrium;' },
  { char: '⇍', name: 'leftwards double arrow with stroke', category: 'arrows', codepoint: 'U+21CD', htmlEntity: '&nlArr;' },
  { char: '⇎', name: 'left right double arrow with stroke', category: 'arrows', codepoint: 'U+21CE', htmlEntity: '&nhArr;' },
  { char: '⇏', name: 'rightwards double arrow with stroke', category: 'arrows', codepoint: 'U+21CF', htmlEntity: '&nrArr;' },
  { char: '⇐', name: 'leftwards double arrow', category: 'arrows', codepoint: 'U+21D0', htmlEntity: '&DoubleLeftArrow;' },
  { char: '⇑', name: 'upwards double arrow', category: 'arrows', codepoint: 'U+21D1', htmlEntity: '&DoubleUpArrow;' },
  { char: '⇒', name: 'rightwards double arrow', category: 'arrows', codepoint: 'U+21D2', htmlEntity: '&DoubleRightArrow;' },
  { char: '⇓', name: 'downwards double arrow', category: 'arrows', codepoint: 'U+21D3', htmlEntity: '&dArr;' },
  { char: '⇔', name: 'left right double arrow', category: 'arrows', codepoint: 'U+21D4', htmlEntity: '&DoubleLeftRightArrow;' },
  { char: '⇕', name: 'up down double arrow', category: 'arrows', codepoint: 'U+21D5', htmlEntity: '&DoubleUpDownArrow;' },
  { char: '⇚', name: 'leftwards triple arrow', category: 'arrows', codepoint: 'U+21DA', htmlEntity: '&lAarr;' },
  { char: '⇛', name: 'rightwards triple arrow', category: 'arrows', codepoint: 'U+21DB', htmlEntity: '&rAarr;' },
  { char: '⇠', name: 'leftwards dashed arrow', category: 'arrows', codepoint: 'U+21E0', htmlEntity: '&#x21E0;' },
  { char: '⇡', name: 'upwards dashed arrow', category: 'arrows', codepoint: 'U+21E1', htmlEntity: '&#x21E1;' },
  { char: '⇢', name: 'rightwards dashed arrow', category: 'arrows', codepoint: 'U+21E2', htmlEntity: '&#x21E2;' },
  { char: '⇣', name: 'downwards dashed arrow', category: 'arrows', codepoint: 'U+21E3', htmlEntity: '&#x21E3;' },
  { char: '⇦', name: 'leftwards white arrow', category: 'arrows', codepoint: 'U+21E6', htmlEntity: '&#x21E6;' },
  { char: '⇧', name: 'upwards white arrow', category: 'arrows', codepoint: 'U+21E7', htmlEntity: '&#x21E7;' },
  { char: '⇨', name: 'rightwards white arrow', category: 'arrows', codepoint: 'U+21E8', htmlEntity: '&#x21E8;' },
  { char: '⇩', name: 'downwards white arrow', category: 'arrows', codepoint: 'U+21E9', htmlEntity: '&#x21E9;' },
  { char: '⇵', name: 'downwards arrow leftwards of upwards arrow', category: 'arrows', codepoint: 'U+21F5', htmlEntity: '&DownArrowUpArrow;' },
  { char: '➡', name: 'black rightwards arrow', category: 'arrows', codepoint: 'U+27A1', htmlEntity: '&#x27A1;' },
  { char: '⤴', name: 'arrow pointing rightwards then curving upwards', category: 'arrows', codepoint: 'U+2934', htmlEntity: '&#x2934;' },
  { char: '⤵', name: 'arrow pointing rightwards then curving downwards', category: 'arrows', codepoint: 'U+2935', htmlEntity: '&cudarrr;' },
  { char: '⬅', name: 'leftwards black arrow', category: 'arrows', codepoint: 'U+2B05', htmlEntity: '&#x2B05;' },
  { char: '⬆', name: 'upwards black arrow', category: 'arrows', codepoint: 'U+2B06', htmlEntity: '&#x2B06;' },
  { char: '⬇', name: 'downwards black arrow', category: 'arrows', codepoint: 'U+2B07', htmlEntity: '&#x2B07;' },
  { char: '±', name: 'plus-minus sign', category: 'math', codepoint: 'U+00B1', htmlEntity: '&PlusMinus;' },
  { char: '×', name: 'multiplication sign', category: 'math', codepoint: 'U+00D7', htmlEntity: '&times;' },
  { char: '÷', name: 'division sign', category: 'math', codepoint: 'U+00F7', htmlEntity: '&div;' },
  { char: '¬', name: 'not sign', category: 'math', codepoint: 'U+00AC', htmlEntity: '&not;' },
  { char: '⁄', name: 'fraction slash', category: 'math', codepoint: 'U+2044', htmlEntity: '&frasl;' },
  { char: '⁒', name: 'commercial minus sign', category: 'math', codepoint: 'U+2052', htmlEntity: '&#x2052;' },
  { char: '∀', name: 'for all', category: 'math', codepoint: 'U+2200', htmlEntity: '&forall;' },
  { char: '∁', name: 'complement', category: 'math', codepoint: 'U+2201', htmlEntity: '&comp;' },
  { char: '∂', name: 'partial differential', category: 'math', codepoint: 'U+2202', htmlEntity: '&part;' },
  { char: '∃', name: 'there exists', category: 'math', codepoint: 'U+2203', htmlEntity: '&exist;' },
  { char: '∄', name: 'there does not exist', category: 'math', codepoint: 'U+2204', htmlEntity: '&nexist;' },
  { char: '∅', name: 'empty set', category: 'math', codepoint: 'U+2205', htmlEntity: '&empty;' },
  { char: '∆', name: 'increment', category: 'math', codepoint: 'U+2206', htmlEntity: '&#x2206;' },
  { char: '∇', name: 'nabla', category: 'math', codepoint: 'U+2207', htmlEntity: '&Del;' },
  { char: '∈', name: 'element of', category: 'math', codepoint: 'U+2208', htmlEntity: '&Element;' },
  { char: '∉', name: 'not an element of', category: 'math', codepoint: 'U+2209', htmlEntity: '&NotElement;' },
  { char: '∋', name: 'contains as member', category: 'math', codepoint: 'U+220B', htmlEntity: '&ni;' },
  { char: '∏', name: 'n-ary product', category: 'math', codepoint: 'U+220F', htmlEntity: '&prod;' },
  { char: '∑', name: 'n-ary summation', category: 'math', codepoint: 'U+2211', htmlEntity: '&sum;' },
  { char: '−', name: 'minus sign', category: 'math', codepoint: 'U+2212', htmlEntity: '&minus;' },
  { char: '∓', name: 'minus-or-plus sign', category: 'math', codepoint: 'U+2213', htmlEntity: '&MinusPlus;' },
  { char: '∕', name: 'division slash', category: 'math', codepoint: 'U+2215', htmlEntity: '&#x2215;' },
  { char: '∖', name: 'set minus', category: 'math', codepoint: 'U+2216', htmlEntity: '&Backslash;' },
  { char: '∗', name: 'asterisk operator', category: 'math', codepoint: 'U+2217', htmlEntity: '&lowast;' },
  { char: '∘', name: 'ring operator', category: 'math', codepoint: 'U+2218', htmlEntity: '&compfn;' },
  { char: '∙', name: 'bullet operator', category: 'math', codepoint: 'U+2219', htmlEntity: '&#x2219;' },
  { char: '√', name: 'square root', category: 'math', codepoint: 'U+221A', htmlEntity: '&radic;' },
  { char: '∛', name: 'cube root', category: 'math', codepoint: 'U+221B', htmlEntity: '&#x221B;' },
  { char: '∜', name: 'fourth root', category: 'math', codepoint: 'U+221C', htmlEntity: '&#x221C;' },
  { char: '∝', name: 'proportional to', category: 'math', codepoint: 'U+221D', htmlEntity: '&prop;' },
  { char: '∞', name: 'infinity', category: 'math', codepoint: 'U+221E', htmlEntity: '&infin;' },
  { char: '∟', name: 'right angle', category: 'math', codepoint: 'U+221F', htmlEntity: '&angrt;' },
  { char: '∠', name: 'angle', category: 'math', codepoint: 'U+2220', htmlEntity: '&ang;' },
  { char: '∡', name: 'measured angle', category: 'math', codepoint: 'U+2221', htmlEntity: '&angmsd;' },
  { char: '∥', name: 'parallel to', category: 'math', codepoint: 'U+2225', htmlEntity: '&DoubleVerticalBar;' },
  { char: '∦', name: 'not parallel to', category: 'math', codepoint: 'U+2226', htmlEntity: '&NotDoubleVerticalBar;' },
  { char: '∧', name: 'logical and', category: 'math', codepoint: 'U+2227', htmlEntity: '&and;' },
  { char: '∨', name: 'logical or', category: 'math', codepoint: 'U+2228', htmlEntity: '&or;' },
  { char: '∩', name: 'intersection', category: 'math', codepoint: 'U+2229', htmlEntity: '&cap;' },
  { char: '∪', name: 'union', category: 'math', codepoint: 'U+222A', htmlEntity: '&cup;' },
  { char: '∫', name: 'integral', category: 'math', codepoint: 'U+222B', htmlEntity: '&int;' },
  { char: '∬', name: 'double integral', category: 'math', codepoint: 'U+222C', htmlEntity: '&Int;' },
  { char: '∮', name: 'contour integral', category: 'math', codepoint: 'U+222E', htmlEntity: '&conint;' },
  { char: '∴', name: 'therefore', category: 'math', codepoint: 'U+2234', htmlEntity: '&there4;' },
  { char: '∵', name: 'because', category: 'math', codepoint: 'U+2235', htmlEntity: '&becaus;' },
  { char: '∷', name: 'proportion', category: 'math', codepoint: 'U+2237', htmlEntity: '&Colon;' },
  { char: '∼', name: 'tilde operator', category: 'math', codepoint: 'U+223C', htmlEntity: '&sim;' },
  { char: '≃', name: 'asymptotically equal to', category: 'math', codepoint: 'U+2243', htmlEntity: '&sime;' },
  { char: '≅', name: 'approximately equal to', category: 'math', codepoint: 'U+2245', htmlEntity: '&cong;' },
  { char: '≈', name: 'almost equal to', category: 'math', codepoint: 'U+2248', htmlEntity: '&ap;' },
  { char: '≉', name: 'not almost equal to', category: 'math', codepoint: 'U+2249', htmlEntity: '&nap;' },
  { char: '≠', name: 'not equal to', category: 'math', codepoint: 'U+2260', htmlEntity: '&ne;' },
  { char: '≡', name: 'identical to', category: 'math', codepoint: 'U+2261', htmlEntity: '&Congruent;' },
  { char: '≢', name: 'not identical to', category: 'math', codepoint: 'U+2262', htmlEntity: '&nequiv;' },
  { char: '≤', name: 'less-than or equal to', category: 'math', codepoint: 'U+2264', htmlEntity: '&le;' },
  { char: '≥', name: 'greater-than or equal to', category: 'math', codepoint: 'U+2265', htmlEntity: '&ge;' },
  { char: '≪', name: 'much less-than', category: 'math', codepoint: 'U+226A', htmlEntity: '&ll;' },
  { char: '≫', name: 'much greater-than', category: 'math', codepoint: 'U+226B', htmlEntity: '&gg;' },
  { char: '≺', name: 'precedes', category: 'math', codepoint: 'U+227A', htmlEntity: '&pr;' },
  { char: '≻', name: 'succeeds', category: 'math', codepoint: 'U+227B', htmlEntity: '&sc;' },
  { char: '⊂', name: 'subset of', category: 'math', codepoint: 'U+2282', htmlEntity: '&sub;' },
  { char: '⊃', name: 'superset of', category: 'math', codepoint: 'U+2283', htmlEntity: '&sup;' },
  { char: '⊄', name: 'not a subset of', category: 'math', codepoint: 'U+2284', htmlEntity: '&nsub;' },
  { char: '⊆', name: 'subset of or equal to', category: 'math', codepoint: 'U+2286', htmlEntity: '&sube;' },
  { char: '⊇', name: 'superset of or equal to', category: 'math', codepoint: 'U+2287', htmlEntity: '&supe;' },
  { char: '⊕', name: 'circled plus', category: 'math', codepoint: 'U+2295', htmlEntity: '&CirclePlus;' },
  { char: '⊖', name: 'circled minus', category: 'math', codepoint: 'U+2296', htmlEntity: '&CircleMinus;' },
  { char: '⊗', name: 'circled times', category: 'math', codepoint: 'U+2297', htmlEntity: '&CircleTimes;' },
  { char: '⊙', name: 'circled dot operator', category: 'math', codepoint: 'U+2299', htmlEntity: '&CircleDot;' },
  { char: '⊢', name: 'right tack', category: 'math', codepoint: 'U+22A2', htmlEntity: '&RightTee;' },
  { char: '⊣', name: 'left tack', category: 'math', codepoint: 'U+22A3', htmlEntity: '&dashv;' },
  { char: '⊤', name: 'down tack', category: 'math', codepoint: 'U+22A4', htmlEntity: '&DownTee;' },
  { char: '⊥', name: 'up tack', category: 'math', codepoint: 'U+22A5', htmlEntity: '&bot;' },
  { char: '⋅', name: 'dot operator', category: 'math', codepoint: 'U+22C5', htmlEntity: '&sdot;' },
  { char: '⋆', name: 'star operator', category: 'math', codepoint: 'U+22C6', htmlEntity: '&sstarf;' },
  { char: '⌈', name: 'left ceiling', category: 'math', codepoint: 'U+2308', htmlEntity: '&lceil;' },
  { char: '⌉', name: 'right ceiling', category: 'math', codepoint: 'U+2309', htmlEntity: '&rceil;' },
  { char: '⌊', name: 'left floor', category: 'math', codepoint: 'U+230A', htmlEntity: '&LeftFloor;' },
  { char: '⌋', name: 'right floor', category: 'math', codepoint: 'U+230B', htmlEntity: '&rfloor;' },
  { char: '⟨', name: 'mathematical left angle bracket', category: 'math', codepoint: 'U+27E8', htmlEntity: '&lang;' },
  { char: '⟩', name: 'mathematical right angle bracket', category: 'math', codepoint: 'U+27E9', htmlEntity: '&rang;' },
  { char: '¼', name: 'vulgar fraction one quarter', category: 'math', codepoint: 'U+00BC', htmlEntity: '&frac14;' },
  { char: '½', name: 'vulgar fraction one half', category: 'math', codepoint: 'U+00BD', htmlEntity: '&frac12;' },
  { char: '¾', name: 'vulgar fraction three quarters', category: 'math', codepoint: 'U+00BE', htmlEntity: '&frac34;' },
  { char: '⅓', name: 'vulgar fraction one third', category: 'math', codepoint: 'U+2153', htmlEntity: '&frac13;' },
  { char: '⅔', name: 'vulgar fraction two thirds', category: 'math', codepoint: 'U+2154', htmlEntity: '&frac23;' },
  { char: '⅛', name: 'vulgar fraction one eighth', category: 'math', codepoint: 'U+215B', htmlEntity: '&frac18;' },
  { char: '℅', name: 'care of', category: 'math', codepoint: 'U+2105', htmlEntity: '&incare;' },
  { char: '‰', name: 'per mille sign', category: 'math', codepoint: 'U+2030', htmlEntity: '&permil;' },
  { char: '‱', name: 'per ten thousand sign', category: 'math', codepoint: 'U+2031', htmlEntity: '&pertenk;' },
  { char: '′', name: 'prime', category: 'math', codepoint: 'U+2032', htmlEntity: '&prime;' },
  { char: '″', name: 'double prime', category: 'math', codepoint: 'U+2033', htmlEntity: '&Prime;' },
  { char: 'ℯ', name: 'script small e', category: 'math', codepoint: 'U+212F', htmlEntity: '&escr;' },
  { char: 'ℕ', name: 'double-struck capital n', category: 'math', codepoint: 'U+2115', htmlEntity: '&naturals;' },
  { char: 'ℤ', name: 'double-struck capital z', category: 'math', codepoint: 'U+2124', htmlEntity: '&integers;' },
  { char: 'ℚ', name: 'double-struck capital q', category: 'math', codepoint: 'U+211A', htmlEntity: '&Qopf;' },
  { char: 'ℝ', name: 'double-struck capital r', category: 'math', codepoint: 'U+211D', htmlEntity: '&reals;' },
  { char: 'ℂ', name: 'double-struck capital c', category: 'math', codepoint: 'U+2102', htmlEntity: '&complexes;' },
  { char: 'Α', name: 'greek capital letter alpha', category: 'greek', codepoint: 'U+0391', htmlEntity: '&Alpha;' },
  { char: 'Β', name: 'greek capital letter beta', category: 'greek', codepoint: 'U+0392', htmlEntity: '&Beta;' },
  { char: 'Γ', name: 'greek capital letter gamma', category: 'greek', codepoint: 'U+0393', htmlEntity: '&Gamma;' },
  { char: 'Δ', name: 'greek capital letter delta', category: 'greek', codepoint: 'U+0394', htmlEntity: '&Delta;' },
  { char: 'Ε', name: 'greek capital letter epsilon', category: 'greek', codepoint: 'U+0395', htmlEntity: '&Epsilon;' },
  { char: 'Ζ', name: 'greek capital letter zeta', category: 'greek', codepoint: 'U+0396', htmlEntity: '&Zeta;' },
  { char: 'Η', name: 'greek capital letter eta', category: 'greek', codepoint: 'U+0397', htmlEntity: '&Eta;' },
  { char: 'Θ', name: 'greek capital letter theta', category: 'greek', codepoint: 'U+0398', htmlEntity: '&Theta;' },
  { char: 'Ι', name: 'greek capital letter iota', category: 'greek', codepoint: 'U+0399', htmlEntity: '&Iota;' },
  { char: 'Κ', name: 'greek capital letter kappa', category: 'greek', codepoint: 'U+039A', htmlEntity: '&Kappa;' },
  { char: 'Λ', name: 'greek capital letter lamda', category: 'greek', codepoint: 'U+039B', htmlEntity: '&Lambda;' },
  { char: 'Μ', name: 'greek capital letter mu', category: 'greek', codepoint: 'U+039C', htmlEntity: '&Mu;' },
  { char: 'Ν', name: 'greek capital letter nu', category: 'greek', codepoint: 'U+039D', htmlEntity: '&Nu;' },
  { char: 'Ξ', name: 'greek capital letter xi', category: 'greek', codepoint: 'U+039E', htmlEntity: '&Xi;' },
  { char: 'Ο', name: 'greek capital letter omicron', category: 'greek', codepoint: 'U+039F', htmlEntity: '&Omicron;' },
  { char: 'Π', name: 'greek capital letter pi', category: 'greek', codepoint: 'U+03A0', htmlEntity: '&Pi;' },
  { char: 'Ρ', name: 'greek capital letter rho', category: 'greek', codepoint: 'U+03A1', htmlEntity: '&Rho;' },
  { char: 'Σ', name: 'greek capital letter sigma', category: 'greek', codepoint: 'U+03A3', htmlEntity: '&Sigma;' },
  { char: 'Τ', name: 'greek capital letter tau', category: 'greek', codepoint: 'U+03A4', htmlEntity: '&Tau;' },
  { char: 'Υ', name: 'greek capital letter upsilon', category: 'greek', codepoint: 'U+03A5', htmlEntity: '&Upsilon;' },
  { char: 'Φ', name: 'greek capital letter phi', category: 'greek', codepoint: 'U+03A6', htmlEntity: '&Phi;' },
  { char: 'Χ', name: 'greek capital letter chi', category: 'greek', codepoint: 'U+03A7', htmlEntity: '&Chi;' },
  { char: 'Ψ', name: 'greek capital letter psi', category: 'greek', codepoint: 'U+03A8', htmlEntity: '&Psi;' },
  { char: 'Ω', name: 'greek capital letter omega', category: 'greek', codepoint: 'U+03A9', htmlEntity: '&ohm;' },
  { char: 'α', name: 'greek small letter alpha', category: 'greek', codepoint: 'U+03B1', htmlEntity: '&alpha;' },
  { char: 'β', name: 'greek small letter beta', category: 'greek', codepoint: 'U+03B2', htmlEntity: '&beta;' },
  { char: 'γ', name: 'greek small letter gamma', category: 'greek', codepoint: 'U+03B3', htmlEntity: '&gamma;' },
  { char: 'δ', name: 'greek small letter delta', category: 'greek', codepoint: 'U+03B4', htmlEntity: '&delta;' },
  { char: 'ε', name: 'greek small letter epsilon', category: 'greek', codepoint: 'U+03B5', htmlEntity: '&epsi;' },
  { char: 'ζ', name: 'greek small letter zeta', category: 'greek', codepoint: 'U+03B6', htmlEntity: '&zeta;' },
  { char: 'η', name: 'greek small letter eta', category: 'greek', codepoint: 'U+03B7', htmlEntity: '&eta;' },
  { char: 'θ', name: 'greek small letter theta', category: 'greek', codepoint: 'U+03B8', htmlEntity: '&theta;' },
  { char: 'ι', name: 'greek small letter iota', category: 'greek', codepoint: 'U+03B9', htmlEntity: '&iota;' },
  { char: 'κ', name: 'greek small letter kappa', category: 'greek', codepoint: 'U+03BA', htmlEntity: '&kappa;' },
  { char: 'λ', name: 'greek small letter lamda', category: 'greek', codepoint: 'U+03BB', htmlEntity: '&lambda;' },
  { char: 'μ', name: 'greek small letter mu', category: 'greek', codepoint: 'U+03BC', htmlEntity: '&mu;' },
  { char: 'ν', name: 'greek small letter nu', category: 'greek', codepoint: 'U+03BD', htmlEntity: '&nu;' },
  { char: 'ξ', name: 'greek small letter xi', category: 'greek', codepoint: 'U+03BE', htmlEntity: '&xi;' },
  { char: 'ο', name: 'greek small letter omicron', category: 'greek', codepoint: 'U+03BF', htmlEntity: '&omicron;' },
  { char: 'π', name: 'greek small letter pi', category: 'greek', codepoint: 'U+03C0', htmlEntity: '&pi;' },
  { char: 'ρ', name: 'greek small letter rho', category: 'greek', codepoint: 'U+03C1', htmlEntity: '&rho;' },
  { char: 'ς', name: 'greek small letter final sigma', category: 'greek', codepoint: 'U+03C2', htmlEntity: '&sigmaf;' },
  { char: 'σ', name: 'greek small letter sigma', category: 'greek', codepoint: 'U+03C3', htmlEntity: '&sigma;' },
  { char: 'τ', name: 'greek small letter tau', category: 'greek', codepoint: 'U+03C4', htmlEntity: '&tau;' },
  { char: 'υ', name: 'greek small letter upsilon', category: 'greek', codepoint: 'U+03C5', htmlEntity: '&upsi;' },
  { char: 'φ', name: 'greek small letter phi', category: 'greek', codepoint: 'U+03C6', htmlEntity: '&phi;' },
  { char: 'χ', name: 'greek small letter chi', category: 'greek', codepoint: 'U+03C7', htmlEntity: '&chi;' },
  { char: 'ψ', name: 'greek small letter psi', category: 'greek', codepoint: 'U+03C8', htmlEntity: '&psi;' },
  { char: 'ω', name: 'greek small letter omega', category: 'greek', codepoint: 'U+03C9', htmlEntity: '&omega;' },
  { char: 'ϑ', name: 'greek theta symbol', category: 'greek', codepoint: 'U+03D1', htmlEntity: '&thetasym;' },
  { char: 'ϕ', name: 'greek phi symbol', category: 'greek', codepoint: 'U+03D5', htmlEntity: '&phiv;' },
  { char: 'ϖ', name: 'greek pi symbol', category: 'greek', codepoint: 'U+03D6', htmlEntity: '&piv;' },
  { char: 'ϵ', name: 'greek lunate epsilon symbol', category: 'greek', codepoint: 'U+03F5', htmlEntity: '&epsiv;' },
  { char: 'ϝ', name: 'greek small letter digamma', category: 'greek', codepoint: 'U+03DD', htmlEntity: '&digamma;' },
  { char: '$', name: 'dollar sign', category: 'currency', codepoint: 'U+0024', htmlEntity: '&dollar;' },
  { char: '¢', name: 'cent sign', category: 'currency', codepoint: 'U+00A2', htmlEntity: '&cent;' },
  { char: '£', name: 'pound sign', category: 'currency', codepoint: 'U+00A3', htmlEntity: '&pound;' },
  { char: '¤', name: 'currency sign', category: 'currency', codepoint: 'U+00A4', htmlEntity: '&curren;' },
  { char: '¥', name: 'yen sign', category: 'currency', codepoint: 'U+00A5', htmlEntity: '&yen;' },
  { char: '₡', name: 'colon sign', category: 'currency', codepoint: 'U+20A1', htmlEntity: '&#x20A1;' },
  { char: '₣', name: 'french franc sign', category: 'currency', codepoint: 'U+20A3', htmlEntity: '&#x20A3;' },
  { char: '₤', name: 'lira sign', category: 'currency', codepoint: 'U+20A4', htmlEntity: '&#x20A4;' },
  { char: '₦', name: 'naira sign', category: 'currency', codepoint: 'U+20A6', htmlEntity: '&#x20A6;' },
  { char: '₨', name: 'rupee sign', category: 'currency', codepoint: 'U+20A8', htmlEntity: '&#x20A8;' },
  { char: '₩', name: 'won sign', category: 'currency', codepoint: 'U+20A9', htmlEntity: '&#x20A9;' },
  { char: '₪', name: 'new sheqel sign', category: 'currency', codepoint: 'U+20AA', htmlEntity: '&#x20AA;' },
  { char: '₫', name: 'dong sign', category: 'currency', codepoint: 'U+20AB', htmlEntity: '&#x20AB;' },
  { char: '€', name: 'euro sign', category: 'currency', codepoint: 'U+20AC', htmlEntity: '&euro;' },
  { char: '₭', name: 'kip sign', category: 'currency', codepoint: 'U+20AD', htmlEntity: '&#x20AD;' },
  { char: '₮', name: 'tugrik sign', category: 'currency', codepoint: 'U+20AE', htmlEntity: '&#x20AE;' },
  { char: '₱', name: 'peso sign', category: 'currency', codepoint: 'U+20B1', htmlEntity: '&#x20B1;' },
  { char: '₲', name: 'guarani sign', category: 'currency', codepoint: 'U+20B2', htmlEntity: '&#x20B2;' },
  { char: '₴', name: 'hryvnia sign', category: 'currency', codepoint: 'U+20B4', htmlEntity: '&#x20B4;' },
  { char: '₵', name: 'cedi sign', category: 'currency', codepoint: 'U+20B5', htmlEntity: '&#x20B5;' },
  { char: '₸', name: 'tenge sign', category: 'currency', codepoint: 'U+20B8', htmlEntity: '&#x20B8;' },
  { char: '₹', name: 'indian rupee sign', category: 'currency', codepoint: 'U+20B9', htmlEntity: '&#x20B9;' },
  { char: '₺', name: 'turkish lira sign', category: 'currency', codepoint: 'U+20BA', htmlEntity: '&#x20BA;' },
  { char: '₼', name: 'manat sign', category: 'currency', codepoint: 'U+20BC', htmlEntity: '&#x20BC;' },
  { char: '₽', name: 'ruble sign', category: 'currency', codepoint: 'U+20BD', htmlEntity: '&#x20BD;' },
  { char: '₾', name: 'lari sign', category: 'currency', codepoint: 'U+20BE', htmlEntity: '&#x20BE;' },
  { char: '₿', name: 'bitcoin sign', category: 'currency', codepoint: 'U+20BF', htmlEntity: '&#x20BF;' },
  { char: '₯', name: 'drachma sign', category: 'currency', codepoint: 'U+20AF', htmlEntity: '&#x20AF;' },
  { char: '‐', name: 'hyphen', category: 'punctuation', codepoint: 'U+2010', htmlEntity: '&dash;' },
  { char: '‑', name: 'non-breaking hyphen', category: 'punctuation', codepoint: 'U+2011', htmlEntity: '&#x2011;' },
  { char: '‒', name: 'figure dash', category: 'punctuation', codepoint: 'U+2012', htmlEntity: '&#x2012;' },
  { char: '–', name: 'en dash', category: 'punctuation', codepoint: 'U+2013', htmlEntity: '&ndash;' },
  { char: '—', name: 'em dash', category: 'punctuation', codepoint: 'U+2014', htmlEntity: '&mdash;' },
  { char: '―', name: 'horizontal bar', category: 'punctuation', codepoint: 'U+2015', htmlEntity: '&horbar;' },
  { char: '‖', name: 'double vertical line', category: 'punctuation', codepoint: 'U+2016', htmlEntity: '&Verbar;' },
  { char: '‗', name: 'double low line', category: 'punctuation', codepoint: 'U+2017', htmlEntity: '&#x2017;' },
  { char: '‘', name: 'left single quotation mark', category: 'punctuation', codepoint: 'U+2018', htmlEntity: '&lsquo;' },
  { char: '’', name: 'right single quotation mark', category: 'punctuation', codepoint: 'U+2019', htmlEntity: '&CloseCurlyQuote;' },
  { char: '‚', name: 'single low-9 quotation mark', category: 'punctuation', codepoint: 'U+201A', htmlEntity: '&lsquor;' },
  { char: '‛', name: 'single high-reversed-9 quotation mark', category: 'punctuation', codepoint: 'U+201B', htmlEntity: '&#x201B;' },
  { char: '“', name: 'left double quotation mark', category: 'punctuation', codepoint: 'U+201C', htmlEntity: '&ldquo;' },
  { char: '”', name: 'right double quotation mark', category: 'punctuation', codepoint: 'U+201D', htmlEntity: '&CloseCurlyDoubleQuote;' },
  { char: '„', name: 'double low-9 quotation mark', category: 'punctuation', codepoint: 'U+201E', htmlEntity: '&bdquo;' },
  { char: '‟', name: 'double high-reversed-9 quotation mark', category: 'punctuation', codepoint: 'U+201F', htmlEntity: '&#x201F;' },
  { char: '†', name: 'dagger', category: 'punctuation', codepoint: 'U+2020', htmlEntity: '&dagger;' },
  { char: '‡', name: 'double dagger', category: 'punctuation', codepoint: 'U+2021', htmlEntity: '&Dagger;' },
  { char: '•', name: 'bullet', category: 'punctuation', codepoint: 'U+2022', htmlEntity: '&bull;' },
  { char: '‣', name: 'triangular bullet', category: 'punctuation', codepoint: 'U+2023', htmlEntity: '&#x2023;' },
  { char: '…', name: 'horizontal ellipsis', category: 'punctuation', codepoint: 'U+2026', htmlEntity: '&hellip;' },
  { char: '‧', name: 'hyphenation point', category: 'punctuation', codepoint: 'U+2027', htmlEntity: '&#x2027;' },
  { char: '‹', name: 'single left-pointing angle quotation mark', category: 'punctuation', codepoint: 'U+2039', htmlEntity: '&lsaquo;' },
  { char: '›', name: 'single right-pointing angle quotation mark', category: 'punctuation', codepoint: 'U+203A', htmlEntity: '&rsaquo;' },
  { char: '«', name: 'left-pointing double angle quotation mark', category: 'punctuation', codepoint: 'U+00AB', htmlEntity: '&laquo;' },
  { char: '»', name: 'right-pointing double angle quotation mark', category: 'punctuation', codepoint: 'U+00BB', htmlEntity: '&raquo;' },
  { char: '¡', name: 'inverted exclamation mark', category: 'punctuation', codepoint: 'U+00A1', htmlEntity: '&iexcl;' },
  { char: '¿', name: 'inverted question mark', category: 'punctuation', codepoint: 'U+00BF', htmlEntity: '&iquest;' },
  { char: '·', name: 'middle dot', category: 'punctuation', codepoint: 'U+00B7', htmlEntity: '&centerdot;' },
  { char: '※', name: 'reference mark', category: 'punctuation', codepoint: 'U+203B', htmlEntity: '&#x203B;' },
  { char: '‼', name: 'double exclamation mark', category: 'punctuation', codepoint: 'U+203C', htmlEntity: '&#x203C;' },
  { char: '⁇', name: 'double question mark', category: 'punctuation', codepoint: 'U+2047', htmlEntity: '&#x2047;' },
  { char: '⁈', name: 'question exclamation mark', category: 'punctuation', codepoint: 'U+2048', htmlEntity: '&#x2048;' },
  { char: '⁉', name: 'exclamation question mark', category: 'punctuation', codepoint: 'U+2049', htmlEntity: '&#x2049;' },
  { char: '⁋', name: 'reversed pilcrow sign', category: 'punctuation', codepoint: 'U+204B', htmlEntity: '&#x204B;' },
  { char: '⸺', name: 'two-em dash', category: 'punctuation', codepoint: 'U+2E3A', htmlEntity: '&#x2E3A;' },
  { char: '─', name: 'box drawings light horizontal', category: 'box', codepoint: 'U+2500', htmlEntity: '&boxh;' },
  { char: '│', name: 'box drawings light vertical', category: 'box', codepoint: 'U+2502', htmlEntity: '&boxv;' },
  { char: '┌', name: 'box drawings light down and right', category: 'box', codepoint: 'U+250C', htmlEntity: '&boxdr;' },
  { char: '┐', name: 'box drawings light down and left', category: 'box', codepoint: 'U+2510', htmlEntity: '&boxdl;' },
  { char: '└', name: 'box drawings light up and right', category: 'box', codepoint: 'U+2514', htmlEntity: '&boxur;' },
  { char: '┘', name: 'box drawings light up and left', category: 'box', codepoint: 'U+2518', htmlEntity: '&boxul;' },
  { char: '├', name: 'box drawings light vertical and right', category: 'box', codepoint: 'U+251C', htmlEntity: '&boxvr;' },
  { char: '┤', name: 'box drawings light vertical and left', category: 'box', codepoint: 'U+2524', htmlEntity: '&boxvl;' },
  { char: '┬', name: 'box drawings light down and horizontal', category: 'box', codepoint: 'U+252C', htmlEntity: '&boxhd;' },
  { char: '┴', name: 'box drawings light up and horizontal', category: 'box', codepoint: 'U+2534', htmlEntity: '&boxhu;' },
  { char: '┼', name: 'box drawings light vertical and horizontal', category: 'box', codepoint: 'U+253C', htmlEntity: '&boxvh;' },
  { char: '━', name: 'box drawings heavy horizontal', category: 'box', codepoint: 'U+2501', htmlEntity: '&#x2501;' },
  { char: '┃', name: 'box drawings heavy vertical', category: 'box', codepoint: 'U+2503', htmlEntity: '&#x2503;' },
  { char: '┏', name: 'box drawings heavy down and right', category: 'box', codepoint: 'U+250F', htmlEntity: '&#x250F;' },
  { char: '┓', name: 'box drawings heavy down and left', category: 'box', codepoint: 'U+2513', htmlEntity: '&#x2513;' },
  { char: '┗', name: 'box drawings heavy up and right', category: 'box', codepoint: 'U+2517', htmlEntity: '&#x2517;' },
  { char: '┛', name: 'box drawings heavy up and left', category: 'box', codepoint: 'U+251B', htmlEntity: '&#x251B;' },
  { char: '┣', name: 'box drawings heavy vertical and right', category: 'box', codepoint: 'U+2523', htmlEntity: '&#x2523;' },
  { char: '┫', name: 'box drawings heavy vertical and left', category: 'box', codepoint: 'U+252B', htmlEntity: '&#x252B;' },
  { char: '┳', name: 'box drawings heavy down and horizontal', category: 'box', codepoint: 'U+2533', htmlEntity: '&#x2533;' },
  { char: '┻', name: 'box drawings heavy up and horizontal', category: 'box', codepoint: 'U+253B', htmlEntity: '&#x253B;' },
  { char: '╋', name: 'box drawings heavy vertical and horizontal', category: 'box', codepoint: 'U+254B', htmlEntity: '&#x254B;' },
  { char: '═', name: 'box drawings double horizontal', category: 'box', codepoint: 'U+2550', htmlEntity: '&boxH;' },
  { char: '║', name: 'box drawings double vertical', category: 'box', codepoint: 'U+2551', htmlEntity: '&boxV;' },
  { char: '╔', name: 'box drawings double down and right', category: 'box', codepoint: 'U+2554', htmlEntity: '&boxDR;' },
  { char: '╗', name: 'box drawings double down and left', category: 'box', codepoint: 'U+2557', htmlEntity: '&boxDL;' },
  { char: '╚', name: 'box drawings double up and right', category: 'box', codepoint: 'U+255A', htmlEntity: '&boxUR;' },
  { char: '╝', name: 'box drawings double up and left', category: 'box', codepoint: 'U+255D', htmlEntity: '&boxUL;' },
  { char: '╠', name: 'box drawings double vertical and right', category: 'box', codepoint: 'U+2560', htmlEntity: '&boxVR;' },
  { char: '╣', name: 'box drawings double vertical and left', category: 'box', codepoint: 'U+2563', htmlEntity: '&boxVL;' },
  { char: '╦', name: 'box drawings double down and horizontal', category: 'box', codepoint: 'U+2566', htmlEntity: '&boxHD;' },
  { char: '╩', name: 'box drawings double up and horizontal', category: 'box', codepoint: 'U+2569', htmlEntity: '&boxHU;' },
  { char: '╬', name: 'box drawings double vertical and horizontal', category: 'box', codepoint: 'U+256C', htmlEntity: '&boxVH;' },
  { char: '┄', name: 'box drawings light triple dash horizontal', category: 'box', codepoint: 'U+2504', htmlEntity: '&#x2504;' },
  { char: '┈', name: 'box drawings light quadruple dash horizontal', category: 'box', codepoint: 'U+2508', htmlEntity: '&#x2508;' },
  { char: '┊', name: 'box drawings light quadruple dash vertical', category: 'box', codepoint: 'U+250A', htmlEntity: '&#x250A;' },
  { char: '╭', name: 'box drawings light arc down and right', category: 'box', codepoint: 'U+256D', htmlEntity: '&#x256D;' },
  { char: '╮', name: 'box drawings light arc down and left', category: 'box', codepoint: 'U+256E', htmlEntity: '&#x256E;' },
  { char: '╯', name: 'box drawings light arc up and left', category: 'box', codepoint: 'U+256F', htmlEntity: '&#x256F;' },
  { char: '╰', name: 'box drawings light arc up and right', category: 'box', codepoint: 'U+2570', htmlEntity: '&#x2570;' },
  { char: '╱', name: 'box drawings light diagonal upper right to lower left', category: 'box', codepoint: 'U+2571', htmlEntity: '&#x2571;' },
  { char: '╲', name: 'box drawings light diagonal upper left to lower right', category: 'box', codepoint: 'U+2572', htmlEntity: '&#x2572;' },
  { char: '╳', name: 'box drawings light diagonal cross', category: 'box', codepoint: 'U+2573', htmlEntity: '&#x2573;' },
  { char: '▀', name: 'upper half block', category: 'box', codepoint: 'U+2580', htmlEntity: '&uhblk;' },
  { char: '▄', name: 'lower half block', category: 'box', codepoint: 'U+2584', htmlEntity: '&lhblk;' },
  { char: '█', name: 'full block', category: 'box', codepoint: 'U+2588', htmlEntity: '&block;' },
  { char: '▌', name: 'left half block', category: 'box', codepoint: 'U+258C', htmlEntity: '&#x258C;' },
  { char: '▐', name: 'right half block', category: 'box', codepoint: 'U+2590', htmlEntity: '&#x2590;' },
  { char: '░', name: 'light shade', category: 'box', codepoint: 'U+2591', htmlEntity: '&blk14;' },
  { char: '▒', name: 'medium shade', category: 'box', codepoint: 'U+2592', htmlEntity: '&blk12;' },
  { char: '▓', name: 'dark shade', category: 'box', codepoint: 'U+2593', htmlEntity: '&blk34;' },
  { char: '⁰', name: 'superscript zero', category: 'superscript', codepoint: 'U+2070', htmlEntity: '&#x2070;' },
  { char: '¹', name: 'superscript one', category: 'superscript', codepoint: 'U+00B9', htmlEntity: '&sup1;' },
  { char: '²', name: 'superscript two', category: 'superscript', codepoint: 'U+00B2', htmlEntity: '&sup2;' },
  { char: '³', name: 'superscript three', category: 'superscript', codepoint: 'U+00B3', htmlEntity: '&sup3;' },
  { char: '⁴', name: 'superscript four', category: 'superscript', codepoint: 'U+2074', htmlEntity: '&#x2074;' },
  { char: '⁵', name: 'superscript five', category: 'superscript', codepoint: 'U+2075', htmlEntity: '&#x2075;' },
  { char: '⁶', name: 'superscript six', category: 'superscript', codepoint: 'U+2076', htmlEntity: '&#x2076;' },
  { char: '⁷', name: 'superscript seven', category: 'superscript', codepoint: 'U+2077', htmlEntity: '&#x2077;' },
  { char: '⁸', name: 'superscript eight', category: 'superscript', codepoint: 'U+2078', htmlEntity: '&#x2078;' },
  { char: '⁹', name: 'superscript nine', category: 'superscript', codepoint: 'U+2079', htmlEntity: '&#x2079;' },
  { char: '⁺', name: 'superscript plus sign', category: 'superscript', codepoint: 'U+207A', htmlEntity: '&#x207A;' },
  { char: '⁻', name: 'superscript minus', category: 'superscript', codepoint: 'U+207B', htmlEntity: '&#x207B;' },
  { char: '⁼', name: 'superscript equals sign', category: 'superscript', codepoint: 'U+207C', htmlEntity: '&#x207C;' },
  { char: '⁽', name: 'superscript left parenthesis', category: 'superscript', codepoint: 'U+207D', htmlEntity: '&#x207D;' },
  { char: '⁾', name: 'superscript right parenthesis', category: 'superscript', codepoint: 'U+207E', htmlEntity: '&#x207E;' },
  { char: 'ⁿ', name: 'superscript latin small letter n', category: 'superscript', codepoint: 'U+207F', htmlEntity: '&#x207F;' },
  { char: '₀', name: 'subscript zero', category: 'superscript', codepoint: 'U+2080', htmlEntity: '&#x2080;' },
  { char: '₁', name: 'subscript one', category: 'superscript', codepoint: 'U+2081', htmlEntity: '&#x2081;' },
  { char: '₂', name: 'subscript two', category: 'superscript', codepoint: 'U+2082', htmlEntity: '&#x2082;' },
  { char: '₃', name: 'subscript three', category: 'superscript', codepoint: 'U+2083', htmlEntity: '&#x2083;' },
  { char: '₄', name: 'subscript four', category: 'superscript', codepoint: 'U+2084', htmlEntity: '&#x2084;' },
  { char: '₅', name: 'subscript five', category: 'superscript', codepoint: 'U+2085', htmlEntity: '&#x2085;' },
  { char: '₆', name: 'subscript six', category: 'superscript', codepoint: 'U+2086', htmlEntity: '&#x2086;' },
  { char: '₇', name: 'subscript seven', category: 'superscript', codepoint: 'U+2087', htmlEntity: '&#x2087;' },
  { char: '₈', name: 'subscript eight', category: 'superscript', codepoint: 'U+2088', htmlEntity: '&#x2088;' },
  { char: '₉', name: 'subscript nine', category: 'superscript', codepoint: 'U+2089', htmlEntity: '&#x2089;' },
  { char: '₊', name: 'subscript plus sign', category: 'superscript', codepoint: 'U+208A', htmlEntity: '&#x208A;' },
  { char: '₋', name: 'subscript minus', category: 'superscript', codepoint: 'U+208B', htmlEntity: '&#x208B;' },
  { char: '₌', name: 'subscript equals sign', category: 'superscript', codepoint: 'U+208C', htmlEntity: '&#x208C;' },
  { char: '₍', name: 'subscript left parenthesis', category: 'superscript', codepoint: 'U+208D', htmlEntity: '&#x208D;' },
  { char: '₎', name: 'subscript right parenthesis', category: 'superscript', codepoint: 'U+208E', htmlEntity: '&#x208E;' },
  { char: 'ₐ', name: 'latin subscript small letter a', category: 'superscript', codepoint: 'U+2090', htmlEntity: '&#x2090;' },
  { char: 'ₑ', name: 'latin subscript small letter e', category: 'superscript', codepoint: 'U+2091', htmlEntity: '&#x2091;' },
  { char: 'ₒ', name: 'latin subscript small letter o', category: 'superscript', codepoint: 'U+2092', htmlEntity: '&#x2092;' },
  { char: 'ₓ', name: 'latin subscript small letter x', category: 'superscript', codepoint: 'U+2093', htmlEntity: '&#x2093;' },
  { char: '✓', name: 'check mark', category: 'symbols', codepoint: 'U+2713', htmlEntity: '&check;' },
  { char: '✔', name: 'heavy check mark', category: 'symbols', codepoint: 'U+2714', htmlEntity: '&#x2714;' },
  { char: '✕', name: 'multiplication x', category: 'symbols', codepoint: 'U+2715', htmlEntity: '&#x2715;' },
  { char: '✖', name: 'heavy multiplication x', category: 'symbols', codepoint: 'U+2716', htmlEntity: '&#x2716;' },
  { char: '✗', name: 'ballot x', category: 'symbols', codepoint: 'U+2717', htmlEntity: '&cross;' },
  { char: '✘', name: 'heavy ballot x', category: 'symbols', codepoint: 'U+2718', htmlEntity: '&#x2718;' },
  { char: '☐', name: 'ballot box', category: 'symbols', codepoint: 'U+2610', htmlEntity: '&#x2610;' },
  { char: '☑', name: 'ballot box with check', category: 'symbols', codepoint: 'U+2611', htmlEntity: '&#x2611;' },
  { char: '☒', name: 'ballot box with x', category: 'symbols', codepoint: 'U+2612', htmlEntity: '&#x2612;' },
  { char: '★', name: 'black star', category: 'symbols', codepoint: 'U+2605', htmlEntity: '&bigstar;' },
  { char: '☆', name: 'white star', category: 'symbols', codepoint: 'U+2606', htmlEntity: '&star;' },
  { char: '✦', name: 'black four pointed star', category: 'symbols', codepoint: 'U+2726', htmlEntity: '&#x2726;' },
  { char: '✧', name: 'white four pointed star', category: 'symbols', codepoint: 'U+2727', htmlEntity: '&#x2727;' },
  { char: '✩', name: 'stress outlined white star', category: 'symbols', codepoint: 'U+2729', htmlEntity: '&#x2729;' },
  { char: '✪', name: 'circled white star', category: 'symbols', codepoint: 'U+272A', htmlEntity: '&#x272A;' },
  { char: '✴', name: 'eight pointed black star', category: 'symbols', codepoint: 'U+2734', htmlEntity: '&#x2734;' },
  { char: '✵', name: 'eight pointed pinwheel star', category: 'symbols', codepoint: 'U+2735', htmlEntity: '&#x2735;' },
  { char: '✶', name: 'six pointed black star', category: 'symbols', codepoint: 'U+2736', htmlEntity: '&sext;' },
  { char: '✹', name: 'twelve pointed black star', category: 'symbols', codepoint: 'U+2739', htmlEntity: '&#x2739;' },
  { char: '✻', name: 'teardrop-spoked asterisk', category: 'symbols', codepoint: 'U+273B', htmlEntity: '&#x273B;' },
  { char: '✽', name: 'heavy teardrop-spoked asterisk', category: 'symbols', codepoint: 'U+273D', htmlEntity: '&#x273D;' },
  { char: '■', name: 'black square', category: 'symbols', codepoint: 'U+25A0', htmlEntity: '&#x25A0;' },
  { char: '□', name: 'white square', category: 'symbols', codepoint: 'U+25A1', htmlEntity: '&square;' },
  { char: '▪', name: 'black small square', category: 'symbols', codepoint: 'U+25AA', htmlEntity: '&blacksquare;' },
  { char: '▫', name: 'white small square', category: 'symbols', codepoint: 'U+25AB', htmlEntity: '&EmptyVerySmallSquare;' },
  { char: '▲', name: 'black up-pointing triangle', category: 'symbols', codepoint: 'U+25B2', htmlEntity: '&#x25B2;' },
  { char: '△', name: 'white up-pointing triangle', category: 'symbols', codepoint: 'U+25B3', htmlEntity: '&bigtriangleup;' },
  { char: '▼', name: 'black down-pointing triangle', category: 'symbols', codepoint: 'U+25BC', htmlEntity: '&#x25BC;' },
  { char: '▽', name: 'white down-pointing triangle', category: 'symbols', codepoint: 'U+25BD', htmlEntity: '&bigtriangledown;' },
  { char: '▶', name: 'black right-pointing triangle', category: 'symbols', codepoint: 'U+25B6', htmlEntity: '&#x25B6;' },
  { char: '◀', name: 'black left-pointing triangle', category: 'symbols', codepoint: 'U+25C0', htmlEntity: '&#x25C0;' },
  { char: '◆', name: 'black diamond', category: 'symbols', codepoint: 'U+25C6', htmlEntity: '&#x25C6;' },
  { char: '◇', name: 'white diamond', category: 'symbols', codepoint: 'U+25C7', htmlEntity: '&#x25C7;' },
  { char: '○', name: 'white circle', category: 'symbols', codepoint: 'U+25CB', htmlEntity: '&cir;' },
  { char: '◎', name: 'bullseye', category: 'symbols', codepoint: 'U+25CE', htmlEntity: '&#x25CE;' },
  { char: '●', name: 'black circle', category: 'symbols', codepoint: 'U+25CF', htmlEntity: '&#x25CF;' },
  { char: '◉', name: 'fisheye', category: 'symbols', codepoint: 'U+25C9', htmlEntity: '&#x25C9;' },
  { char: '◐', name: 'circle with left half black', category: 'symbols', codepoint: 'U+25D0', htmlEntity: '&#x25D0;' },
  { char: '◑', name: 'circle with right half black', category: 'symbols', codepoint: 'U+25D1', htmlEntity: '&#x25D1;' },
  { char: '♠', name: 'black spade suit', category: 'symbols', codepoint: 'U+2660', htmlEntity: '&spades;' },
  { char: '♡', name: 'white heart suit', category: 'symbols', codepoint: 'U+2661', htmlEntity: '&#x2661;' },
  { char: '♢', name: 'white diamond suit', category: 'symbols', codepoint: 'U+2662', htmlEntity: '&#x2662;' },
  { char: '♣', name: 'black club suit', category: 'symbols', codepoint: 'U+2663', htmlEntity: '&clubs;' },
  { char: '♤', name: 'white spade suit', category: 'symbols', codepoint: 'U+2664', htmlEntity: '&#x2664;' },
  { char: '♥', name: 'black heart suit', category: 'symbols', codepoint: 'U+2665', htmlEntity: '&hearts;' },
  { char: '♦', name: 'black diamond suit', category: 'symbols', codepoint: 'U+2666', htmlEntity: '&diamondsuit;' },
  { char: '♧', name: 'white club suit', category: 'symbols', codepoint: 'U+2667', htmlEntity: '&#x2667;' },
  { char: '☛', name: 'black right pointing index', category: 'symbols', codepoint: 'U+261B', htmlEntity: '&#x261B;' },
  { char: '☞', name: 'white right pointing index', category: 'symbols', codepoint: 'U+261E', htmlEntity: '&#x261E;' },
  { char: '❖', name: 'black diamond minus white x', category: 'symbols', codepoint: 'U+2756', htmlEntity: '&#x2756;' },
  { char: '❥', name: 'rotated heavy black heart bullet', category: 'symbols', codepoint: 'U+2765', htmlEntity: '&#x2765;' },
  { char: '©', name: 'copyright sign', category: 'legal', codepoint: 'U+00A9', htmlEntity: '&copy;' },
  { char: '®', name: 'registered sign', category: 'legal', codepoint: 'U+00AE', htmlEntity: '&circledR;' },
  { char: '™', name: 'trade mark sign', category: 'legal', codepoint: 'U+2122', htmlEntity: '&trade;' },
  { char: '℗', name: 'sound recording copyright', category: 'legal', codepoint: 'U+2117', htmlEntity: '&copysr;' },
  { char: '℠', name: 'service mark', category: 'legal', codepoint: 'U+2120', htmlEntity: '&#x2120;' },
  { char: '§', name: 'section sign', category: 'legal', codepoint: 'U+00A7', htmlEntity: '&sect;' },
  { char: '¶', name: 'pilcrow sign', category: 'legal', codepoint: 'U+00B6', htmlEntity: '&para;' },
  { char: '℮', name: 'estimated symbol', category: 'legal', codepoint: 'U+212E', htmlEntity: '&#x212E;' },
  { char: '№', name: 'numero sign', category: 'legal', codepoint: 'U+2116', htmlEntity: '&numero;' },
  { char: '\u00A0', name: 'no-break space', category: 'invisible', codepoint: 'U+00A0', htmlEntity: '&nbsp;' },
  { char: '\u2002', name: 'en space', category: 'invisible', codepoint: 'U+2002', htmlEntity: '&ensp;' },
  { char: '\u2003', name: 'em space', category: 'invisible', codepoint: 'U+2003', htmlEntity: '&emsp;' },
  { char: '\u2004', name: 'three-per-em space', category: 'invisible', codepoint: 'U+2004', htmlEntity: '&emsp13;' },
  { char: '\u2005', name: 'four-per-em space', category: 'invisible', codepoint: 'U+2005', htmlEntity: '&emsp14;' },
  { char: '\u2007', name: 'figure space', category: 'invisible', codepoint: 'U+2007', htmlEntity: '&numsp;' },
  { char: '\u2008', name: 'punctuation space', category: 'invisible', codepoint: 'U+2008', htmlEntity: '&puncsp;' },
  { char: '\u2009', name: 'thin space', category: 'invisible', codepoint: 'U+2009', htmlEntity: '&ThinSpace;' },
  { char: '\u200A', name: 'hair space', category: 'invisible', codepoint: 'U+200A', htmlEntity: '&hairsp;' },
  { char: '\u202F', name: 'narrow no-break space', category: 'invisible', codepoint: 'U+202F', htmlEntity: '&#x202F;' },
  { char: '\u00AD', name: 'soft hyphen', category: 'invisible', codepoint: 'U+00AD', htmlEntity: '&shy;' },
  { char: '\u200B', name: 'zero width space', category: 'invisible', codepoint: 'U+200B', htmlEntity: '&NegativeMediumSpace;' },
  { char: '\u200C', name: 'zero width non-joiner', category: 'invisible', codepoint: 'U+200C', htmlEntity: '&zwnj;' },
  { char: '\u200D', name: 'zero width joiner', category: 'invisible', codepoint: 'U+200D', htmlEntity: '&zwj;' },
  { char: '\u2060', name: 'word joiner', category: 'invisible', codepoint: 'U+2060', htmlEntity: '&NoBreak;' },
  { char: '\uFEFF', name: 'zero width no-break space', category: 'invisible', codepoint: 'U+FEFF', htmlEntity: '&#xFEFF;' },
];
