import { describe, expect, it } from 'vitest';
import {
  canonicalToken,
  displayKeycode,
  parseKeymap,
  positionLabel,
  run,
  splitTopLevel,
  stripComments,
  SEPARATOR,
  type OryxOpts,
} from './index';
import { MOONLANDER_POSITIONS } from './data';

/* ------------------------------------------------------------------ *
 * Fixtures: two small but real Moonlander keymap.c files
 * ------------------------------------------------------------------ */

/** A realistic Moonlander base layer, 72 tokens in LAYOUT order. */
const BASE: string[] = [
  // Row 1: left seven, then right seven.
  'KC_EQUAL', 'KC_1', 'KC_2', 'KC_3', 'KC_4', 'KC_5', 'KC_LEFT',
  'KC_RIGHT', 'KC_6', 'KC_7', 'KC_8', 'KC_9', 'KC_0', 'KC_MINUS',
  // Row 2.
  'KC_DELETE', 'KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_LBRC',
  'KC_RBRC', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_BSLS',
  // Row 3.
  'KC_BSPC', 'KC_A', 'KC_S', 'KC_D', 'KC_F', 'KC_G', 'KC_LGUI',
  'MT(MOD_LSFT, KC_ESCAPE)', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOTE',
  // Row 4: six keys per hand.
  'KC_LSFT', 'KC_Z', 'KC_X', 'KC_C', 'KC_V', 'KC_B',
  'KC_N', 'KC_M', 'KC_COMMA', 'KC_DOT', 'KC_SLASH', 'KC_RSFT',
  // Row 5 left, five keys.
  'KC_LCTL', 'KC_GRAVE', 'KC_LALT', 'KC_HOME', 'KC_END',
  // The two large thumb keys.
  'LT(1, KC_SPACE)',
  'MO(1)',
  // Row 5 right, five keys.
  'KC_UP', 'KC_DOWN', 'KC_PGUP', 'KC_PGDN', 'KC_RGUI',
  // Left thumb cluster, then right thumb cluster.
  'KC_TAB', 'KC_CAPS', 'KC_ENTER',
  'KC_BSPC', 'KC_DELETE', 'RGB_TOG',
];

function filled(value: string): string[] {
  return Array.from({ length: 72 }, () => value);
}

function withChanges(base: string[], changes: Record<number, string>): string[] {
  const copy = [...base];
  for (const [index, token] of Object.entries(changes)) copy[Number(index)] = token;
  return copy;
}

interface FixtureLayer {
  key: string;
  tokens: string[];
}

/** Build a keymap.c the way the Download Source zip writes one. */
function keymapFile(layerNames: string[], layers: FixtureLayer[], macro = 'LAYOUT_moonlander'): string {
  const head = [
    '/* Generated by the fixture builder. Oryx\'s own header looks like this. */',
    '#include QMK_KEYBOARD_H',
    '',
  ];
  if (layerNames.length > 0) {
    head.push('enum layers {');
    for (const name of layerNames) head.push(`    ${name}, // layer ${name}`);
    head.push('};');
    head.push('');
  }
  head.push('const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {');
  const body = layers.map(
    (layer) => `  [${layer.key}] = ${macro}(\n    ${layer.tokens.join(',\n    ')}\n  ),`,
  );
  return [...head, ...body, '};', ''].join('\n');
}

const SYM_A = withChanges(filled('_______'), {
  1: 'KC_EXLM',
  2: 'KC_AT',
  35: 'KC_HASH',
});

// Side B writes the long transparent spelling, which must not read as a change.
const SYM_B = withChanges(filled('KC_TRANSPARENT'), {
  1: 'KC_EXLM',
  2: 'KC_AT',
  35: 'KC_DLR',
});

const BASE_B = withChanges(BASE, {
  2: 'KC_F2',
  35: 'MT(MOD_LCTL, KC_ESCAPE)',
  // KC_ENTER leaves the left thumb cluster and lands on the right large thumb.
  60: 'KC_ENTER',
  68: 'KC_LGUI',
});

const SIDE_A = keymapFile(
  ['BASE', 'SYM'],
  [
    { key: 'BASE', tokens: BASE },
    { key: 'SYM', tokens: SYM_A },
  ],
);

const SIDE_B = keymapFile(
  ['BASE', 'SYM', 'NAV'],
  [
    { key: 'BASE', tokens: BASE_B },
    { key: 'SYM', tokens: SYM_B },
    { key: 'NAV', tokens: filled('KC_NO') },
  ],
);

const both = `${SIDE_A}\n${SEPARATOR}\n${SIDE_B}`;

const OPTS: OryxOpts = { showUnchanged: false, format: 'report' };
const opts = (over: Partial<OryxOpts> = {}): OryxOpts => ({ ...OPTS, ...over });

/* ------------------------------------------------------------------ *
 * Lexing
 * ------------------------------------------------------------------ */

describe('stripComments', () => {
  it('removes line and block comments', () => {
    expect(stripComments('KC_A, // KC_ZZZ\nKC_B')).not.toContain('KC_ZZZ');
    expect(stripComments('KC_A, /* KC_ZZZ */ KC_B')).not.toContain('KC_ZZZ');
    expect(stripComments('KC_A, /* KC_ZZZ */ KC_B')).toContain('KC_B');
  });

  it('leaves string literals alone', () => {
    expect(stripComments('SEND_STRING("http://example.com")')).toContain('http://example.com');
  });
});

describe('splitTopLevel', () => {
  it('splits on depth zero commas only', () => {
    expect(splitTopLevel('KC_A, LT(1, KC_SPC), MT(MOD_LSFT, KC_Z)')).toEqual([
      'KC_A',
      'LT(1, KC_SPC)',
      'MT(MOD_LSFT, KC_Z)',
    ]);
  });

  it('drops the token a trailing comma would create', () => {
    expect(splitTopLevel('KC_A, KC_B,')).toEqual(['KC_A', 'KC_B']);
  });
});

/* ------------------------------------------------------------------ *
 * Parsing
 * ------------------------------------------------------------------ */

describe('parseKeymap', () => {
  it('reads the layer count, the enum names and 72 tokens per layer', () => {
    const parsed = parseKeymap(SIDE_A, 'A');
    expect(parsed.layers).toHaveLength(2);
    expect(parsed.layers.map((layer) => layer.name)).toEqual(['BASE', 'SYM']);
    expect(parsed.layers[0].tokens).toHaveLength(72);
    expect(parsed.layers[0].tokens[35]).toBe('MT(MOD_LSFT, KC_ESCAPE)');
    expect(parsed.warnings).toEqual([]);
  });

  it('falls back to L0, L1 names when there is no layers enum', () => {
    // What Oryx actually exports: numeric layer keys and a custom_keycodes
    // enum, which must never be mistaken for a layers enum.
    const file =
      'enum custom_keycodes {\n  RGB_SLD = ML_SAFE_RANGE,\n  ST_MACRO_0,\n};\n\n' +
      keymapFile([], [{ key: '0', tokens: BASE }, { key: '1', tokens: SYM_A }], 'LAYOUT');
    const parsed = parseKeymap(file, 'A');
    expect(parsed.layers.map((layer) => layer.name)).toEqual(['L0', 'L1']);
    expect(parsed.layerNames).toEqual([]);
  });

  it('ignores keycodes hidden in comments', () => {
    const parsed = parseKeymap(SIDE_A, 'A');
    expect(parsed.layers[0].tokens.every((token) => !token.includes('layer'))).toBe(true);
  });

  it('warns and names the count when a layer is not 72 keys', () => {
    const short = BASE.slice(0, 71);
    const file = keymapFile(['BASE'], [{ key: 'BASE', tokens: short }]);
    const parsed = parseKeymap(file, 'A');
    expect(parsed.layers[0].tokens).toHaveLength(71);
    expect(parsed.warnings).toHaveLength(1);
    expect(parsed.warnings[0]).toContain('71 keycodes');
    expect(parsed.warnings[0]).toContain('Voyager');
  });
});

describe('canonicalToken', () => {
  it('collapses the transparent and none aliases', () => {
    expect(canonicalToken('_______')).toBe(canonicalToken('KC_TRANSPARENT'));
    expect(canonicalToken('KC_TRNS')).toBe(canonicalToken('KC_TRANSPARENT'));
    expect(canonicalToken('XXXXXXX')).toBe(canonicalToken('KC_NO'));
  });

  it('ignores whitespace inside nested calls', () => {
    expect(canonicalToken('LT(1, KC_SPC)')).toBe(canonicalToken('LT(1,KC_SPC)'));
  });
});

/* ------------------------------------------------------------------ *
 * Keycode display names
 * ------------------------------------------------------------------ */

describe('displayKeycode', () => {
  it('normalises plain keycodes', () => {
    expect(displayKeycode('KC_A')).toBe('A');
    expect(displayKeycode('KC_F7')).toBe('F7');
    expect(displayKeycode('KC_LSFT')).toBe('LShift');
    expect(displayKeycode('KC_SPACE')).toBe('Space');
    expect(displayKeycode('_______')).toBe('transparent');
    expect(displayKeycode('KC_TRANSPARENT')).toBe('transparent');
    expect(displayKeycode('XXXXXXX')).toBe('none');
    expect(displayKeycode('KC_NO')).toBe('none');
  });

  it('normalises layer taps and mod taps', () => {
    expect(displayKeycode('LT(1,KC_SPC)')).toBe('LT L1 / Space');
    expect(displayKeycode('LT(1, KC_SPC)', ['BASE', 'SYM'])).toBe('LT SYM / Space');
    expect(displayKeycode('MT(MOD_LSFT, KC_ESC)')).toBe('Shift-tap / Esc');
    expect(displayKeycode('LCTL_T(KC_A)')).toBe('Ctrl-tap / A');
  });

  it('names layer switches with the enum names', () => {
    const names = ['BASE', 'SYM', 'NAV'];
    expect(displayKeycode('MO(2)', names)).toBe('MO NAV');
    expect(displayKeycode('TO(0)', names)).toBe('TO BASE');
    expect(displayKeycode('TG(1)', names)).toBe('TG SYM');
    expect(displayKeycode('OSL(1)', names)).toBe('OSL SYM');
    expect(displayKeycode('MO(2)')).toBe('MO L2');
  });

  it('handles tap dance, one shot mods, wrappers and media keys', () => {
    expect(displayKeycode('TD(DANCE_0)')).toBe('Tap dance DANCE_0');
    expect(displayKeycode('OSM(MOD_LSFT)')).toBe('One-shot Shift');
    expect(displayKeycode('LSFT(KC_9)')).toBe('Shift+9');
    expect(displayKeycode('KC_MPLY')).toBe('Play/Pause');
    expect(displayKeycode('RGB_VAI')).toBe('RGB bright up');
    expect(displayKeycode('TOGGLE_LAYER_COLOR')).toBe('Toggle layer color');
  });

  it('shows unknown custom keycodes verbatim', () => {
    expect(displayKeycode('ST_MACRO_0')).toBe('ST_MACRO_0');
  });
});

/* ------------------------------------------------------------------ *
 * Geometry data integrity
 * ------------------------------------------------------------------ */

describe('MOONLANDER_POSITIONS', () => {
  it('has exactly 72 entries with unique indices in order', () => {
    expect(MOONLANDER_POSITIONS).toHaveLength(72);
    const indices = MOONLANDER_POSITIONS.map((position) => position.index);
    expect(new Set(indices).size).toBe(72);
    expect(indices).toEqual(Array.from({ length: 72 }, (unused, i) => i));
  });

  it('splits into 64 main keys and 8 thumb keys, evenly per hand', () => {
    const main = MOONLANDER_POSITIONS.filter((position) => position.zone === 'main');
    const thumbs = MOONLANDER_POSITIONS.filter((position) => position.zone === 'thumb');
    expect(main).toHaveLength(64);
    expect(thumbs).toHaveLength(8);
    expect(MOONLANDER_POSITIONS.filter((position) => position.hand === 'left')).toHaveLength(36);
    expect(MOONLANDER_POSITIONS.filter((position) => position.hand === 'right')).toHaveLength(36);
  });

  it('labels the positions the report quotes', () => {
    expect(positionLabel(2, 72)).toBe('Left hand, row 1, col 3 (ring)');
    expect(positionLabel(35, 72)).toBe('Right hand, row 3, col 7 (inner column)');
    expect(positionLabel(59, 72)).toBe('Left thumb 1 (large)');
    expect(positionLabel(60, 72)).toBe('Right thumb 1 (large)');
    expect(positionLabel(68, 72)).toBe('Left thumb 4');
    expect(positionLabel(5, 71)).toBe('Key 5');
  });
});

/* ------------------------------------------------------------------ *
 * The diff
 * ------------------------------------------------------------------ */

describe('run', () => {
  it('reports the layer counts and names on each side', () => {
    const out = run(both, opts());
    expect(out).toContain('Layout A: 2 layers (BASE, SYM)');
    expect(out).toContain('Layout B: 3 layers (BASE, SYM, NAV)');
    expect(out).toContain('Layers only in B: NAV');
    expect(out).toContain('Layers only in A: none');
    expect(out).toContain('Layers matched by name.');
  });

  it('finds exactly the planted changes with their physical positions', () => {
    const out = run(both, opts());
    expect(out).toContain('Layer BASE: 4 changed keys, 68 unchanged');
    expect(out).toMatch(/Left hand, row 1, col 3 \(ring\)\s+2 -> F2/);
    expect(out).toMatch(
      /Right hand, row 3, col 7 \(inner column\)\s+Shift-tap \/ Esc -> Ctrl-tap \/ Esc/,
    );
    expect(out).toMatch(/Right thumb 1 \(large\)\s+MO SYM -> Enter/);
    expect(out).toMatch(/Left thumb 4\s+Enter -> LGui/);
    expect(out).toContain('Total changed keys: 5');
    expect(out).toContain('    BASE: 4');
    expect(out).toContain('    SYM: 1');
  });

  it('treats _______ and KC_TRANSPARENT as the same binding', () => {
    const out = run(both, opts());
    // The SYM layer differs at one key only; the 69 transparent keys that
    // changed spelling must not show up.
    expect(out).toContain('Layer SYM: 1 changed key, 71 unchanged');
    expect(out).not.toContain('transparent -> transparent');
  });

  it('detects a binding that moved to another position on the same layer', () => {
    const out = run(both, opts());
    expect(out).toContain('Moved bindings:');
    expect(out).toContain('Enter: Left thumb 4 -> Right thumb 1 (large) (layer BASE)');
  });

  it('says when there are no moves', () => {
    const a = keymapFile(['BASE'], [{ key: 'BASE', tokens: BASE }]);
    const b = keymapFile(['BASE'], [{ key: 'BASE', tokens: withChanges(BASE, { 2: 'KC_F2' }) }]);
    const out = run(`${a}\n${SEPARATOR}\n${b}`, opts());
    expect(out).toContain('Moved bindings: none');
  });

  it('calls out a layer that only exists on side B', () => {
    const out = run(both, opts());
    expect(out).toContain('Layer NAV: only in layout B, 72 keys, nothing to compare it against.');
  });

  it('calls out a layer that only exists on side A', () => {
    const a = keymapFile(
      ['BASE', 'SYM'],
      [
        { key: 'BASE', tokens: BASE },
        { key: 'SYM', tokens: SYM_A },
      ],
    );
    const b = keymapFile(['BASE'], [{ key: 'BASE', tokens: BASE }]);
    const out = run(`${a}\n${SEPARATOR}\n${b}`, opts());
    expect(out).toContain('Layer SYM: only in layout A, 72 keys, nothing to compare it against.');
  });

  it('reports no changes when the two files are identical', () => {
    const out = run(`${SIDE_A}\n${SEPARATOR}\n${SIDE_A}`, opts());
    expect(out).toContain('Layer BASE: no changes, 72 keys identical');
    expect(out).toContain('Total changed keys: 0');
  });

  it('matches by file order and says so when no layer names line up', () => {
    const a = keymapFile(['ALPHA'], [{ key: 'ALPHA', tokens: BASE }]);
    const b = keymapFile(['QWERTY'], [{ key: 'QWERTY', tokens: withChanges(BASE, { 2: 'KC_F2' }) }]);
    const out = run(`${a}\n${SEPARATOR}\n${b}`, opts());
    expect(out).toContain('matched by their order in the file');
    expect(out).toContain('Layer ALPHA vs QWERTY: 1 changed key');
  });

  it('surfaces the short layer warning and falls back to key indices', () => {
    const short = BASE.slice(0, 71);
    const a = keymapFile(['BASE'], [{ key: 'BASE', tokens: short }]);
    const b = keymapFile(['BASE'], [{ key: 'BASE', tokens: withChanges(short, { 2: 'KC_F2' }) }]);
    const out = run(`${a}\n${SEPARATOR}\n${b}`, opts());
    expect(out).toContain('Warnings');
    expect(out).toContain('71 keycodes');
    expect(out).toMatch(/Key 2\s+2 -> F2/);
  });

  it('lists every key when showUnchanged is on', () => {
    const out = run(both, opts({ showUnchanged: true }));
    const baseSection = out.slice(out.indexOf('Layer BASE:'), out.indexOf('Layer SYM:'));
    const keyLines = baseSection.split('\n').filter((line) => /^ {2}[* ] /.test(line));
    expect(keyLines).toHaveLength(72);
    expect(baseSection).toContain('* ');
    expect(baseSection).toMatch(/ {2} {2}Left hand, row 1, col 1 \(pinky outer\)\s+=/);
  });

  it('emits csv with a header and quoted positions', () => {
    const out = run(both, opts({ format: 'csv' }));
    const lines = out.split('\n');
    expect(lines[0]).toBe('position,layer,old,new');
    expect(lines).toContain('"Left hand, row 1, col 3 (ring)",BASE,2,F2');
    expect(lines).toContain('Right thumb 1 (large),BASE,MO SYM,Enter');
    // Four changed keys on BASE plus one on SYM, plus the header.
    expect(lines).toHaveLength(6);
  });
});

/* ------------------------------------------------------------------ *
 * Errors
 * ------------------------------------------------------------------ */

describe('run errors', () => {
  it('throws on empty input', () => {
    expect(() => run('', opts())).toThrowError(/Nothing to compare/);
    expect(() => run('   \n  ', opts())).toThrowError(/Nothing to compare/);
  });

  it('throws when the ===== separator is missing', () => {
    expect(() => run(SIDE_A, opts())).toThrowError(/separator/);
  });

  it('throws when only one side was pasted', () => {
    expect(() => run(`${SIDE_A}\n${SEPARATOR}\n`, opts())).toThrowError(/Only one keymap.c/);
    expect(() => run(`\n${SEPARATOR}\n${SIDE_B}`, opts())).toThrowError(/Only one keymap.c/);
  });

  it('throws when a side has no layer definitions', () => {
    const notAKeymap = 'enum layers { BASE, SYM };\nint main(void) { return 0; }\n';
    expect(() => run(`${notAKeymap}\n${SEPARATOR}\n${SIDE_B}`, opts())).toThrowError(
      /Layout A has no layer definitions/,
    );
  });

  it('throws on an unknown format', () => {
    expect(() => run(both, opts({ format: 'html' }))).toThrowError(/Unknown format/);
  });
});
