import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "minecraft-xp-calculator",
  icon: "Sparkles",
  name: "Minecraft XP Calculator",
  description:
    "Exact level-to-XP math, Mending repair costs, and kill counts, verified against decompiled game code.",
  category: "Minecraft",
  keywords: [
    "minecraft xp calculator",
    "minecraft level calculator",
    "minecraft xp to level 30",
    "minecraft mending xp cost",
    "minecraft xp per mob",
    "minecraft experience calculator",
    "xp bottle calculator",
  ],
  searchTerms: [
    "how much xp for level 30",
    "minecraft experience points",
    "xp farm math",
    "mending repair cost",
    "levels to xp",
    "minecraft level curve",
    "xp bottles needed",
    "diamond ore xp",
    "mob grinder levels",
    "enchanting level cost",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "levels",
      options: [
        {
          value: "levels",
          label: "Levels to XP",
          synonyms: ["level to xp", "between levels", "level cost", "kill planning", "xp needed"],
        },
        {
          value: "xp",
          label: "XP to level",
          synonyms: ["points to level", "total xp", "what level am i", "convert xp"],
        },
        {
          value: "mending",
          label: "Mending repair",
          synonyms: ["mending", "repair", "durability", "fix item", "unbreaking partner"],
        },
      ],
    },
    { kind: "number", id: "fromLevel", label: "Current level", default: 0, min: 0, max: 100000, step: 1 },
    { kind: "number", id: "toLevel", label: "Target level", default: 30, min: 0, max: 100000, step: 1 },
    {
      kind: "number",
      id: "totalXp",
      label: "Total XP points (XP to level mode)",
      default: 1395,
      min: 0,
      max: 2147483647,
      step: 1,
    },
    {
      kind: "number",
      id: "durability",
      label: "Durability to repair (Mending mode)",
      default: 1561,
      min: 0,
      max: 1000000,
      step: 1,
    },
    {
      kind: "select",
      id: "source",
      label: "XP source",
      default: "zombie",
      groups: [
        {
          label: "Hostile mobs",
          synonyms: ["mobs", "monsters", "hostile", "farm"],
          options: [
            { value: "zombie", label: "Zombie (5 XP)", synonyms: ["zombie", "husk", "zombie villager", "drowned"] },
            { value: "baby_zombie", label: "Baby zombie (12 XP)", synonyms: ["baby", "zombie baby"] },
            { value: "skeleton", label: "Skeleton (5 XP)", synonyms: ["skelly", "stray", "bogged"] },
            { value: "creeper", label: "Creeper (5 XP)", synonyms: ["creeper farm"] },
            { value: "spider", label: "Spider (5 XP)", synonyms: ["cave spider", "spider farm"] },
            { value: "enderman", label: "Enderman (5 XP)", synonyms: ["ender man", "enderman farm", "end farm"] },
            { value: "witch", label: "Witch (5 XP)", synonyms: ["witch farm"] },
            { value: "wither_skeleton", label: "Wither skeleton (5 XP)", synonyms: ["wither skelly", "nether fortress"] },
            { value: "blaze", label: "Blaze (10 XP)", synonyms: ["blaze farm", "blaze rod"] },
            { value: "guardian", label: "Guardian (10 XP)", synonyms: ["guardian farm", "elder guardian", "ocean monument"] },
            { value: "evoker", label: "Evoker (10 XP)", synonyms: ["raid", "totem of undying"] },
            { value: "breeze", label: "Breeze (10 XP)", synonyms: ["trial chamber", "breeze rod"] },
            { value: "warden", label: "Warden (5 XP)", synonyms: ["deep dark", "sculk shrieker"] },
            { value: "ravager", label: "Ravager (20 XP)", synonyms: ["raid", "beast"] },
            { value: "piglin_brute", label: "Piglin brute (20 XP)", synonyms: ["brute", "bastion"] },
            { value: "vex", label: "Vex (3 XP)", synonyms: ["evoker minion"] },
            { value: "slime_big", label: "Slime or magma cube, big (4 XP)", synonyms: ["slime", "magma cube", "large slime"] },
            { value: "slime_small", label: "Slime or magma cube, small (2 XP)", synonyms: ["medium slime"] },
            { value: "slime_tiny", label: "Slime or magma cube, tiny (1 XP)", synonyms: ["tiny slime", "baby slime"] },
          ],
        },
        {
          label: "Bosses",
          synonyms: ["boss", "dragon", "wither boss"],
          options: [
            { value: "wither", label: "Wither (50 XP)", synonyms: ["wither boss", "nether star"] },
            { value: "ender_dragon_first", label: "Ender dragon, first kill (12,000 XP)", synonyms: ["dragon", "end boss", "first dragon"] },
            { value: "ender_dragon_respawn", label: "Ender dragon, respawned (500 XP)", synonyms: ["respawned dragon", "dragon refight"] },
          ],
        },
        {
          label: "Animals",
          synonyms: ["passive", "farm animals", "breeding"],
          options: [
            { value: "adult_animal", label: "Adult animal (1 to 3 XP)", synonyms: ["cow", "pig", "sheep", "chicken", "animal farm"] },
            { value: "breeding", label: "Breeding two animals (1 to 7 XP)", synonyms: ["breed", "breeder", "love mode"] },
          ],
        },
        {
          label: "Bottles and blocks",
          synonyms: ["bottle", "spawner", "sculk", "blocks"],
          options: [
            { value: "xp_bottle", label: "Bottle o' Enchanting (3 to 11 XP)", synonyms: ["xp bottle", "experience bottle", "bottle of enchanting"] },
            { value: "spawner_block", label: "Breaking a monster spawner (15 to 43 XP)", synonyms: ["spawner", "mob spawner", "cage"] },
            { value: "sculk", label: "Sculk block (1 XP)", synonyms: ["sculk mining", "deep dark", "hoe"] },
          ],
        },
        {
          label: "Ore mining",
          synonyms: ["ore", "mining", "fortune", "silk touch"],
          options: [
            { value: "coal_ore", label: "Coal ore (0 to 2 XP)", synonyms: ["coal", "coal mining"] },
            { value: "nether_gold_ore", label: "Nether gold ore (0 to 1 XP)", synonyms: ["gold nugget ore", "nether gold"] },
            { value: "lapis_ore", label: "Lapis lazuli ore (2 to 5 XP)", synonyms: ["lapis", "lapis mining"] },
            { value: "nether_quartz_ore", label: "Nether quartz ore (2 to 5 XP)", synonyms: ["quartz", "quartz mining"] },
            { value: "redstone_ore", label: "Redstone ore (1 to 5 XP)", synonyms: ["redstone", "redstone mining"] },
            { value: "diamond_ore", label: "Diamond ore (3 to 7 XP)", synonyms: ["diamond", "diamond mining"] },
            { value: "emerald_ore", label: "Emerald ore (3 to 7 XP)", synonyms: ["emerald", "emerald mining"] },
          ],
        },
      ],
    },
  ],
  copy: {
    what: "Exact Minecraft XP math: convert levels to experience points and back, price a Mending repair in orb XP, and plan how many mob kills, XP bottles, or mined ore blocks a level climb costs. Every constant is reimplemented from decompiled, unobfuscated game code and checked across six releases from 1.16.5 through 26.2. Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.",
    how: "Pick a mode. Levels to XP takes a current and a target level and shows the total points at each, the gap between them, and how many of your chosen XP source cover it on average and in the worst case. XP to level converts a raw point total into a level with progress toward the next. Mending repair takes a durability deficit and prices it in orb XP, then in your chosen source. The settings live in the page address, so you can share an exact calculation as a link.",
    why: "Most Minecraft XP calculators copy each other's tables and never say which version they describe. The numbers here were verified against the game's own decompiled code, version by version: the level curve, mob rewards, bottle and ore drops, and the Mending ratio of 2 durability per point are identical in every release checked, from 1.16.5 through 26.2, so there is no version picker because nothing differs. The math runs in your browser with no ads, and your files and inputs never leave your device.",
    faq: [
      {
        q: "How much XP does it take to reach level 30?",
        a: "1,395 experience points starting from level 0. The curve has three tiers: each level up to 15 costs 7 + 2 times the level, levels 15 to 30 cost 37 + 5 per level above 15, and levels past 30 cost 112 + 9 per level above 30. That is why level 30 to 39 costs more than level 0 to 30.",
      },
      {
        q: "How does Mending turn XP into durability?",
        a: "Every experience point an orb carries repairs 2 points of durability on the Mending item you are holding or wearing, and orbs go to repair before they fill your XP bar. The ratio is hard-coded in the experience orb logic through 1.20.6 and defined as a repair_with_xp factor of 2.0 in the enchantment data from 1.21 on; both were checked and match.",
      },
      {
        q: "Do these numbers change between Minecraft versions?",
        a: "No. The level curve, mob XP rewards, Bottle o' Enchanting range, ore drop ranges, and the Mending ratio were compared across decompiled code for 1.16.5, 1.18.2, 1.20.6, 1.21.1, 1.21.11, and 26.2, and every value is identical. Only availability changes: newer mobs like the Warden and Breeze simply do not exist in older versions. Mob equipment adds 1 to 3 bonus XP per equipped item, and Looting does not change XP drops.",
      },
    ],
  },
};
