import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "screenshot-annotator",
  matrixSlug: "annotate",
  icon: "PenTool",
  name: "Screenshot Annotator",
  description: "Draw arrows, boxes, blur and numbered callouts on any screenshot.",
  category: "Capture",
  keywords: [
    "screenshot annotator",
    "annotate screenshot online",
    "add arrows to screenshot",
    "blur part of screenshot",
    "markup screenshot",
    "callout numbers screenshot",
    "draw on screenshot",
  ],
  searchTerms: [
    "image markup",
    "arrow tool",
    "circle part of image",
    "highlight screenshot",
    "number the steps in a screenshot",
    "skitch alternative",
    "snagit alternative",
    "annotate png",
    "draw box on image",
    "pixelate screenshot",
    "bug report screenshot tool",
    "redact screenshot online",
    "annotate image online free",
  ],
  input: "application/json",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "color",
      label: "Stroke color",
      default: "#e5484d",
      options: [
        { value: "#e5484d", label: "Red", synonyms: ["crimson", "error", "danger"] },
        { value: "#f76b15", label: "Orange", synonyms: ["amber", "warning"] },
        { value: "#30a46c", label: "Green", synonyms: ["success", "ok", "emerald"] },
        { value: "#0091ff", label: "Blue", synonyms: ["azure", "link", "info"] },
        { value: "#8e4ec6", label: "Purple", synonyms: ["violet", "magenta"] },
        { value: "#e93d82", label: "Pink", synonyms: ["hot pink", "rose", "fuchsia"] },
      ],
    },
    {
      kind: "slider",
      id: "strokeWidth",
      label: "Stroke width (px)",
      default: 4,
      min: 1,
      max: 24,
      step: 1,
    },
    {
      kind: "number",
      id: "fontSize",
      label: "Label size (px)",
      default: 18,
      min: 8,
      max: 96,
      step: 1,
    },
    {
      kind: "select",
      id: "blurStyle",
      label: "Blur style",
      default: "blur",
      options: [
        { value: "blur", label: "Blur", synonyms: ["soften", "gaussian", "box blur"] },
        { value: "pixelate", label: "Pixelate", synonyms: ["mosaic", "blocky", "censor"] },
      ],
    },
    {
      kind: "slider",
      id: "blurRadius",
      label: "Blur radius (px)",
      default: 10,
      min: 2,
      max: 40,
      step: 1,
    },
    {
      kind: "number",
      id: "pixelBlock",
      label: "Pixelate block size (px)",
      default: 12,
      min: 4,
      max: 64,
      step: 1,
    },
    {
      kind: "select",
      id: "format",
      label: "Export format",
      default: "png",
      options: [
        { value: "png", label: "PNG (lossless)", synonyms: ["portable network graphics", "sharp"] },
        { value: "jpeg", label: "JPEG (smaller)", synonyms: ["jpg", "compressed", "photo"] },
      ],
    },
  ],
  copy: {
    what: "Marks up a screenshot with the shapes people actually need in a bug report or a how-to: arrows, boxes, ellipses, straight lines, freehand ink, text labels on a readable pill, numbered callout badges that count themselves, a yellow highlighter, and blur or pixelate regions. The annotations live as an editable document, so you can select something you drew earlier, move it, or delete it instead of starting the image over. Export burns everything into a new PNG or JPEG, with the blurred areas genuinely resampled rather than covered by a shape. The overlay is also available as plain SVG if you would rather keep the markup separate from the picture.",
    how: "Drop a screenshot on the panel, paste one straight from the clipboard, or pick a file. Choose a tool from the toolbar or press its key: A for arrow, R for rect, E for ellipse, T for text, C for callout, B for blur, H for highlight, F for freehand. Drag on the image to draw, click a shape to select it, then drag to move it or press Delete to remove it, and Ctrl+Z to undo. When it looks right, export the flattened image or copy it to the clipboard to paste into an issue or a chat.",
    why: "Most annotation sites upload your screenshot to their servers before you have drawn a single arrow, which is a strange thing to accept when the screenshot is of your own dashboard, inbox, or invoice. Desktop apps solve the privacy problem and then ask for a license for what is fundamentally an arrow. This runs entirely in the page: your files and inputs never leave your device, there is no account, no watermark, and no size limit beyond what your browser can decode. Blur and pixelate are real pixel operations here, so the exported file has no hidden original underneath.",
    faq: [
      {
        q: "Is my screenshot uploaded anywhere?",
        a: "No. The image is decoded, drawn on, and re-encoded by the canvas in this tab, so your files and inputs never leave your device. There is no account to make and no server copy to delete, and closing the tab discards everything.",
      },
      {
        q: "Can I blur sensitive information properly?",
        a: "Blur and pixelate both rewrite the pixels in the region, so the export carries the softened or blocked version and nothing else. That is a real improvement on drawing a filled box over the area in a layered editor, where the original can survive underneath the shape and reappear if the file is opened without flattening. It is still not the strongest option: a blur keeps a low resolution trace of what was there, and researchers have reconstructed text from blurred and pixelated images. For a password, a token, or an account number, use the redaction tool and its solid fill, which replaces the region with one flat color and leaves nothing to analyze.",
      },
      {
        q: "Can I paste a screenshot straight from the clipboard?",
        a: "Yes. Press Ctrl+V (Cmd+V on a Mac) with the panel focused and the image on your clipboard loads onto the canvas, so a fresh Print Screen or a Shift+Cmd+4 capture goes straight to annotating. Dropping a file on the panel and picking one with the file button both work too, and when you are done you can copy the annotated result back to the clipboard instead of downloading it.",
      },
    ],
  },
};
