import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "tick-time-converter",
  matrixSlug: "minecraft-tick-time-converter",
  icon: "Timer",
  name: "Minecraft Tick Time Converter",
  description:
    "Convert between game ticks, redstone ticks, and real time, plus day cycle markers, /time add, and TPS versus MSPT.",
  category: "Minecraft",
  keywords: [
    "minecraft tick converter",
    "ticks to seconds minecraft",
    "minecraft redstone tick",
    "minecraft time set values",
    "minecraft tps mspt",
    "minecraft day length",
  ],
  searchTerms: [
    "how many ticks in a minecraft day",
    "time set night value",
    "time set noon value",
    "redstone tick vs game tick",
    "20 ticks per second",
    "mspt to tps calculator",
    "how long is 24000 ticks",
    "time add command calculator",
    "minecraft server lag tps",
    "how long is a redstone tick",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "ticks-to-time",
      options: [
        {
          value: "ticks-to-time",
          label: "Ticks to real time",
          synonyms: ["ticks to seconds", "ticks to minutes", "how long is n ticks"],
        },
        {
          value: "time-to-ticks",
          label: "Real time to ticks",
          synonyms: ["seconds to ticks", "minutes to ticks"],
        },
        {
          value: "redstone",
          label: "Redstone ticks",
          synonyms: ["redstone tick to game tick", "repeater delay", "comparator delay"],
        },
        {
          value: "day-cycle",
          label: "Day cycle marker",
          synonyms: ["time set", "noon", "midnight", "sunrise", "sunset", "what time is it"],
        },
        {
          value: "time-add",
          label: "/time add result",
          synonyms: ["time add command", "advance time"],
        },
        {
          value: "tps-to-mspt",
          label: "TPS to MSPT",
          synonyms: ["ticks per second", "server performance"],
        },
        {
          value: "mspt-to-tps",
          label: "MSPT to TPS",
          synonyms: ["milliseconds per tick", "server lag"],
        },
        {
          value: "durations",
          label: "Common durations table",
          synonyms: ["cheat sheet", "reference table", "furnace smelt time"],
        },
      ],
    },
    {
      kind: "number",
      id: "ticks",
      label: "Ticks (Ticks to real time)",
      default: 100,
      min: -1e9,
      max: 1e9,
      step: 1,
    },
    {
      kind: "number",
      id: "seconds",
      label: "Seconds (Real time to ticks)",
      default: 5,
      min: -1e8,
      max: 1e8,
      step: 0.05,
    },
    {
      kind: "number",
      id: "redstoneTicks",
      label: "Redstone ticks",
      default: 1,
      min: -5e8,
      max: 5e8,
      step: 1,
    },
    {
      kind: "number",
      id: "tps",
      label: "TPS (TPS to MSPT)",
      default: 20,
      min: 0.1,
      max: 20,
      step: 0.1,
    },
    {
      kind: "number",
      id: "mspt",
      label: "MSPT (MSPT to TPS)",
      default: 50,
      min: 0.1,
      max: 5000,
      step: 0.1,
    },
    {
      kind: "number",
      id: "currentTime",
      label: "Current time of day (ticks, Day cycle and /time add)",
      default: 6000,
      min: 0,
      max: 24000,
      step: 1,
    },
    {
      kind: "number",
      id: "addTicks",
      label: "Ticks to add (/time add)",
      default: 1000,
      min: 0,
      max: 1e8,
      step: 1,
    },
  ],
  http: { method: "GET", contentType: "application/json" },
  copy: {
    what: "Converts between Minecraft's 20 ticks per second game clock, redstone ticks (2 game ticks each), and real seconds, minutes, and hours. Also covers the day/night cycle: every named /time set marker with its tick value, what /time add lands on from a given starting time, and a server performance converter between TPS and MSPT. A reference table lists common in-game durations, like a furnace smelt or a full day, already converted.",
    how: "Pick a mode and enter the value it asks for: a tick count, a duration in seconds, a redstone tick count, a current day/night tick, or a measured TPS or MSPT figure. Every field converts live and updates the URL, so a link reproduces the exact conversion.",
    why: "Most tick converters online cover one direction and stop. This one keeps game ticks, redstone ticks, day cycle markers, /time add, and server TPS/MSPT together in one tool, since anyone building redstone, writing a datapack, or reading server lag numbers usually needs more than one of them in the same sitting. It runs entirely in your browser: your files and inputs never leave your device.",
    faq: [
      {
        q: "How many ticks are in a Minecraft day?",
        a: "24000 ticks, which is 20 real minutes at a full, unlagged 20 ticks per second. Noon is tick 6000, sunset is tick 12000, night (full dark) is tick 13000, midnight is tick 18000, and sunrise is tick 23000.",
      },
      {
        q: "What is the difference between a game tick and a redstone tick?",
        a: "A game tick is the server's base unit, 1/20 of a second. A redstone tick is exactly 2 game ticks, 1/10 of a second, and is the unit repeater delay steps and most redstone timing documentation use, since redstone components update on even tick boundaries.",
      },
      {
        q: "What does MSPT tell me about server lag?",
        a: "MSPT is the average milliseconds each server tick actually takes to process. A healthy server holds 20 TPS at 50 MSPT per tick; once MSPT climbs past 50 the server can no longer keep up, and TPS drops below 20 in direct proportion, since the server just runs fewer ticks per real second.",
      },
    ],
  },
};
