import type { ToolMeta } from '../types';

export const meta: ToolMeta = {
  slug: 'escape-unescape',
  matrixSlug: 'escape',
  name: 'Escape / Unescape',
  description:
    'Escape or unescape text in over thirty formats: JSON, HTML, XML, URL, C, Python, Java, shell, SQL, base64, base32, base58, ascii85, uuencode, quoted-printable, ROT13/47, Morse, NATO phonetic, punycode, and more.',
  category: 'Text',
  keywords: [
    'escape string',
    'unescape string',
    'encode decode text',
    'json escape',
    'html entities',
    'url encode decode',
    'base64 encode decode',
    'punycode converter',
  ],
  searchTerms: [
    'regex escape',
    'shell quote escape',
    'xml entity encode',
    'percent encoding',
    'url component encode',
    'form url encoded',
    'c string escape',
    'c++ string escape',
    'python string escape',
    'java unicode escape',
    'dotnet string escape',
    'csharp string escape',
    'unicode code point escape',
    'hex escape',
    'octal escape',
    'whitespace visualizer',
    'control character escape',
    'powershell string escape',
    'windows batch escape',
    'cmd escape',
    'sql string quote',
    'sql escape',
    'csv quote field',
    'ldap filter escape',
    'ldap escape',
    'base32 encode decode',
    'base58 encode decode',
    'bitcoin base58',
    'ascii85 encode decode',
    'base85 encode decode',
    'adobe85',
    'uuencode uudecode',
    'quoted printable',
    'mime qp encode',
    'rot13',
    'rot47 cipher',
    'caesar cipher',
    'morse code translator',
    'nato phonetic alphabet',
    'military alphabet',
    'idn encode',
    'punycode encode decode',
    'xn-- prefix',
    'internationalized domain name',
  ],
  input: 'text/plain',
  output: 'text/plain',
  options: [
    {
      kind: 'select',
      id: 'format',
      label: 'Format',
      default: 'json',
      choices: [
        { value: 'json', label: 'JSON string escape' },
        { value: 'html', label: 'HTML entities (named + numeric)' },
        { value: 'xml', label: 'XML entities (predefined + numeric)' },
        { value: 'url', label: 'URL percent-encoding (component)' },
        { value: 'url-full', label: 'URL percent-encoding (full URI)' },
        { value: 'url-form', label: 'URL form-encoded (application/x-www-form-urlencoded)' },
        { value: 'url-bytes', label: 'Percent-encode every UTF-8 byte' },
        { value: 'regex', label: 'Regex metacharacters' },
        { value: 'c', label: 'C / C++ string literal' },
        { value: 'python', label: 'Python string literal' },
        { value: 'java', label: 'Java / .NET \\uXXXX escape' },
        { value: 'unicode-brace', label: 'JS/TS \\u{...} code point escape' },
        { value: 'whitespace', label: 'Whitespace and control character visualizer' },
        { value: 'hex-bytes', label: 'Hex byte escape (\\xHH, every byte)' },
        { value: 'octal-bytes', label: 'Octal byte escape (\\NNN, every byte)' },
        { value: 'shell', label: 'Shell, POSIX single-quoted' },
        { value: 'shell-double', label: 'Shell, POSIX double-quoted' },
        { value: 'batch', label: 'Windows batch (cmd.exe) escape' },
        { value: 'powershell', label: 'PowerShell single-quoted string' },
        { value: 'sql', label: 'SQL string literal quoting' },
        { value: 'csv', label: 'CSV field quoting (RFC 4180)' },
        { value: 'ldap', label: 'LDAP filter escaping (RFC 4515)' },
        { value: 'base64', label: 'Base64' },
        { value: 'base64url', label: 'Base64url (no padding)' },
        { value: 'base32', label: 'Base32 (RFC 4648)' },
        { value: 'base58', label: 'Base58 (Bitcoin alphabet)' },
        { value: 'ascii85', label: 'Ascii85 / Base85 (Adobe)' },
        { value: 'uuencode', label: 'Uuencode' },
        { value: 'quoted-printable', label: 'Quoted-printable (MIME)' },
        { value: 'rot13', label: 'ROT13' },
        { value: 'rot47', label: 'ROT47' },
        { value: 'morse', label: 'Morse code' },
        { value: 'nato', label: 'NATO phonetic alphabet' },
        { value: 'punycode', label: 'Punycode / IDN (xn-- domains)' },
      ],
    },
    {
      kind: 'select',
      id: 'direction',
      label: 'Direction',
      default: 'escape',
      choices: [
        { value: 'escape', label: 'Escape / Encode' },
        { value: 'unescape', label: 'Unescape / Decode' },
      ],
    },
  ],
  http: { method: 'POST', contentType: 'text/plain' },
  copy: {
    what: 'One tool for over thirty text escaping and encoding formats: the common ones (JSON, HTML, XML, URL, regex) plus far more obscure territory, including C, Python, Java and JS/TS string-literal escapes, shell/batch/PowerShell/SQL/CSV/LDAP quoting, binary-to-text encodings (base64, base64url, base32, base58, ascii85, uuencode, quoted-printable), classic ciphers (ROT13, ROT47), Morse code, the NATO phonetic alphabet, and punycode for internationalized domain names. Every reversible format round-trips: escape, then unescape, and you get your original text back.',
    how: 'Paste your text, pick a format from the dropdown, and choose Escape/Encode or Unescape/Decode. The result updates instantly with its own copy button. Malformed input for any decode direction (a truncated base64 string, an unterminated escape sequence, an out-of-range punycode digit) raises a specific error explaining what is wrong and how to fix it, instead of silently returning garbage.',
    why: 'Most escaping sites online handle one format, bury the tool under ads, and quietly mangle malformed input. This one covers over thirty formats, common and obscure, in a single page, runs entirely in your browser, and never sends your text anywhere: your files and inputs never leave your device.',
    faq: [
      {
        q: 'What is the difference between the URL, URL full URI, and URL form-encoded options?',
        a: 'Component encoding (encodeURIComponent) escapes everything except unreserved characters, and is right for a single query parameter or path segment. Full URI encoding (encodeURI) leaves URL structure characters like / and ? alone, for encoding a whole URL. Form-encoded matches application/x-www-form-urlencoded, the format browsers use for HTML form submissions, where a space becomes + instead of %20.',
      },
      {
        q: 'Why do some formats like ROT13 have both Escape and Unescape do the same thing?',
        a: 'ROT13 and ROT47 are self-inverse Caesar ciphers: applying the same shift twice returns the original text, so encoding and decoding are literally the same operation. Both directions are still exposed for consistency with every other format.',
      },
      {
        q: 'How does punycode handle a full domain name like café.com?',
        a: 'It splits on dots and encodes each label independently, only touching labels that contain non-ASCII characters and prefixing them with xn--, exactly like a browser converts an internationalized domain name before a DNS lookup. ASCII-only labels, like com, pass through untouched.',
      },
    ],
  },
};
