import { describe, expect, it } from "vitest";
import { buildCaddy, buildNginx, run, type ReverseProxyOpts } from "./index";
import { ToolError } from "../types";

const DEFAULT_OPTS: ReverseProxyOpts = {
  server: "nginx",
  domain: "app.example.com",
  upstream: "http://127.0.0.1:3000",
  tls: true,
  websockets: true,
  securityHeaders: true,
  realIp: true,
  gzip: true,
  maxBodyMb: 50,
  timeoutSec: 60,
  cache: "none",
  wwwRedirect: false,
};

const INPUT_LINE = "app.example.com -> http://127.0.0.1:3000";

const EXPECTED_CADDY_DEFAULT = `# Reverse proxy config generated for app.example.com
# Generated by the tools.maxhogan.dev reverse proxy config generator

app.example.com {
    # Caddy proxies websockets automatically, no extra config needed.
    request_body {
        max_size 50MB
    }
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
    }
    encode gzip zstd
    reverse_proxy http://127.0.0.1:3000 {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up Host {host}
        transport http {
            read_timeout 60s
            write_timeout 60s
        }
    }
}
`;

describe("run", () => {
  it("defaults: nginx server block has server_name, proxy_pass, websocket upgrade, HSTS, 443 ssl, and the port 80 redirect", () => {
    const out = run(INPUT_LINE, DEFAULT_OPTS);
    expect(out).toContain("server_name app.example.com;");
    expect(out).toContain("proxy_pass http://127.0.0.1:3000;");
    expect(out).toContain("proxy_set_header Upgrade $http_upgrade;");
    expect(out).toContain('Strict-Transport-Security "max-age=31536000; includeSubDomains"');
    expect(out).toContain("listen 443 ssl http2;");
    expect(out).toContain("return 301 https://$host$request_uri;");
  });

  it("defaults: emits an exact Caddyfile block", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy" });
    expect(out).toBe(EXPECTED_CADDY_DEFAULT);
  });

  it("input line overrides the domain and upstream options", () => {
    const out = run("other.example.com -> http://10.0.0.5:8080", {
      ...DEFAULT_OPTS,
      domain: "unused.example.com",
      upstream: "http://unused:1",
    });
    expect(out).toContain("server_name other.example.com;");
    expect(out).toContain("proxy_pass http://10.0.0.5:8080;");
  });

  it("falls back to the domain and upstream options when input has no arrow", () => {
    const out = run("just some notes, not a config line", DEFAULT_OPTS);
    expect(out).toContain("server_name app.example.com;");
    expect(out).toContain("proxy_pass http://127.0.0.1:3000;");
  });

  it("tls=false removes ssl, HSTS, and the redirect block from nginx", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, tls: false });
    expect(out).not.toContain("ssl");
    expect(out).not.toContain("Strict-Transport-Security");
    expect(out).not.toContain("return 301 https://$host$request_uri;");
    expect(out).toContain("listen 80;");
  });

  it("tls=false uses an explicit http:// address and drops HSTS in Caddy", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy", tls: false });
    expect(out).toContain("http://app.example.com {");
    expect(out).not.toContain("Strict-Transport-Security");
  });

  it("websockets=false drops the Upgrade/Connection headers", () => {
    const nginxOut = run(INPUT_LINE, { ...DEFAULT_OPTS, websockets: false });
    expect(nginxOut).not.toContain("Upgrade");
    expect(nginxOut).not.toContain("proxy_http_version 1.1;");

    const caddyOut = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy", websockets: false });
    expect(caddyOut).not.toContain("websockets automatically");
  });

  it("securityHeaders=false drops all security headers", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, securityHeaders: false });
    expect(out).not.toContain("X-Content-Type-Options");
    expect(out).not.toContain("X-Frame-Options");
    expect(out).not.toContain("Referrer-Policy");
    expect(out).not.toContain("Strict-Transport-Security");
  });

  it("realIp=false drops the real-IP forwarding headers", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, realIp: false });
    expect(out).not.toContain("X-Real-IP");
    expect(out).not.toContain("X-Forwarded-For");
  });

  it("gzip=false drops the gzip block", () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, gzip: false });
    expect(out).not.toContain("gzip on;");

    const caddyOut = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy", gzip: false });
    expect(caddyOut).not.toContain("encode gzip zstd");
  });

  it("cache=static-assets adds a static asset location/matcher with long expiry", () => {
    const nginxOut = run(INPUT_LINE, { ...DEFAULT_OPTS, cache: "static-assets" });
    expect(nginxOut).toContain("location ~* \\.(css|js|mjs|png|jpg|jpeg|gif|svg|ico|woff|woff2)$");
    expect(nginxOut).toContain("expires 30d;");

    const caddyOut = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy", cache: "static-assets" });
    expect(caddyOut).toContain("@static {");
    expect(caddyOut).toContain('header @static Cache-Control "public, max-age=2592000, immutable"');
  });

  it("wwwRedirect adds an extra server/site block redirecting www to the apex domain", () => {
    const nginxOut = run(INPUT_LINE, { ...DEFAULT_OPTS, wwwRedirect: true });
    expect(nginxOut).toContain("server_name www.app.example.com;");
    expect(nginxOut).toContain("return 301 https://app.example.com$request_uri;");

    const caddyOut = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "caddy", wwwRedirect: true });
    expect(caddyOut).toContain("www.app.example.com {");
    expect(caddyOut).toContain("redir https://app.example.com{uri} permanent");
  });

  it('server="both" includes labeled nginx and Caddy sections', () => {
    const out = run(INPUT_LINE, { ...DEFAULT_OPTS, server: "both" });
    expect(out).toContain("==================== nginx ====================");
    expect(out).toContain("==================== Caddy (Caddyfile) ====================");
    expect(out).toContain("server_name app.example.com;");
    expect(out).toContain("reverse_proxy http://127.0.0.1:3000 {");
  });

  it("is deterministic: the same input and options produce identical output", () => {
    const a = run(INPUT_LINE, DEFAULT_OPTS);
    const b = run(INPUT_LINE, DEFAULT_OPTS);
    expect(a).toBe(b);
  });

  it("throws empty-input when no domain/upstream is available", () => {
    try {
      run("", { ...DEFAULT_OPTS, domain: "", upstream: "" });
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ToolError);
      expect((err as ToolError).code).toBe("empty-input");
    }
  });

  it("throws bad-domain for an invalid hostname", () => {
    try {
      run("not a domain!! -> http://127.0.0.1:3000", DEFAULT_OPTS);
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ToolError);
      expect((err as ToolError).code).toBe("bad-domain");
    }
  });

  it("throws bad-upstream for an invalid upstream target", () => {
    try {
      run("app.example.com -> not-a-url", DEFAULT_OPTS);
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ToolError);
      expect((err as ToolError).code).toBe("bad-upstream");
    }
  });

  it("accepts a unix socket upstream", () => {
    const out = run("app.example.com -> unix:/run/app.sock", DEFAULT_OPTS);
    expect(out).toContain("proxy_pass http://unix:/run/app.sock:/;");
  });

  it("throws bad-option when maxBodyMb is out of range", () => {
    try {
      run(INPUT_LINE, { ...DEFAULT_OPTS, maxBodyMb: 0 });
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ToolError);
      expect((err as ToolError).code).toBe("bad-option");
    }
  });

  it("throws bad-option when timeoutSec is out of range", () => {
    try {
      run(INPUT_LINE, { ...DEFAULT_OPTS, timeoutSec: -5 });
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ToolError);
      expect((err as ToolError).code).toBe("bad-option");
    }
  });
});

describe("buildNginx / buildCaddy", () => {
  it("buildNginx produces a complete, non-empty server block set directly", () => {
    const out = buildNginx(DEFAULT_OPTS, "app.example.com", "http://127.0.0.1:3000");
    expect(out).toContain("server {");
    expect(out).toContain("location / {");
  });

  it("buildCaddy produces a complete site block directly", () => {
    const out = buildCaddy(DEFAULT_OPTS, "app.example.com", "http://127.0.0.1:3000");
    expect(out).toContain("app.example.com {");
    expect(out).toContain("reverse_proxy http://127.0.0.1:3000 {");
  });
});

describe("run: the meta.ts examples", () => {
  it("builds nginx for the quick entry line", () => {
    const out = run("app.example.com -> http://127.0.0.1:3000", { ...DEFAULT_OPTS, server: "nginx" });
    expect(out).toContain("server_name app.example.com;");
    expect(out).toContain("proxy_pass http://127.0.0.1:3000;");
  });

  it("builds Caddy with static asset caching and a www redirect", () => {
    const out = run("static.example.com -> http://127.0.0.1:8080", {
      ...DEFAULT_OPTS,
      server: "caddy",
      cache: "static-assets",
      wwwRedirect: true,
    });
    expect(out).toContain("static.example.com {");
    expect(out).toContain("reverse_proxy http://127.0.0.1:8080 {");
  });
});
