import { ToolError, type ToolLogic } from "../types";

export interface ReverseProxyOpts {
  server: string;
  domain: string;
  upstream: string;
  tls: boolean;
  websockets: boolean;
  securityHeaders: boolean;
  realIp: boolean;
  gzip: boolean;
  maxBodyMb: number;
  timeoutSec: number;
  cache: string;
  wwwRedirect: boolean;
  [key: string]: unknown;
}

const HOSTNAME_PATTERN =
  /^(?=.{1,253}$)(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*$/;

const HTTP_UPSTREAM_PATTERN = /^https?:\/\/[a-zA-Z0-9.-]+(:\d{1,5})?$/;
const UNIX_UPSTREAM_PATTERN = /^unix:\/[^\s]+$/;

const STATIC_ASSET_EXTS_NGINX = "css|js|mjs|png|jpg|jpeg|gif|svg|ico|woff|woff2";
const STATIC_ASSET_EXTS_CADDY = "*.css *.js *.mjs *.png *.jpg *.jpeg *.gif *.svg *.ico *.woff *.woff2";

/** Parses an "host -> upstream" input line, or returns null when the line has no arrow. */
function parseInputOverride(input: string): { domain: string; upstream: string } | null {
  const trimmed = (input ?? "").trim();
  const arrowIndex = trimmed.indexOf("->");
  if (arrowIndex === -1) return null;
  return {
    domain: trimmed.slice(0, arrowIndex).trim(),
    upstream: trimmed.slice(arrowIndex + 2).trim(),
  };
}

function validateDomain(domain: string): void {
  if (!HOSTNAME_PATTERN.test(domain)) {
    throw new ToolError(
      "bad-domain",
      `"${domain}" does not look like a valid hostname.`,
      "Use a plain domain name, for example app.example.com (no scheme, no path).",
    );
  }
}

function validateUpstream(upstream: string): void {
  if (!HTTP_UPSTREAM_PATTERN.test(upstream) && !UNIX_UPSTREAM_PATTERN.test(upstream)) {
    throw new ToolError(
      "bad-upstream",
      `"${upstream}" is not a valid upstream target.`,
      "Use http://host:port, https://host:port, or unix:/path/to.sock, for example http://127.0.0.1:3000.",
    );
  }
}

/** Converts an upstream target into an nginx proxy_pass value, handling unix sockets. */
function toNginxProxyPass(upstream: string): string {
  if (upstream.startsWith("unix:")) {
    const socketPath = upstream.slice("unix:".length);
    return `http://unix:${socketPath}:/`;
  }
  return upstream;
}

function indentBlock(lines: string[], indent = "    "): string[] {
  return lines.map((line) => (line.length > 0 ? `${indent}${line}` : line));
}

function validateOptions(opts: ReverseProxyOpts): void {
  if (!Number.isFinite(opts.maxBodyMb) || opts.maxBodyMb <= 0 || opts.maxBodyMb > 10000) {
    throw new ToolError(
      "bad-option",
      `Max body size ${opts.maxBodyMb}MB is out of range.`,
      "Use a value between 1 and 10000 (megabytes).",
    );
  }
  if (!Number.isFinite(opts.timeoutSec) || opts.timeoutSec <= 0 || opts.timeoutSec > 3600) {
    throw new ToolError(
      "bad-option",
      `Timeout ${opts.timeoutSec}s is out of range.`,
      "Use a value between 1 and 3600 (seconds).",
    );
  }
}

function headerComment(domain: string): string {
  return [
    `# Reverse proxy config generated for ${domain}`,
    "# Generated by the tools.maxhogan.dev reverse proxy config generator",
  ].join("\n");
}

/** Builds a complete nginx server block set for the resolved options. */
export function buildNginx(opts: ReverseProxyOpts, domain: string, upstream: string): string {
  const proxyPass = toNginxProxyPass(upstream);
  const blocks: string[] = [headerComment(domain)];

  if (opts.tls) {
    blocks.push(
      [
        "server {",
        "    listen 80;",
        "    listen [::]:80;",
        `    server_name ${domain};`,
        "    return 301 https://$host$request_uri;",
        "}",
      ].join("\n"),
    );
  }

  if (opts.wwwRedirect) {
    const scheme = opts.tls ? "https" : "http";
    const wwwServerLines = ["server {"];
    if (opts.tls) {
      wwwServerLines.push("    listen 443 ssl http2;", "    listen [::]:443 ssl http2;");
    } else {
      wwwServerLines.push("    listen 80;", "    listen [::]:80;");
    }
    wwwServerLines.push(`    server_name www.${domain};`);
    if (opts.tls) {
      wwwServerLines.push(
        `    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;`,
        `    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`,
      );
    }
    wwwServerLines.push(`    return 301 ${scheme}://${domain}$request_uri;`, "}");
    blocks.push(wwwServerLines.join("\n"));
  }

  const locationLines: string[] = ["proxy_pass " + proxyPass + ";"];
  if (opts.websockets) {
    locationLines.push(
      "proxy_http_version 1.1;",
      "proxy_set_header Upgrade $http_upgrade;",
      'proxy_set_header Connection "upgrade";',
    );
  }
  if (opts.realIp) {
    locationLines.push(
      "proxy_set_header X-Real-IP $remote_addr;",
      "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
      "proxy_set_header X-Forwarded-Proto $scheme;",
      "proxy_set_header Host $host;",
    );
  }
  locationLines.push(
    `proxy_connect_timeout ${opts.timeoutSec}s;`,
    `proxy_send_timeout ${opts.timeoutSec}s;`,
    `proxy_read_timeout ${opts.timeoutSec}s;`,
  );

  const serverLines: string[] = ["server {"];
  if (opts.tls) {
    serverLines.push("    listen 443 ssl http2;", "    listen [::]:443 ssl http2;");
  } else {
    serverLines.push("    listen 80;", "    listen [::]:80;");
  }
  serverLines.push(`    server_name ${domain};`, "");

  if (opts.tls) {
    serverLines.push(
      `    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;`,
      `    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`,
      "",
    );
  }

  serverLines.push(`    client_max_body_size ${opts.maxBodyMb}m;`, "");

  if (opts.securityHeaders) {
    if (opts.tls) {
      serverLines.push(
        '    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;',
      );
    }
    serverLines.push(
      "    add_header X-Content-Type-Options nosniff always;",
      "    add_header X-Frame-Options SAMEORIGIN always;",
      '    add_header Referrer-Policy strict-origin-when-cross-origin always;',
      "",
    );
  }

  if (opts.gzip) {
    serverLines.push(
      "    gzip on;",
      "    gzip_min_length 256;",
      "    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;",
      "",
    );
  }

  if (opts.cache === "static-assets") {
    serverLines.push(
      `    location ~* \\.(${STATIC_ASSET_EXTS_NGINX})$ {`,
      `        proxy_pass ${proxyPass};`,
      "        expires 30d;",
      '        add_header Cache-Control "public, max-age=2592000, immutable";',
      "        access_log off;",
      "    }",
      "",
    );
  }

  serverLines.push("    location / {", ...indentBlock(locationLines, "        "), "    }", "}");

  blocks.push(serverLines.join("\n"));

  return blocks.join("\n\n") + "\n";
}

/** Builds a complete Caddyfile site block set for the resolved options. */
export function buildCaddy(opts: ReverseProxyOpts, domain: string, upstream: string): string {
  const blocks: string[] = [headerComment(domain)];

  const siteAddress = opts.tls ? domain : `http://${domain}`;
  const siteLines: string[] = [`${siteAddress} {`];

  if (opts.websockets) {
    siteLines.push("    # Caddy proxies websockets automatically, no extra config needed.");
  }

  siteLines.push(`    request_body {`, `        max_size ${opts.maxBodyMb}MB`, `    }`);

  if (opts.securityHeaders) {
    const headerLines: string[] = [];
    if (opts.tls) {
      headerLines.push(
        '        Strict-Transport-Security "max-age=31536000; includeSubDomains"',
      );
    }
    headerLines.push(
      '        X-Content-Type-Options "nosniff"',
      '        X-Frame-Options "SAMEORIGIN"',
      '        Referrer-Policy "strict-origin-when-cross-origin"',
    );
    siteLines.push("    header {", ...headerLines, "    }");
  }

  if (opts.gzip) {
    siteLines.push("    encode gzip zstd");
  }

  if (opts.cache === "static-assets") {
    siteLines.push(
      "    @static {",
      `        path ${STATIC_ASSET_EXTS_CADDY}`,
      "    }",
      '    header @static Cache-Control "public, max-age=2592000, immutable"',
    );
  }

  const reverseProxyLines: string[] = [`reverse_proxy ${upstream} {`];
  if (opts.realIp) {
    reverseProxyLines.push(
      "    header_up X-Real-IP {remote_host}",
      "    header_up X-Forwarded-For {remote_host}",
      "    header_up X-Forwarded-Proto {scheme}",
      "    header_up Host {host}",
    );
  }
  reverseProxyLines.push(
    "    transport http {",
    `        read_timeout ${opts.timeoutSec}s`,
    `        write_timeout ${opts.timeoutSec}s`,
    "    }",
  );
  reverseProxyLines.push("}");

  siteLines.push(...indentBlock(reverseProxyLines, "    "));
  siteLines.push("}");

  blocks.push(siteLines.join("\n"));

  if (opts.wwwRedirect) {
    const canonicalScheme = opts.tls ? "https" : "http";
    const wwwAddress = opts.tls ? `www.${domain}` : `http://www.${domain}`;
    blocks.push(
      [
        `${wwwAddress} {`,
        `    redir ${canonicalScheme}://${domain}{uri} permanent`,
        "}",
      ].join("\n"),
    );
  }

  return blocks.join("\n\n") + "\n";
}

/**
 * input is an optional "host -> upstream" convenience line, for example
 * "app.example.com -> http://127.0.0.1:3000". When present it overrides the
 * domain and upstream options; when absent or not shaped like "a -> b", the
 * domain and upstream options are used as-is and the input is ignored.
 */
export function run(input: string, opts: ReverseProxyOpts): string {
  const override = parseInputOverride(input);

  const domain = (override?.domain || opts.domain || "").trim();
  const upstream = (override?.upstream || opts.upstream || "").trim();

  if (!domain || !upstream) {
    throw new ToolError(
      "empty-input",
      "Enter a domain and upstream, either in the fields or as a single line.",
      'For example: app.example.com -> http://127.0.0.1:3000',
    );
  }

  validateDomain(domain);
  validateUpstream(upstream);
  validateOptions(opts);

  const server = (opts.server || "nginx").trim();

  if (server === "nginx") return buildNginx(opts, domain, upstream);
  if (server === "caddy") return buildCaddy(opts, domain, upstream);

  const nginxOut = buildNginx(opts, domain, upstream);
  const caddyOut = buildCaddy(opts, domain, upstream);
  return [
    "# ==================== nginx ====================",
    "",
    nginxOut.trimEnd(),
    "",
    "# ==================== Caddy (Caddyfile) ====================",
    "",
    caddyOut.trimEnd(),
    "",
  ].join("\n");
}

export default { run } satisfies ToolLogic<string, string, ReverseProxyOpts>;
