import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "password-generator",
  icon: "KeyRound",
  matrixSlug: "password",
  name: "Password Generator",
  description: "Random passwords and diceware passphrases with real entropy maths.",
  category: "Crypto",
  keywords: [
    "password generator",
    "random password",
    "diceware",
    "passphrase generator",
    "strong password",
    "eff wordlist",
    "password entropy",
  ],
  searchTerms: [
    "secure password maker",
    "strong passphrase generator",
    "crack time calculator",
    "entropy calculator",
    "random string generator",
    "pwgen",
    "memorable password",
    "xkcd password generator",
    "correct horse battery staple",
    "passphrase with words",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "password",
      choices: [
        { value: "password", label: "Password" },
        { value: "passphrase", label: "Passphrase (diceware)" },
      ],
    },
    { kind: "number", id: "length", label: "Password length", default: 20, min: 8, max: 128 },
    { kind: "boolean", id: "lowercase", label: "Lowercase (a-z)", default: true },
    { kind: "boolean", id: "uppercase", label: "Uppercase (A-Z)", default: true },
    { kind: "boolean", id: "digits", label: "Digits (0-9)", default: true },
    { kind: "boolean", id: "symbols", label: "Symbols (!@#$...)", default: true },
    {
      kind: "boolean",
      id: "excludeAmbiguous",
      label: "Exclude ambiguous characters (0 O 1 l I |)",
      default: false,
    },
    {
      kind: "number",
      id: "words",
      label: "Word count (passphrase)",
      default: 6,
      min: 3,
      max: 12,
    },
    {
      kind: "text",
      id: "separator",
      label: "Word separator (passphrase)",
      default: "-",
      placeholder: "-",
    },
    { kind: "boolean", id: "capitalize", label: "Capitalize words (passphrase)", default: false },
    {
      kind: "text",
      id: "seed",
      label: "Seed (optional, for reproducible output)",
      default: "",
      placeholder: "leave empty for true randomness",
    },
  ],
  copy: {
    what: "Generates random passwords or diceware-style passphrases entirely in your browser, using the same EFF large wordlist (7,776 words) that security researchers recommend. Every result comes with its exact entropy in bits and a humanized crack-time estimate at 10 billion guesses per second.",
    how: "Choose Password or Passphrase mode. For passwords, set the length and toggle which character sets to include; for passphrases, set the word count, separator, and whether to capitalize each word. Leave the seed blank for cryptographically secure randomness, or set it to get the same reproducible output every time (useful for testing).",
    why: 'Most password generator sites are covered in ads, cap how many characters you can generate, or quietly log what you type into a form field. This one runs the whole computation locally with crypto.getRandomValues, shows the actual entropy math instead of a vague "strength" bar, and your generated credentials never touch a network request.',
    faq: [
      {
        q: "Is this actually random, or can the output be predicted?",
        a: "With the seed field empty, every character or word comes from crypto.getRandomValues, the same cryptographically secure source browsers use for key generation. Only setting a seed switches to a deterministic (predictable) generator, and that is opt-in for testing.",
      },
      {
        q: "What is a diceware passphrase and why use one?",
        a: "Diceware picks whole words at random from a large, fixed wordlist (here, the EFF large list of 7,776 words) instead of random characters. Six random words give about 77.5 bits of entropy (comparable to a long random password) while being far easier to memorize and type.",
      },
      {
        q: "What does the crack-time estimate mean?",
        a: "It divides the total possible combinations (2 raised to the entropy in bits) by 10 billion guesses per second, a realistic ceiling for offline GPU cracking of a well-hashed password. It is an order-of-magnitude estimate, not a guarantee: always pair strong passwords with unique use per site and, ideally, a password manager.",
      },
    ],
  },
};
