import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "fluid-clamp-calculator",
  icon: "Shrink",
  name: "Fluid Clamp Calculator",
  description:
    "Turn a min and max size into a responsive CSS clamp() expression, with a preview at six viewport widths.",
  category: "Dev",
  keywords: [
    "css clamp calculator",
    "fluid typography",
    "responsive font size",
    "clamp min max viewport",
    "fluid type scale",
    "vw font size calculator",
    "utopia type scale",
  ],
  searchTerms: [
    "clamp()",
    "fluid font size",
    "responsive spacing calculator",
    "linear interpolation css",
    "rem px converter font",
    "viewport units typography",
    "modular scale",
    "min() max() clamp()",
    "wcag 1.4.4 resize text",
    "fluid space calculator",
  ],
  input: "text/plain",
  output: "application/json",
  inputOptional: {
    label: "Quick entry",
    hint: "Two or four lengths: min size, max size, and optionally min and max viewport. For example 16px 24px 320px 1280px. Anything you type here overrides the matching options below.",
  },
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "single",
      options: [
        {
          value: "single",
          label: "One size",
          synonyms: ["single", "one value", "simple", "single clamp"],
        },
        {
          value: "scale",
          label: "Full type scale",
          synonyms: ["batch", "modular scale", "ratio", "steps", "utopia", "many sizes"],
        },
      ],
    },
    { kind: "number", id: "minSize", label: "Min size (px)", default: 16, min: 0.1, max: 2000 },
    { kind: "number", id: "maxSize", label: "Max size (px)", default: 24, min: 0.1, max: 2000 },
    {
      kind: "number",
      id: "minViewport",
      label: "Min viewport (px)",
      default: 320,
      min: 1,
      max: 10000,
    },
    {
      kind: "number",
      id: "maxViewport",
      label: "Max viewport (px)",
      default: 1280,
      min: 1,
      max: 10000,
    },
    {
      kind: "select",
      id: "unit",
      label: "Output unit",
      default: "rem",
      options: [
        {
          value: "rem",
          label: "rem",
          synonyms: ["root em", "relative", "accessible", "zoom friendly"],
        },
        { value: "px", label: "px", synonyms: ["pixels", "absolute", "device pixels"] },
      ],
    },
    { kind: "number", id: "rootSize", label: "Root font size (px)", default: 16, min: 1, max: 100 },
    {
      kind: "select",
      id: "minRatio",
      label: "Scale ratio at the min viewport",
      default: "1.2",
      ui: "select",
      options: [
        { value: "1.067", label: "1.067 minor second", synonyms: ["tight", "subtle", "15:16"] },
        { value: "1.125", label: "1.125 major second", synonyms: ["8:9", "compact"] },
        { value: "1.2", label: "1.2 minor third", synonyms: ["5:6", "common", "default"] },
        { value: "1.25", label: "1.25 major third", synonyms: ["4:5", "balanced"] },
        { value: "1.333", label: "1.333 perfect fourth", synonyms: ["3:4", "classic"] },
        { value: "1.414", label: "1.414 augmented fourth", synonyms: ["square root of two", "a4"] },
        { value: "1.5", label: "1.5 perfect fifth", synonyms: ["2:3", "dramatic"] },
        { value: "1.618", label: "1.618 golden ratio", synonyms: ["phi", "golden section"] },
      ],
    },
    {
      kind: "select",
      id: "maxRatio",
      label: "Scale ratio at the max viewport",
      default: "1.25",
      ui: "select",
      options: [
        { value: "1.067", label: "1.067 minor second", synonyms: ["tight", "subtle", "15:16"] },
        { value: "1.125", label: "1.125 major second", synonyms: ["8:9", "compact"] },
        { value: "1.2", label: "1.2 minor third", synonyms: ["5:6", "common"] },
        { value: "1.25", label: "1.25 major third", synonyms: ["4:5", "balanced", "default"] },
        { value: "1.333", label: "1.333 perfect fourth", synonyms: ["3:4", "classic"] },
        { value: "1.414", label: "1.414 augmented fourth", synonyms: ["square root of two", "a4"] },
        { value: "1.5", label: "1.5 perfect fifth", synonyms: ["2:3", "dramatic"] },
        { value: "1.618", label: "1.618 golden ratio", synonyms: ["phi", "golden section"] },
      ],
    },
    { kind: "number", id: "stepsUp", label: "Steps above the base", default: 5, min: 0, max: 12 },
    { kind: "number", id: "stepsDown", label: "Steps below the base", default: 2, min: 0, max: 6 },
    {
      kind: "text",
      id: "prefix",
      label: "Custom property prefix",
      default: "step",
      placeholder: "step",
    },
  ],
  examples: [
    { label: "Body copy, 16 to 24", input: "16px 24px 320px 1280px" },
    {
      label: "Display heading, 32 to 72",
      input: "32px 72px 375px 1440px",
    },
    {
      label: "Full type scale",
      input: "16px 20px 320px 1280px",
      opts: { mode: "scale", stepsUp: "5", stepsDown: "2" },
    },
  ],
  http: { method: "GET", contentType: "application/json" },
  copy: {
    what: "Turns a min size, a max size, and the two viewport widths they belong to into a CSS clamp() expression that scales smoothly between them. It shows the slope and intercept the expression is built from, previews the rendered size at 320, 375, 768, 1024, 1440, and 1920 pixels wide, and flags whether the result survives browser text zoom. A batch mode multiplies the base size by a ratio to emit a whole type scale as custom properties, with separate ratios for the small and large viewport so headings can grow faster than body copy.",
    how: "Set the four numbers, either in the option fields or as a single quick entry line like 16px 24px 320px 1280px. Pick rem or px output, then copy the clamp() value, the custom property, or the whole font-size declaration. Switch the mode to the full type scale when you want a set of sizes rather than one, and change the two ratios to control how quickly the scale grows at each end.",
    why: "Most clamp calculators hand back one expression and stop. This one shows the arithmetic, previews the rendered size at real device widths so you can see where the value bottoms out, and checks the rem term against WCAG 1.4.4 so a size that ignores browser text zoom does not slip through. It runs entirely in the page, so your files and inputs never leave your device.",
    faq: [
      {
        q: "Why does my clamp() ignore browser zoom?",
        a: "A preferred value built only from vw units tracks the viewport and nothing else, so raising the browser text size changes nothing. WCAG 1.4.4 asks that text stay usable at a 200 percent resize, which means the preferred value needs a rem term with a positive coefficient. This tool always writes the intercept as a rem length by default and tells you when that term has come out zero or negative, which happens when the size range is steep relative to the viewport range.",
      },
      {
        q: "What min and max viewport should I use?",
        a: "320px is the narrowest phone still worth designing for, and somewhere between 1280px and 1440px is where most layouts stop growing. Using your own container max width as the upper bound is usually better than the viewport, because past that point the text column stops widening and larger type stops helping. Whatever you pick, remember the size is frozen outside that range: the preview table marks those rows as clamped.",
      },
      {
        q: "How is the type scale mode different from a modular scale generator?",
        a: "A modular scale gives you one number per step. This gives you two, one for each end of the viewport range, and joins them with clamp(), so every step is fluid rather than fixed. Setting a larger ratio at the max viewport than at the min is the usual choice: it keeps headings close to body size on a phone, where a 1.618 scale would overflow, and lets them open up on a desktop.",
      },
    ],
  },
};
