import type { ToolMeta } from '../types';

export const meta: ToolMeta = {
  slug: 'batch-processor',
  matrixSlug: 'batch',
  name: 'Batch Processor',
  description: 'Run a text transform over many files and write the results back, safely.',
  category: 'Files',
  keywords: [
    'batch process files',
    'find and replace across files',
    'bulk edit text files',
    'transform folder of files',
    'batch text tool no upload',
  ],
  searchTerms: [
    'sed alternative',
    'mass find and replace',
    'bulk text editor',
    'folder text processor',
    'multi file find replace',
    'bulk json formatter',
    'batch sort lines',
    'bulk dedupe lines',
    'bulk trim whitespace',
    'crlf lf converter',
    'strip bom',
  ],
  input: 'none',
  output: 'application/json',
  requires: ['fs-access'],
  options: [
    {
      kind: 'text',
      id: 'filter',
      label: 'Files to include',
      default: '*',
      placeholder: '*.md, docs/**/*.txt, !draft-*.md',
    },
    {
      kind: 'select',
      id: 'operation',
      label: 'Operation',
      default: 'find-replace',
      choices: [
        { value: 'find-replace', label: 'Find and replace' },
        { value: 'case', label: 'Change case' },
        { value: 'trim-whitespace', label: 'Trim whitespace' },
        { value: 'line-endings', label: 'Convert line endings' },
        { value: 'encoding-normalize', label: 'Strip byte order mark' },
        { value: 'prefix-suffix', label: 'Add header or footer' },
        { value: 'sort-lines', label: 'Sort lines' },
        { value: 'dedupe-lines', label: 'Remove duplicate lines' },
        { value: 'json-format', label: 'Format JSON' },
        { value: 'template-wrap', label: 'Wrap in a template' },
      ],
    },
    {
      kind: 'select',
      id: 'output',
      label: 'Where results go',
      default: 'subfolder',
      choices: [
        { value: 'subfolder', label: 'Into a subfolder (originals untouched)' },
        { value: 'suffix', label: 'Alongside, as name.processed.ext' },
        { value: 'in-place', label: 'In place (overwrites the originals)' },
      ],
    },
    {
      kind: 'text',
      id: 'subfolder',
      label: 'Subfolder name',
      default: 'processed',
      placeholder: 'processed',
    },
  ],
  copy: {
    what: 'Batch Processor applies one text transform to every file you pick out of a folder on your disk. Ten operations are built in: find and replace (literal or regex), change case, trim trailing whitespace, convert line endings to LF or CRLF, strip a byte order mark, add a header or footer, sort lines, remove duplicate lines, pretty print or minify JSON, and wrap each file in a template using {content} and {name}. A glob filter picks the files, and results can overwrite the originals, land alongside them as name.processed.ext, or go into a subfolder that mirrors your folder structure. Version 1 handles text files only, so images, archives and other binary formats are skipped by extension and listed rather than damaged.',
    how: 'Choose a folder, then type a filter such as *.md or docs/**/*.txt and watch the matched count. Pick an operation, fill in its options, and check the before and after preview that runs on the first matched file so you can see exactly what the transform does. Choose where results go, then press Process. You review the full list of changes and confirm before anything is written, and files whose text came out identical are never rewritten.',
    why: 'Doing the same edit to 200 files usually means writing a throwaway script or paying for a desktop app that wants your folder in its cloud. This runs the common transforms against your real folder, with a live matched count, a preview before you commit, and a downloadable backup of the originals, all locally: your files and inputs never leave your device.',
    faq: [
      {
        q: 'What kinds of files can it handle?',
        a: 'Text files only in this version: Markdown, code, CSV, JSON, config, logs, plain text. Known binary extensions such as .png, .zip, .pdf and .docx are skipped by extension and listed in the results, because a text transform would turn them into damaged bytes. Files over 8 MB are skipped too. Batch work on images and other binary formats needs a different pipeline, and it is not built yet.',
      },
      {
        q: 'Can I undo an in place edit?',
        a: 'Only from the backup file, so download it. Before an in place run the panel writes a backup of the original contents of every file it is about to change and hands it to you as a JSON download. The folder tool undo file that comes with every write batch lists the operations, but it cannot restore contents that were overwritten, because the old bytes were never in it. If you would rather not rely on a backup at all, choose the subfolder or alongside output mode: both leave your originals exactly where they are.',
      },
      {
        q: 'Are my files uploaded anywhere?',
        a: 'No. The folder is opened in place through the browser File System Access API and read in this tab: your files and inputs never leave your device. Nothing is copied to a server, and the tool only gets the folder you explicitly pick, for as long as the tab is open.',
      },
    ],
  },
};
