import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "electromagnetic-spectrum",
  name: "Electromagnetic Spectrum and Frequency Allocations",
  description:
    "A to scale map of the electromagnetic spectrum plus a US frequency allocation chart: who uses each band, ham band plans, Wi-Fi and IoT channel tables, license rules and an FCC RF exposure calculator.",
  category: "RF",
  keywords: [
    "electromagnetic spectrum",
    "frequency allocation chart",
    "us spectrum allocations",
    "ham radio band plan",
    "who uses this frequency",
    "ism bands",
    "wifi channel frequencies",
    "rf exposure calculator",
    "wavelength frequency converter",
    "photon energy calculator",
    "radio frequency bands",
  ],
  searchTerms: [
    "light spectrum",
    "radio spectrum",
    "spectrum allocation",
    "frequency allocation table",
    "fcc table of frequency allocations",
    "band plan",
    "amateur radio bands",
    "technician general extra privileges",
    "2m 70cm band",
    "who is on this frequency",
    "unlicensed bands",
    "ism band",
    "part 15",
    "gmrs frs murs channels",
    "zigbee channels",
    "lora frequencies",
    "bluetooth channels",
    "wifi channel list",
    "cellular bands lte 5g",
    "gps frequency",
    "radio astronomy protected bands",
    "mpe limit",
    "rf exposure limits",
    "fcc rf exposure",
    "power density calculator",
    "wavelength frequency converter",
    "photon energy",
    "gamma xray uv infrared microwave",
    "ITU bands",
    "ITU regions",
    "visible light nm",
    "blackbody temperature",
    "em spectrum",
    "frequency to wavelength",
    "ev to nm",
    "color to wavelength",
    "electromagnetic spectrum chart",
  ],
  icon: "Rainbow",
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "text",
      id: "query",
      label: "Jump to (frequency, wavelength, or energy)",
      default: "550 nm",
      placeholder: "2.45 GHz, 550 nm, 10 keV",
    },
  ],
  http: { method: "GET", contentType: "application/json" },
  copy: {
    what: "Two references in one page. The top half is a single interactive chart of the whole electromagnetic spectrum, drawn to scale on a log frequency axis from gamma rays down to ELF radio, with live frequency, wavelength, photon energy, black-body temperature and color readouts. The bottom half is a spectrum allocation reference: a zoomable chart of who is allocated what in the United States (with ITU region views), amateur band privileges by license class, broadcast, aviation, maritime, cellular, satellite, GPS, radar and radio astronomy bands, the unlicensed and ISM bands, channel tables for Wi-Fi, Zigbee, Thread, LoRa, Bluetooth, DECT, FRS, GMRS and MURS, plain English licensing rules per frequency, an FCC RF exposure calculator, and short notes on how each part of the spectrum propagates and what it does to people.",
    how: "Hover or tap the spectrum to read values, drag across it to zoom, and pan by scrolling. The search box takes a frequency (915 MHz), a wavelength (21 cm), a photon energy (10 keV), a band (2m, 70cm, 6 GHz), a service (radio astronomy), or a channel (wifi 36, zigbee 15, GMRS 19, marine 16) and jumps to it. The allocation chart below shares the same axis: pick a region, click a band for its range, rules, notes and source, and export the visible rows as CSV or JSON. The Rules tab answers whether you may transmit at the selected frequency. The Channels tab lists every fixed channel plan with a show-on-spectrum action. The Exposure tab takes a power, an antenna gain, a distance and an environment and compares the far field power density against the FCC limit. Everything runs in your browser, so your files and inputs never leave your device.",
    why: "Most spectrum charts are static posters, and the FCC allocation table is a 150 page PDF of footnotes. This tool puts the physics chart and the regulatory chart on one zoomable axis, cites a source for every row, spells out the amateur sub band privileges from 47 CFR 97, and computes the exposure limit from the actual 47 CFR 1.1310 formulas instead of a lookup image. It is free of ads, sign up walls and export limits, and it never phones home.",
    faq: [
      {
        q: "How do you convert between frequency, wavelength, and energy?",
        a: "Wavelength is the speed of light divided by frequency. Photon energy is Planck constant times frequency, shown in electronvolts by dividing by the elementary charge. The chart uses the exact 2019 SI values for these constants, so a green photon near 550 nm reads as about 545 THz and 2.25 eV.",
      },
      {
        q: "Where does the allocation data come from, and can I rely on it?",
        a: "It is a hand curated summary of the FCC Table of Frequency Allocations (47 CFR 2.106), the NTIA manual for federal bands, the service rules in FCC Parts 15, 73, 80, 87, 90, 95 and 97, the ITU Radio Regulations for regional differences, and the 3GPP band tables for cellular. Every row carries its source. It collapses co-primary services and omits footnotes and geographic restrictions, so treat it as a map, not as the rulebook: the CFR governs.",
      },
      {
        q: "What do primary, secondary, unlicensed and restricted mean?",
        a: "A primary service is protected from interference and may not be interfered with. A secondary service may operate but must accept interference from primary users and never cause it. Unlicensed means anyone may transmit with certified equipment under a power limit, no license needed, as in the ISM and Wi-Fi bands. Restricted marks bands where transmitting is prohibited or tightly limited, usually to protect passive users like radio astronomy.",
      },
      {
        q: "Which amateur bands can a Technician use?",
        a: "Every band from 6 m (50 MHz) up, plus small slices of 10 m (28.0 to 28.5 MHz), 15 m, 40 m and 80 m for CW, and 28.3 to 28.5 MHz for SSB voice. General adds most of HF, and Extra has everything. Select any amateur band on the chart and the Rules tab lists the sub band privileges by class, taken from 47 CFR 97.301 and 97.305.",
      },
      {
        q: "Is the RF exposure calculator a compliance evaluation?",
        a: "No. It applies the far field formula S = EIRP / (4 pi R squared) and compares the result with the maximum permissible exposure limit in 47 CFR 1.1310, and it checks the single source exemption threshold in 47 CFR 1.1307(b). Real evaluations account for antenna patterns, ground reflection, the near field and multiple sources. Use it to see whether a station is nowhere near the limit or worth evaluating properly.",
      },
      {
        q: "What counts as ionizing radiation here?",
        a: "The chart flags radiation as ionizing at or above about 10 electronvolts, which is roughly the hard ultraviolet boundary and up through X-rays and gamma rays. The real threshold is not a sharp line: it depends on the molecule and sits somewhere between 10 and 33 eV, so the flag is labeled as approximate.",
      },
      {
        q: "Why are Wi-Fi and FM radio in different top level bands?",
        a: "The chart nests the ITU bands under two top level groups: Radio holds ELF through VHF (3 Hz to 300 MHz), and Microwave holds UHF, SHF, and EHF (300 MHz to 300 GHz), because those upper ITU bands are exactly the microwave region. FM broadcast at 88 to 108 MHz sits in VHF under Radio, while 2.4 GHz Wi-Fi sits in UHF under Microwave.",
      },
    ],
  },
};
