import { ToolError, type ToolLogic } from "../types";
import {
  LEVEL_XP_THRESHOLDS,
  VILLAGER_DATA,
  VILLAGER_VERSIONS,
  type GossipRule,
  type TradeRow,
} from "./data";

/**
 * Villager trading, reputation and price engine over the real per-version
 * trade tables (see data.ts, generated by mc-pipeline/11-emit-villager-data.mjs).
 *
 * Everything below is a reimplementation from the decompiled server source
 * under mc-pipeline/work/<version>/src/, never a transcription:
 *
 * - MerchantOffer.getModifiedCostCount: the shown price is
 *   clamp(base + max(0, floor(base * demand * priceMultiplier)) + specialPriceDiff,
 *   1, the COST ITEM's max stack size). Identical in all six shipped versions.
 *   The upper clamp is not a flat 64, which is why the librarian's Expert
 *   "2 book and quill for 1 emerald" listing only ever charges one book: the
 *   item stacks to 1.
 * - TradeCost.toItemCost (26.x only): when the offer is built from registry
 *   data the cost is ALSO clamped to the cost item's stack size, so 26.x
 *   stores a base cost of 1 for that same trade where earlier versions store
 *   the unclamped 2. Both charge the player one book and quill.
 * - MerchantOffer.updateDemand: demand += uses - (maxUses - uses), applied once
 *   per restock. It is not clamped, so under-trading buffers demand negative
 *   and only the price term floors at zero.
 * - Villager.updateSpecialPrices: specialPriceDiff gets -floor(reputation *
 *   priceMultiplier) when reputation is non-zero, and additionally
 *   -max(floor((0.3 + 0.0625 * amplifier) * base), 1) while the player has
 *   Hero of the Village. Identical in all six shipped versions.
 * - Villager.onReputationEventFrom: curing a zombie villager adds 20
 *   MAJOR_POSITIVE and 25 MINOR_POSITIVE gossip, a trade adds 2 TRADING,
 *   hurting a villager adds 25 MINOR_NEGATIVE, killing one adds 25
 *   MAJOR_NEGATIVE. Identical in all six shipped versions.
 * - GossipContainer.mergeValuesForAddition / makeSureValueIsntTooLowOrTooHigh:
 *   a gossip value is capped at its type's max, and dropped entirely once it
 *   falls below 2. GossipContainer.EntityGossips.decay subtracts decayPerDay
 *   once every 24000 ticks the villager is loaded.
 * - GossipType: THIS is where the 1.20.2 cure nerf lives. MAJOR_POSITIVE went
 *   from max 100 to max 20 and MINOR_POSITIVE from max 200 to max 25, so
 *   stacking cures stopped paying after the first one. The cure amounts
 *   themselves never changed.
 * - Villager.allowedToRestock / shouldRestock: at most two restocks per day,
 *   the second no sooner than 2400 ticks after the first, and the counter
 *   resets on a new day or 12000 ticks after the last restock.
 */

// ------------------------------------------------------------- constants --

/** Villager levels, index 0 is level 1. */
export const LEVEL_NAMES = ["Novice", "Apprentice", "Journeyman", "Expert", "Master"];

/** Display names and job site blocks, stable across every shipped version. */
export const PROFESSION_INFO: Record<string, { name: string; station: string }> = {
  armorer: { name: "Armorer", station: "Blast Furnace" },
  butcher: { name: "Butcher", station: "Smoker" },
  cartographer: { name: "Cartographer", station: "Cartography Table" },
  cleric: { name: "Cleric", station: "Brewing Stand" },
  farmer: { name: "Farmer", station: "Composter" },
  fisherman: { name: "Fisherman", station: "Barrel" },
  fletcher: { name: "Fletcher", station: "Fletching Table" },
  leatherworker: { name: "Leatherworker", station: "Cauldron" },
  librarian: { name: "Librarian", station: "Lectern" },
  mason: { name: "Mason", station: "Stonecutter" },
  shepherd: { name: "Shepherd", station: "Loom" },
  toolsmith: { name: "Toolsmith", station: "Smithing Table" },
  weaponsmith: { name: "Weaponsmith", station: "Grindstone" },
};

/** Gossip added per event (Villager.onReputationEventFrom). */
export const GOSSIP_PER_CURE_MAJOR = 20;
export const GOSSIP_PER_CURE_MINOR = 25;
export const GOSSIP_PER_TRADE = 2;
export const GOSSIP_PER_HURT = 25;
export const GOSSIP_PER_KILL = 25;

/** A gossip value below this is dropped (GossipContainer.DISCARD_THRESHOLD). */
const DISCARD_THRESHOLD = 2;

/** Emeralds and every other trade cost item stack to 64. */
const MAX_STACK = 64;

/** Ticks in a Minecraft day, and the restock cooldown between the two daily restocks. */
export const TICKS_PER_DAY = 24000;
export const RESTOCK_COOLDOWN_TICKS = 2400;
export const MAX_RESTOCKS_PER_DAY = 2;

// ----------------------------------------------------------------- types --

export interface VillagerOptions {
  version: string;
  profession: string;
  /** 1 to 5. */
  level: number;
  /** Index into the level's trade pool; -1 selects nothing. */
  tradeIndex?: number;
  /** Hero of the Village level, 1 to 5. 0 means the effect is not active. */
  heroLevel?: number;
  /** Zombie villagers of this villager cured by this player. */
  cures?: number;
  /** Successful trades this player has made with this villager. */
  tradesMade?: number;
  /** Villagers this player has hurt in front of this villager. */
  hurts?: number;
  /** Villagers this player has killed in front of this villager. */
  kills?: number;
  /** Days of gossip decay applied since the reputation was earned. */
  daysElapsed?: number;
  /** Uses of the selected trade between restocks, for the demand term. */
  usesPerRestock?: number;
  /** Restocks that have happened at that usage rate. */
  restocks?: number;
  /** Base price to price up for a randomised trade, like an enchanted book. */
  rolledPrice?: number;
}

export interface GossipLine {
  type: string;
  label: string;
  /** Stored gossip value after caps and decay. */
  value: number;
  weight: number;
  /** value * weight, the contribution to reputation. */
  points: number;
  /** Days until decay drops this value below the discard threshold, null when it never decays. */
  daysRemaining: number | null;
}

export interface PricedTrade {
  index: number;
  /** Stable across versions, see tradeIdentity(). */
  identity: string;
  label: string;
  wants: string;
  wantsName: string;
  /** Base cost before discounts. Randomised trades have a real range. */
  baseMin: number;
  baseMax: number;
  gives: string;
  givesName: string;
  givesCount: number;
  secondary: { item: string; name: string; count: number } | null;
  maxUses: number;
  xp: number;
  priceMultiplier: number;
  /** Villager types that offer this trade; empty means every type. */
  biomes: string[];
  /** "book", "enchanted", "dyed", "map", "stew", "arrow", "type" or "". */
  variable: string;
  /** Final shown price, after reputation, Hero of the Village and demand. */
  priceMin: number;
  priceMax: number;
  savedMin: number;
  savedMax: number;
  /** False when priceMultiplier is 0, which makes the trade undiscountable. */
  discountable: boolean;
}

export interface MendingAnswer {
  /** Base price of the rolled book being priced. */
  rolledPrice: number;
  /** Cures needed to reach 1 emerald with the chosen Hero of the Village level, null when unreachable. */
  curesNeeded: number | null;
  /** Cures needed with no Hero of the Village, null when unreachable. */
  curesNeededNoHero: number | null;
  /** Best price cures alone can reach, at the version's gossip caps. */
  bestCureOnlyPrice: number;
  /** Best price cures plus Hero of the Village V can reach. */
  bestPriceWithHero: number;
  /** Cures past this point add nothing, because the gossip caps are reached. */
  curesUntilCapped: number;
  explanation: string;
}

export interface RestockInfo {
  maxRestocksPerDay: number;
  cooldownTicks: number;
  /** Real-time seconds between the two daily restocks. */
  cooldownSeconds: number;
  /** Uses of the selected trade available per day at full restocks. */
  usesPerDay: number;
  demand: number;
  demandPerRestock: number;
  /** Uses per restock at which demand stops falling and starts rising. */
  breakEvenUses: number;
  /** Uses per restock needed before the price rises by at least one item. */
  usesBeforePriceRises: number | null;
}

export interface VillagerResult {
  version: string;
  profession: string;
  professionName: string;
  station: string;
  level: number;
  levelName: string;
  /** Trades this villager rolls at this level. */
  offered: number;
  xpToLevel: number;
  reputation: number;
  gossip: GossipLine[];
  heroLevel: number;
  heroAmplifier: number;
  demand: number;
  trades: PricedTrade[];
  selected: PricedTrade | null;
  mending: MendingAnswer | null;
  restock: RestockInfo;
  /** Post-1.20.2 gossip caps, the headline version boundary. */
  cureNerfApplies: boolean;
  notes: string[];
}

// ------------------------------------------------------------- utilities --

/** "golden_carrot" -> "Golden Carrot". */
export function itemName(id: string): string {
  return id
    .split("_")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

function versionData(version: string) {
  const data = VILLAGER_DATA[version];
  if (!data) {
    throw new ToolError(
      "unknown-version",
      `No villager data for Minecraft ${version}.`,
      `Pick one of: ${VILLAGER_VERSIONS.join(", ")}.`,
    );
  }
  return data;
}

/** Professions that have trades in this version, sorted by display name. */
export function professionsFor(version: string): string[] {
  return Object.keys(versionData(version).professions).sort((a, b) =>
    (PROFESSION_INFO[a]?.name ?? a).localeCompare(PROFESSION_INFO[b]?.name ?? b),
  );
}

/**
 * A trade's identity, stable across versions.
 *
 * Pool order and pool contents both move between versions, so a list index is
 * not a usable handle. What does survive is what the trade costs, what it
 * hands over, and which villager types offer it. A few pools hold rows that
 * agree on all of that and differ only in something this tool does not model
 * (the six suspicious stew effects, the two Journeyman explorer map
 * destinations), so an occurrence ordinal disambiguates them. Costs and counts
 * are deliberately left out: they are exactly the things that get rebalanced.
 */
export function tradeIdentity(pool: TradeRow[], index: number): string {
  const row = pool[index];
  if (!row) return "";
  const key = `${row[0]}|${row[8]}|${row[3]}|${row[11]}`;
  let ordinal = 0;
  for (let i = 0; i < index; i++) {
    const other = pool[i];
    if (`${other[0]}|${other[8]}|${other[3]}|${other[11]}` === key) ordinal++;
  }
  return `${key}#${ordinal}`;
}

/** Index of the trade with this identity, or -1 when the version dropped it. */
export function findTradeIndex(pool: TradeRow[], identity: string): number {
  for (let i = 0; i < pool.length; i++) if (tradeIdentity(pool, i) === identity) return i;
  return -1;
}

/**
 * Max stack size of an item in this version, which is the ceiling the price
 * formula clamps a trade cost to. Only items that do not stack to 64 are
 * shipped in the data, so anything else answers 64.
 */
export function stackSizeFor(version: string, item: string): number {
  return versionData(version).stacks[item] ?? MAX_STACK;
}

/** Raw pool rows for a profession level, as shipped. */
export function poolFor(version: string, profession: string, level: number): TradeRow[] {
  const data = versionData(version);
  const prof = data.professions[profession];
  if (!prof) {
    throw new ToolError(
      "unknown-profession",
      `Minecraft ${version} has no villager profession "${profession}".`,
      `Try one of: ${professionsFor(version).join(", ")}.`,
    );
  }
  if (!Number.isInteger(level) || level < 1 || level > 5) {
    throw new ToolError(
      "bad-level",
      `Villager level ${level} does not exist.`,
      "Levels run from 1 (Novice) to 5 (Master).",
    );
  }
  return prof.levels[String(level)] ?? [];
}

export interface Selection {
  version: string;
  profession: string;
  level: number;
  tradeIndex: number;
  /** 0 when no specific roll is pinned. */
  rolledPrice: number;
}

export interface CarriedSelection {
  tradeIndex: number;
  rolledPrice: number;
  /** True when the same trade exists in the target version. */
  preserved: boolean;
  /** The rolled price before it was moved into the new range, when it moved. */
  clampedFrom: number | null;
  /** Plain explanation of anything the version change had to change. */
  message: string | null;
}

/**
 * Move a selected trade from one version to another.
 *
 * Switching versions must not silently drop what the user picked. The trade is
 * matched by identity rather than by list index, and a pinned roll is carried
 * over and clamped into the new version's range rather than discarded, since
 * rebalances move prices without removing the trade. Only a trade the target
 * version genuinely does not have falls back, and it says so.
 */
export function carrySelection(from: Selection, toVersion: string): CarriedSelection {
  const fallback: CarriedSelection = {
    tradeIndex: 0,
    rolledPrice: 0,
    preserved: false,
    clampedFrom: null,
    message: null,
  };

  let fromPool: TradeRow[];
  let toPool: TradeRow[];
  try {
    fromPool = poolFor(from.version, from.profession, from.level);
    toPool = poolFor(toVersion, from.profession, from.level);
  } catch {
    return {
      ...fallback,
      message: `${PROFESSION_INFO[from.profession]?.name ?? from.profession} has no trades at this level in Minecraft ${toVersion}, so the selection was reset.`,
    };
  }

  const identity = tradeIdentity(fromPool, from.tradeIndex);
  const target = identity ? findTradeIndex(toPool, identity) : -1;
  if (target < 0) {
    const previous = fromPool[from.tradeIndex];
    const label = previous ? `${itemName(previous[0])} for ${itemName(previous[3])}` : "that trade";
    return {
      ...fallback,
      message: `Minecraft ${toVersion} has no ${label} trade here, so the first trade is selected instead.`,
    };
  }

  const row = toPool[target];
  const rolls = row[1] !== row[2];
  if (!from.rolledPrice || from.rolledPrice <= 0 || !rolls) {
    return {
      tradeIndex: target,
      rolledPrice: 0,
      preserved: true,
      clampedFrom: null,
      message: null,
    };
  }

  const clamped = Math.min(Math.max(from.rolledPrice, row[1]), row[2]);
  return {
    tradeIndex: target,
    rolledPrice: clamped,
    preserved: true,
    clampedFrom: clamped === from.rolledPrice ? null : from.rolledPrice,
    message:
      clamped === from.rolledPrice
        ? null
        : `Minecraft ${toVersion} prices this trade between ${row[1]} and ${row[2]}, so the pinned roll moved from ${from.rolledPrice} to ${clamped}.`,
  };
}

// ------------------------------------------------------------ reputation --

/** Value a gossip type holds after N events of `amount`, its cap, and `days` of decay. */
function gossipValue(rule: GossipRule, events: number, amount: number, days: number): number {
  if (events <= 0) return 0;
  const capped = Math.min(events * amount, rule.max);
  const decayed = capped - Math.max(0, days) * rule.decayPerDay;
  return decayed < DISCARD_THRESHOLD ? 0 : decayed;
}

/** Days until decay pushes a value below the discard threshold. Null when it never decays. */
function daysRemaining(rule: GossipRule, value: number): number | null {
  if (value <= 0) return 0;
  if (rule.decayPerDay <= 0) return null;
  return Math.ceil((value - DISCARD_THRESHOLD + 1) / rule.decayPerDay);
}

const GOSSIP_LABELS: Record<string, string> = {
  major_positive: "Major positive (zombie cure)",
  minor_positive: "Minor positive (zombie cure)",
  trading: "Trading",
  minor_negative: "Minor negative (villager hurt)",
  major_negative: "Major negative (villager killed)",
};

/** Reputation as the game computes it: the weighted sum of every gossip value. */
export function computeGossip(
  version: string,
  opts: Pick<VillagerOptions, "cures" | "tradesMade" | "hurts" | "kills" | "daysElapsed">,
): { lines: GossipLine[]; reputation: number } {
  const rules = versionData(version).gossip;
  const days = Math.max(0, Math.floor(opts.daysElapsed ?? 0));
  const events: Array<[string, number, number]> = [
    ["major_positive", Math.max(0, Math.floor(opts.cures ?? 0)), GOSSIP_PER_CURE_MAJOR],
    ["minor_positive", Math.max(0, Math.floor(opts.cures ?? 0)), GOSSIP_PER_CURE_MINOR],
    ["trading", Math.max(0, Math.floor(opts.tradesMade ?? 0)), GOSSIP_PER_TRADE],
    ["minor_negative", Math.max(0, Math.floor(opts.hurts ?? 0)), GOSSIP_PER_HURT],
    ["major_negative", Math.max(0, Math.floor(opts.kills ?? 0)), GOSSIP_PER_KILL],
  ];

  const lines: GossipLine[] = [];
  let reputation = 0;
  for (const [type, count, amount] of events) {
    const rule = rules[type];
    const value = gossipValue(rule, count, amount, days);
    const points = value * rule.weight;
    reputation += points;
    lines.push({
      type,
      label: GOSSIP_LABELS[type] ?? type,
      value,
      weight: rule.weight,
      points,
      daysRemaining: value > 0 ? daysRemaining(rule, value) : 0,
    });
  }
  return { lines, reputation };
}

// ----------------------------------------------------------------- price --

export interface PriceInputs {
  base: number;
  priceMultiplier: number;
  reputation: number;
  /** Hero of the Village level, 1 to 5. 0 disables it. */
  heroLevel: number;
  demand: number;
  /** Max stack size of the COST item. Defaults to 64. */
  maxStack?: number;
}

/**
 * The number of items the trade actually asks for, exactly as the client shows
 * it: the demand surcharge, then the reputation and Hero of the Village
 * discounts, then a clamp into [1, the cost item's max stack size].
 *
 * The upper clamp is the COST ITEM's stack size, not a flat 64. That detail
 * decides one real trade: the librarian's Expert "2 book and quill for 1
 * emerald" listing asks for two of an item that stacks to one, so every
 * version charges a single book and quill.
 */
export function priceFor(inputs: PriceInputs): number {
  const base = Math.max(1, Math.floor(inputs.base));
  const mult = inputs.priceMultiplier;
  const demandTerm = Math.max(0, Math.floor(base * inputs.demand * mult));

  let special = 0;
  if (inputs.reputation !== 0) special -= Math.floor(inputs.reputation * mult);
  if (inputs.heroLevel > 0) {
    const amplifier = inputs.heroLevel - 1;
    special -= Math.max(Math.floor((0.3 + 0.0625 * amplifier) * base), 1);
  }

  const cap = inputs.maxStack ?? MAX_STACK;
  return Math.min(Math.max(base + demandTerm + special, 1), cap);
}

// ------------------------------------------------------------- mending Q --

/**
 * Cures needed to floor a rolled enchanted book to one emerald.
 *
 * Answered exactly rather than by search intent: for each cure count the
 * reputation is recomputed under this version's gossip caps and run through
 * the real price formula. Curing past the caps changes nothing, so the search
 * stops there and reports "not reachable" honestly instead of guessing.
 */
export function curesForOneEmerald(
  version: string,
  rolledPrice: number,
  heroLevel: number,
  priceMultiplier = 0.2,
): MendingAnswer {
  const rules = versionData(version).gossip;
  const base = Math.min(Math.max(1, Math.floor(rolledPrice)), MAX_STACK);
  const capMajor = Math.ceil(rules.major_positive.max / GOSSIP_PER_CURE_MAJOR);
  const capMinor = Math.ceil(rules.minor_positive.max / GOSSIP_PER_CURE_MINOR);
  const curesUntilCapped = Math.max(capMajor, capMinor);

  const priceAfter = (cures: number, hero: number): number => {
    const { reputation } = computeGossip(version, { cures });
    return priceFor({ base, priceMultiplier, reputation, heroLevel: hero, demand: 0 });
  };

  const search = (hero: number): number | null => {
    for (let cures = 0; cures <= curesUntilCapped; cures++) {
      if (priceAfter(cures, hero) <= 1) return cures;
    }
    return null;
  };

  const curesNeeded = search(Math.max(0, Math.min(5, heroLevel)));
  const curesNeededNoHero = search(0);
  const bestCureOnlyPrice = priceAfter(curesUntilCapped, 0);
  const bestPriceWithHero = priceAfter(curesUntilCapped, 5);

  let explanation: string;
  if (curesNeeded === 0) {
    explanation = `A ${base} emerald book already costs 1 emerald with this setup.`;
  } else if (curesNeeded !== null) {
    explanation = `${curesNeeded} ${curesNeeded === 1 ? "cure" : "cures"} takes a ${base} emerald book to 1 emerald.`;
  } else if (bestPriceWithHero <= 1) {
    explanation = `Curing alone bottoms out at ${bestCureOnlyPrice} emeralds in this version. Hero of the Village V closes the gap.`;
  } else {
    explanation = `Curing plus Hero of the Village V still leaves this book at ${bestPriceWithHero} emeralds in this version.`;
  }

  return {
    rolledPrice: base,
    curesNeeded,
    curesNeededNoHero,
    bestCureOnlyPrice,
    bestPriceWithHero,
    curesUntilCapped,
    explanation,
  };
}

// -------------------------------------------------------------- restocks --

function restockInfo(
  trade: PricedTrade | null,
  usesPerRestock: number,
  restocks: number,
): RestockInfo {
  const maxUses = trade?.maxUses ?? 0;
  const demandPerRestock = 2 * usesPerRestock - maxUses;
  const demand = restocks * demandPerRestock;
  const base = trade?.baseMin ?? 0;
  const mult = trade?.priceMultiplier ?? 0;

  // The demand surcharge is floor(base * demand * mult), so it stays at zero
  // until demand reaches 1 / (base * mult).
  let usesBeforePriceRises: number | null = null;
  if (trade && base > 0 && mult > 0) {
    const demandForOne = Math.ceil(1 / (base * mult));
    const uses = Math.ceil((demandForOne + maxUses) / 2);
    usesBeforePriceRises = uses <= maxUses ? uses : null;
  }

  return {
    maxRestocksPerDay: MAX_RESTOCKS_PER_DAY,
    cooldownTicks: RESTOCK_COOLDOWN_TICKS,
    cooldownSeconds: RESTOCK_COOLDOWN_TICKS / 20,
    usesPerDay: maxUses * (MAX_RESTOCKS_PER_DAY + 1),
    demand,
    demandPerRestock,
    breakEvenUses: maxUses / 2,
    usesBeforePriceRises,
  };
}

// -------------------------------------------------------------- calculate --

function priceTrade(
  version: string,
  pool: TradeRow[],
  index: number,
  reputation: number,
  heroLevel: number,
  demand: number,
  rolledPrice?: number,
): PricedTrade {
  const row = pool[index];
  const [wants, wMinRaw, wMaxRaw, gives, gCount, maxUses, xp, mult, w2, w2Count, variable, biomes] =
    row;
  const hasRoll = typeof rolledPrice === "number" && Number.isFinite(rolledPrice);
  const baseMin = hasRoll ? Math.min(Math.max(rolledPrice, wMinRaw), wMaxRaw) : wMinRaw;
  const baseMax = hasRoll ? baseMin : wMaxRaw;

  const maxStack = stackSizeFor(version, wants);
  const inputs = { priceMultiplier: mult, reputation, heroLevel, demand, maxStack };
  const priceMin = priceFor({ ...inputs, base: baseMin });
  const priceMax = priceFor({ ...inputs, base: baseMax });

  const wantsName = itemName(wants);
  const givesName = itemName(gives);
  const costLabel =
    baseMin === baseMax ? `${baseMin} ${wantsName}` : `${baseMin} to ${baseMax} ${wantsName}`;
  const secondLabel = w2 ? ` plus ${w2Count} ${itemName(w2)}` : "";
  const label = `${costLabel}${secondLabel} for ${gCount} ${givesName}`;

  return {
    index,
    identity: tradeIdentity(pool, index),
    label,
    wants,
    wantsName,
    baseMin,
    baseMax,
    gives,
    givesName,
    givesCount: gCount,
    secondary: w2 ? { item: w2, name: itemName(w2), count: w2Count } : null,
    maxUses,
    xp,
    priceMultiplier: mult,
    biomes: biomes ? biomes.split(",") : [],
    variable,
    priceMin,
    priceMax,
    savedMin: baseMin - priceMin,
    savedMax: baseMax - priceMax,
    discountable: mult > 0,
  };
}

export function calculate(opts: VillagerOptions): VillagerResult {
  const version = opts.version;
  const data = versionData(version);
  const profession = opts.profession;
  const level = opts.level;
  const pool = poolFor(version, profession, level);

  const heroLevel = Math.max(0, Math.min(5, Math.floor(opts.heroLevel ?? 0)));
  const { lines, reputation } = computeGossip(version, opts);

  const usesPerRestock = Math.max(0, Math.floor(opts.usesPerRestock ?? 0));
  const restocks = Math.max(0, Math.floor(opts.restocks ?? 0));

  const index = opts.tradeIndex ?? 0;
  const selectedRow = index >= 0 && index < pool.length ? pool[index] : null;
  const demand = selectedRow ? restocks * (2 * usesPerRestock - selectedRow[5]) : 0;

  const trades = pool.map((row, i) =>
    priceTrade(
      version,
      pool,
      i,
      reputation,
      heroLevel,
      i === index ? demand : 0,
      i === index ? opts.rolledPrice : undefined,
    ),
  );
  const selected = selectedRow ? trades[index] : null;

  const notes: string[] = [];
  const cureNerfApplies = data.gossip.major_positive.max <= GOSSIP_PER_CURE_MAJOR;
  if (cureNerfApplies) {
    notes.push(
      "Since 1.20.2 the major positive gossip cap is 20, so the first zombie cure gives the whole discount and later cures add nothing.",
    );
  } else {
    notes.push(
      "Before 1.20.2 the major positive gossip cap was 100, so up to five zombie cures stacked into a much deeper discount.",
    );
  }
  if (selected && !selected.discountable) {
    notes.push(
      "This trade has a price multiplier of zero, so reputation and Hero of the Village cannot change its price.",
    );
  }
  if (selected && selected.baseMin > stackSizeFor(version, selected.wants)) {
    const cap = stackSizeFor(version, selected.wants);
    notes.push(
      `${selected.wantsName} stacks to ${cap}, and a trade cost is clamped to the cost item's stack size, so this trade asks for ${selected.baseMin} but only ever charges ${cap}.`,
    );
  }
  if (selected?.variable === "book") {
    notes.push(
      "Enchanted book prices are rolled when the trade appears: 2 + random(5 + 10 x level) + 3 x level emeralds, doubled for treasure enchantments and capped at 64.",
    );
  }
  if (selected?.variable === "enchanted") {
    notes.push(
      "Enchanted gear prices are rolled when the trade appears: the base emerald cost plus the 5 to 19 enchanting levels rolled onto the item, capped at 64.",
    );
  }
  if (selected?.biomes.length) {
    notes.push(`This trade only appears on ${selected.biomes.map(itemName).join(", ")} villagers.`);
  }

  const mending =
    selected && selected.variable === "book"
      ? curesForOneEmerald(
          version,
          opts.rolledPrice ?? selected.baseMin,
          heroLevel,
          selected.priceMultiplier,
        )
      : null;

  return {
    version,
    profession,
    professionName: PROFESSION_INFO[profession]?.name ?? itemName(profession),
    station: PROFESSION_INFO[profession]?.station ?? "",
    level,
    levelName: LEVEL_NAMES[level - 1] ?? `Level ${level}`,
    offered: data.professions[profession]?.offered[level - 1] ?? 2,
    xpToLevel: LEVEL_XP_THRESHOLDS[level] ?? 0,
    reputation,
    gossip: lines,
    heroLevel,
    heroAmplifier: heroLevel > 0 ? heroLevel - 1 : 0,
    demand,
    trades,
    selected,
    mending,
    restock: restockInfo(selected, usesPerRestock, restocks),
    cureNerfApplies,
    notes,
  };
}

// ------------------------------------------------------------- run() API --

export interface VillagerRunOpts {
  version?: string;
  profession?: string;
  level?: number;
  tradeIndex?: number;
  heroLevel?: number;
  cures?: number;
  tradesMade?: number;
  hurts?: number;
  kills?: number;
  daysElapsed?: number;
  usesPerRestock?: number;
  restocks?: number;
  rolledPrice?: number;
  [key: string]: unknown;
}

export function run(input: string, opts: VillagerRunOpts): Record<string, string> {
  const version = opts.version ?? VILLAGER_VERSIONS[VILLAGER_VERSIONS.length - 1];
  const profession = (input || "").trim() || opts.profession || "librarian";
  const result = calculate({
    version,
    profession,
    level: Number(opts.level ?? 1),
    tradeIndex: Number(opts.tradeIndex ?? 0),
    heroLevel: Number(opts.heroLevel ?? 0),
    cures: Number(opts.cures ?? 0),
    tradesMade: Number(opts.tradesMade ?? 0),
    hurts: Number(opts.hurts ?? 0),
    kills: Number(opts.kills ?? 0),
    daysElapsed: Number(opts.daysElapsed ?? 0),
    usesPerRestock: Number(opts.usesPerRestock ?? 0),
    restocks: Number(opts.restocks ?? 0),
    rolledPrice: opts.rolledPrice === undefined ? undefined : Number(opts.rolledPrice),
  });

  const out: Record<string, string> = {};
  out["Villager"] =
    `${result.professionName} level ${result.level} (${result.levelName}) in Minecraft ${result.version}`;
  out["Reputation"] = String(result.reputation);
  if (!result.trades.length) {
    out["Trades"] = "This profession has no trades at this level.";
    return out;
  }
  for (const trade of result.trades) {
    const price =
      trade.priceMin === trade.priceMax
        ? `${trade.priceMin}`
        : `${trade.priceMin} to ${trade.priceMax}`;
    const base =
      trade.baseMin === trade.baseMax ? `${trade.baseMin}` : `${trade.baseMin} to ${trade.baseMax}`;
    out[`${trade.index + 1}. ${trade.label}`] =
      `costs ${price} ${trade.wantsName} (base ${base}), ${trade.maxUses} uses per restock, ${trade.xp} villager XP`;
  }
  if (result.mending) out["Cures for a 1 emerald book"] = result.mending.explanation;
  out["Notes"] = result.notes.join(" ");
  return out;
}

export default { run } satisfies ToolLogic<string, Record<string, string>, VillagerRunOpts>;
