import type { ToolMeta } from "../types";
import { VILLAGER_VERSIONS } from "./data";

const VERSION_SYNONYMS: Record<string, string[]> = {
  "1.16.5": ["nether update", "1.16"],
  "1.18.2": ["caves and cliffs", "1.18"],
  "1.20.6": ["trails and tales", "1.20", "cure nerf"],
  "1.21.1": ["tricky trials", "1.21"],
  "1.21.11": ["1.21"],
  "26.2": ["latest", "newest", "current"],
};

const PROFESSION_OPTIONS = [
  { value: "armorer", label: "Armorer", synonyms: ["blast furnace", "armor", "diamond armor"] },
  { value: "butcher", label: "Butcher", synonyms: ["smoker", "meat", "cooked porkchop"] },
  {
    value: "cartographer",
    label: "Cartographer",
    synonyms: ["cartography table", "map", "explorer map"],
  },
  {
    value: "cleric",
    label: "Cleric",
    synonyms: ["brewing stand", "ender pearl", "rotten flesh", "lapis"],
  },
  { value: "farmer", label: "Farmer", synonyms: ["composter", "wheat", "crops", "golden carrot"] },
  { value: "fisherman", label: "Fisherman", synonyms: ["barrel", "fish", "boat", "fishing rod"] },
  {
    value: "fletcher",
    label: "Fletcher",
    synonyms: ["fletching table", "arrow", "bow", "crossbow", "stick"],
  },
  {
    value: "leatherworker",
    label: "Leatherworker",
    synonyms: ["cauldron", "leather", "saddle", "dyed armor"],
  },
  {
    value: "librarian",
    label: "Librarian",
    synonyms: ["lectern", "enchanted book", "mending", "paper"],
  },
  {
    value: "mason",
    label: "Mason",
    synonyms: ["stonecutter", "clay", "quartz", "terracotta", "stone"],
  },
  {
    value: "shepherd",
    label: "Shepherd",
    synonyms: ["loom", "wool", "dye", "bed", "banner", "painting"],
  },
  {
    value: "toolsmith",
    label: "Toolsmith",
    synonyms: ["smithing table", "pickaxe", "axe", "diamond tools"],
  },
  {
    value: "weaponsmith",
    label: "Weaponsmith",
    synonyms: ["grindstone", "sword", "axe", "diamond sword"],
  },
];

export const meta: ToolMeta = {
  slug: "minecraft-villager-trade-calculator",
  matrixSlug: "minecraft-villager",
  icon: "HandCoins",
  name: "Minecraft Villager Trade and Discount Calculator",
  description:
    "Real per-version villager trades with the exact price after zombie cures, Hero of the Village, and demand.",
  category: "Minecraft",
  keywords: [
    "minecraft villager trade calculator",
    "minecraft villager discount calculator",
    "minecraft zombie villager cure discount",
    "minecraft 1 emerald mending book",
    "minecraft hero of the village discount",
    "minecraft villager reputation gossip",
    "minecraft villager restock and demand",
  ],
  searchTerms: [
    "cure discount stacking",
    "1.20.2 villager nerf",
    "how many cures for mending",
    "villager prices went up",
    "librarian mending trade",
    "villager gossip decay",
    "major positive gossip cap",
    "emerald price multiplier",
    "villager trade table by level",
    "villager restock twice a day",
    "trading hall planner",
    "villager breeder setup discount",
    "how many emeralds for mending book",
    "villager price calculator",
    "wandering trader",
    "job site block",
    "curing a zombie villager",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "version",
      label: "Minecraft version",
      default: VILLAGER_VERSIONS[VILLAGER_VERSIONS.length - 1],
      options: VILLAGER_VERSIONS.map((v) => ({
        value: v,
        label: v,
        synonyms: VERSION_SYNONYMS[v] ?? [],
      })),
    },
    {
      kind: "select",
      id: "profession",
      label: "Profession",
      default: "librarian",
      options: PROFESSION_OPTIONS,
    },
    { kind: "number", id: "level", label: "Villager level", default: 1, min: 1, max: 5, step: 1 },
    {
      kind: "number",
      id: "tradeIndex",
      label: "Trade number",
      default: 0,
      min: 0,
      max: 40,
      step: 1,
    },
    { kind: "number", id: "cures", label: "Zombie cures", default: 0, min: 0, max: 10, step: 1 },
    {
      kind: "number",
      id: "heroLevel",
      label: "Hero of the Village level",
      default: 0,
      min: 0,
      max: 5,
      step: 1,
    },
    {
      kind: "number",
      id: "tradesMade",
      label: "Trades already made",
      default: 0,
      min: 0,
      max: 64,
      step: 1,
    },
    { kind: "number", id: "hurts", label: "Villagers hurt", default: 0, min: 0, max: 20, step: 1 },
    {
      kind: "number",
      id: "kills",
      label: "Villagers killed",
      default: 0,
      min: 0,
      max: 20,
      step: 1,
    },
    {
      kind: "number",
      id: "daysElapsed",
      label: "Days of gossip decay",
      default: 0,
      min: 0,
      max: 60,
      step: 1,
    },
    {
      kind: "number",
      id: "usesPerRestock",
      label: "Uses between restocks",
      default: 0,
      min: 0,
      max: 16,
      step: 1,
    },
    {
      kind: "number",
      id: "restocks",
      label: "Restocks so far",
      default: 0,
      min: 0,
      max: 30,
      step: 1,
    },
    {
      kind: "number",
      id: "rolledPrice",
      label: "Rolled book price",
      default: 0,
      min: 0,
      max: 64,
      step: 1,
    },
  ],
  copy: {
    what: "Shows every trade a villager profession offers at each level in Minecraft 1.16.5, 1.18.2, 1.20.6, 1.21.1, 1.21.11, and 26.2, then prices each one exactly the way the game does: base cost, plus the demand surcharge from heavy trading, minus the reputation discount from zombie cures and trading, minus the Hero of the Village discount. It answers the question people actually search for, how many times you must cure a villager to get a one emerald Mending book, per version and per rolled book price. It also models the gossip system itself: the value each cure or trade adds, the cap on each gossip type, and how many in game days the discount survives. Version boundaries it models: 1.20.2 cut the zombie cure gossip caps (major positive 100 to 20, minor positive 200 to 25), which is the whole cure nerf; between 1.18.2 and 1.20.6 the scute became the turtle scute and the cartographer gained a second explorer map at Journeyman; 1.20.6 and 1.21.1 have identical trade tables; 1.21.11 reworked the cartographer, making explorer maps and banners depend on the villager type and dropping paper and glass pane from 16 uses to 12; and 26.x moved the whole trade table out of code and into datapack data, repricing cake from 1 to 3 emeralds, replacing the librarian name tag with candles, and switching the cooked fish and flint trades so the discount lands on the input item rather than the emerald. 26.x also clamps a trade cost to the cost item stack size when the offer is built, so the librarian Expert listing that asks for 2 book and quill now stores a base of 1 where older versions store 2; every version still charges one, because the displayed cost was already clamped the same way. The price formula, the cure amounts and the restock rules have not changed in any of these versions. Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.",
    how: "Pick the version first, since it decides which trades exist and how far cure discounts stack. Choose a profession and a level, then pick a trade from the searchable list. Set your situation under Your standing in the same rail: cures done, Hero of the Village level, trades already made, days since you earned the reputation, and how hard you have been working the trade. The price tile updates live, and the link in your address bar carries the whole setup, so you can share a configured answer.",
    why: "Most villager calculators are a static wiki table with one price and no version awareness, which is exactly wrong for this mechanic: 1.20.2 cut the major positive gossip cap from 100 to 20, so advice written for older versions tells you to cure a librarian five times for a discount that a modern game gives you entirely on the first cure. Every number here comes from the trade tables and gossip constants inside each game version, and the tables were checked against real measurements: this site's test pipeline booted a dedicated server per version and summoned 200 villagers for every profession and every level, then read their generated trades back and compared them to the shipped data in both directions. It runs entirely in your browser, with no ads and no accounts, and your files and inputs never leave your device.",
    faq: [
      {
        q: "How many cures do I need for a one emerald Mending book?",
        a: "It depends on the version and on the price the book rolled at. In 1.20.2 and later, one cure is the whole discount: it gives reputation 125, worth 25 emeralds off a librarian trade, so any book that rolled at 26 emeralds or less drops to 1 and anything above that needs Hero of the Village as well. Before 1.20.2 the caps were far higher, so three cures took even a 64 emerald book down to 1. This calculator works out the exact answer for the price you actually rolled.",
      },
      {
        q: "What changed in 1.20.2?",
        a: "The gossip type limits. Curing a zombie villager still grants 20 major positive and 25 minor positive gossip, and the price formula did not move, but the cap on major positive fell from 100 to 20 and minor positive from 200 to 25. Reputation is the weighted sum of stored gossip, so a single cure now saturates both, and the second, third and fifth cures change nothing. That single constant change is the whole nerf.",
      },
      {
        q: "Why did my villager's prices go up on their own?",
        a: "Demand. Every restock adds uses minus remaining uses to the trade's demand counter, so buying a trade out repeatedly pushes demand up and the price with it, by floor(base cost x demand x price multiplier). Leaving the trade alone pushes demand back down, though the surcharge floors at zero rather than turning into a discount. A villager restocks at most twice a day, at least two minutes apart, and only if it can reach its job site block.",
      },
    ],
  },
};
