/**
 * Generates dist/sw.js after `astro build`.
 *
 * Precaches every built page and asset so tools work offline after first
 * load (PROJECT.md definition of done). Runtime strategy:
 *  - /_astro/* and /fonts/* are content-hashed or immutable: cache-first
 *  - navigations: network-first with cache fallback
 *  - /api/*: never cached (stateless server calls)
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(dist)
  .map((f) => '/' + relative(dist, f).split(sep).join('/'))
  .filter((f) => !f.startsWith('/og/')) // OG images are for crawlers, not offline use
  .map((f) => f.replace(/\/index\.html$/, '/').replace(/^\/index\.html$/, '/'));

const hash = createHash('sha256');
for (const f of files.toSorted()) hash.update(f);
// Content-derived version so unchanged deploys do not churn caches.
for (const f of walk(dist).toSorted()) hash.update(readFileSync(f));
const version = hash.digest('hex').slice(0, 12);

const sw = `/* generated by scripts/generate-sw.mjs */
const VERSION = 'v-${version}';
const PRECACHE = ${JSON.stringify(files, null, 0)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  if (url.pathname.startsWith('/api/')) return;

  if (url.pathname.startsWith('/_astro/') || url.pathname.startsWith('/fonts/')) {
    e.respondWith(
      caches.match(e.request).then(
        (hit) =>
          hit ||
          fetch(e.request).then((res) => {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(e.request, copy));
            return res;
          })
      )
    );
    return;
  }

  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request)
        .then((res) => {
          const copy = res.clone();
          caches.open(VERSION).then((c) => c.put(e.request, copy));
          return res;
        })
        .catch(() => caches.match(e.request).then((hit) => hit || caches.match('/')))
    );
    return;
  }

  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js generated: ${files.length} precached URLs, version v-${version}`);
