/**
 * Generates dist/sw.js after `astro build`.
 *
 * Precaches every built page and asset so tools work offline after first
 * load (PROJECT.md definition of done). Runtime strategy:
 *  - /_astro/* and /fonts/* are content-hashed or immutable: cache-first
 *  - navigations: network-first with cache fallback
 *  - /api/*: never cached (stateless server calls)
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

// Anything above this size is fetched on demand, never precached. The
// ffmpeg core chunks alone are ~30 MB; precaching them would force every
// first-time visitor to download the media engine from the homepage.
const PRECACHE_MAX_BYTES = 2 * 1024 * 1024;

const files = walk(dist)
  .filter((f) => statSync(f).size <= PRECACHE_MAX_BYTES)
  .map((f) => '/' + relative(dist, f).split(sep).join('/'))
  .filter((f) => !f.startsWith('/og/')) // OG images are for crawlers, not offline use
  .filter((f) => !f.endsWith('.wasm')) // engines download on demand, never on first visit
  // model weights, OCR data, and the pyodide runtime are opt-in downloads on their tool pages
  .filter((f) => !f.startsWith('/models/') && !f.startsWith('/tesseract/') && !f.startsWith('/pyodide/'))
  .map((f) => f.replace(/\/index\.html$/, '/').replace(/^\/index\.html$/, '/'));

const hash = createHash('sha256');
for (const f of files.toSorted()) hash.update(f);
// Content-derived version so unchanged deploys do not churn caches.
for (const f of walk(dist).toSorted()) hash.update(readFileSync(f));
const version = hash.digest('hex').slice(0, 12);

const sw = `/* generated by scripts/generate-sw.mjs */
const VERSION = 'v-${version}';
const PRECACHE = ${JSON.stringify(files, null, 0)};

// Web Share Target (POST) parks the shared payload here for one read by the
// /share page. It is a temporary hand-off slot, never a persistent store, and
// it must survive activation, so it is kept out of the version-cache cleanup.
const SHARE_CACHE = 'share-target-inbox';
const SHARE_META_KEY = '/__share/meta';

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k !== VERSION && k !== SHARE_CACHE).map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

// Receive a share: stash the form data, then 303-redirect to /share so the
// page can read it back with a plain GET navigation. Bytes stay on the device;
// this cache is same-origin Cache Storage, never a network call.
async function handleShare(request) {
  try {
    const form = await request.formData();
    const cache = await caches.open(SHARE_CACHE);
    // Clear any stale payload from a previous, unread share.
    for (const key of await cache.keys()) await cache.delete(key);

    const files = form.getAll('files').filter((f) => typeof f !== 'string' && f);
    const fileMeta = [];
    for (let i = 0; i < files.length; i += 1) {
      const file = files[i];
      const key = '/__share/file-' + i;
      const type = file.type || 'application/octet-stream';
      await cache.put(
        new Request(key),
        new Response(file, { headers: { 'Content-Type': type } })
      );
      fileMeta.push({ key, name: file.name || 'shared-file', type, size: file.size });
    }

    const meta = {
      title: form.get('title') || '',
      text: form.get('text') || '',
      url: form.get('url') || '',
      files: fileMeta,
    };
    await cache.put(
      new Request(SHARE_META_KEY),
      new Response(JSON.stringify(meta), { headers: { 'Content-Type': 'application/json' } })
    );
  } catch (err) {
    // Even if stashing failed, still land the user on /share (empty state).
  }
  return Response.redirect('/share', 303);
}

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method === 'POST' && url.origin === location.origin && url.pathname === '/share') {
    e.respondWith(handleShare(e.request));
    return;
  }
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  if (url.pathname.startsWith('/api/')) return;

  if (url.pathname.startsWith('/_astro/') || url.pathname.startsWith('/fonts/')) {
    e.respondWith(
      caches.match(e.request).then(
        (hit) =>
          hit ||
          fetch(e.request).then((res) => {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(e.request, copy));
            return res;
          })
      )
    );
    return;
  }

  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request)
        .then((res) => {
          const copy = res.clone();
          caches.open(VERSION).then((c) => c.put(e.request, copy));
          return res;
        })
        .catch(() => caches.match(e.request).then((hit) => hit || caches.match('/')))
    );
    return;
  }

  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js generated: ${files.length} precached URLs, version v-${version}`);
