import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "minecraft-elytra-calculator",
  matrixSlug: "minecraft-elytra",
  icon: "Feather",
  name: "Minecraft Elytra Flight Calculator",
  description:
    "Simulates elytra glide physics tick by tick: distance from any height, firework cruise speed, rockets per trip, and durability.",
  category: "Minecraft",
  keywords: [
    "minecraft elytra calculator",
    "minecraft elytra distance calculator",
    "how many fireworks to fly 1000 blocks",
    "minecraft elytra speed",
    "elytra durability calculator",
    "minecraft firework rocket calculator",
    "elytra glide ratio",
  ],
  searchTerms: [
    "elytra flight distance",
    "blocks per firework",
    "elytra how long does it last",
    "phantom membrane repair",
    "nether travel vs elytra",
    "elytra top speed blocks per second",
    "firework rocket damage to self",
    "elytra unbreaking mending",
    "how far can i glide from y 320",
    "elytra pitch angle best glide",
    "minecraft flying calculator",
    "firework rocket cost calculator",
    "elytra travel planner",
    "elytera calculator",
    "how to fly fast in minecraft",
    "elytra fall damage",
    "duration 3 firework rockets",
    "rocket cruise speed calculator",
    "elytra trip planner",
    "gunpowder needed for rockets",
  ],
  input: "none",
  output: "application/json",
  options: [
    {
      kind: "select",
      id: "mode",
      label: "Mode",
      default: "glide",
      options: [
        {
          value: "glide",
          label: "Glide from height",
          synonyms: ["glide", "no rockets", "distance", "how far", "drop", "tower jump"],
        },
        {
          value: "cruise",
          label: "Rocket cruise",
          synonyms: ["fireworks", "rockets", "speed", "blocks per rocket", "cruising"],
        },
        {
          value: "travel",
          label: "Trip planner",
          synonyms: ["coordinates", "travel", "nether", "portal", "how many rockets"],
        },
        {
          value: "durability",
          label: "Durability and repair",
          synonyms: ["durability", "mending", "unbreaking", "phantom membrane", "anvil"],
        },
        {
          value: "damage",
          label: "Firework damage to you",
          synonyms: ["damage", "explosion", "firework star", "hurt myself", "gotcha"],
        },
      ],
    },
    {
      kind: "select",
      id: "version",
      label: "Version",
      default: "1.21.11",
      options: [
        { value: "1.16.5", label: "1.16.5", synonyms: ["1 16 5", "nether update"] },
        { value: "1.18.2", label: "1.18.2", synonyms: ["1 18 2", "caves and cliffs"] },
        { value: "1.20.6", label: "1.20.6", synonyms: ["1 20 6", "trails and tales"] },
        { value: "1.21.1", label: "1.21.1", synonyms: ["1 21 1", "tricky trials"] },
        { value: "1.21.11", label: "1.21.11", synonyms: ["1 21 11", "glider component"] },
        { value: "26.2", label: "26.2 (latest)", synonyms: ["26 2", "latest", "current"] },
      ],
    },
    {
      kind: "number",
      id: "pitch",
      label: "Pitch in degrees (positive looks down)",
      default: 0,
      min: -90,
      max: 90,
      step: 0.5,
    },
    {
      kind: "number",
      id: "height",
      label: "Height above the landing spot (blocks)",
      default: 100,
      min: 1,
      max: 10000,
      step: 1,
    },
    {
      kind: "number",
      id: "flightDuration",
      label: "Firework flight duration (gunpowder per craft)",
      default: 1,
      min: 1,
      max: 3,
      step: 1,
    },
    {
      kind: "number",
      id: "targetX",
      label: "Target X",
      default: 10000,
      min: -30000000,
      max: 30000000,
      step: 1,
    },
    {
      kind: "number",
      id: "targetZ",
      label: "Target Z",
      default: 0,
      min: -30000000,
      max: 30000000,
      step: 1,
    },
    {
      kind: "number",
      id: "damage",
      label: "Elytra damage so far",
      default: 0,
      min: 0,
      max: 431,
      step: 1,
    },
    {
      kind: "number",
      id: "unbreaking",
      label: "Unbreaking level",
      default: 0,
      min: 0,
      max: 3,
      step: 1,
    },
    {
      kind: "number",
      id: "stars",
      label: "Firework stars in the rocket",
      default: 0,
      min: 0,
      max: 7,
      step: 1,
    },
    { kind: "boolean", id: "slowFalling", label: "Slow Falling effect", default: false },
  ],
  copy: {
    what: "A real per-tick simulator of elytra flight, not a fitted curve. It runs the same equations the game runs: the 0.08 gravity term, the lift that cancels three quarters of it at level pitch, the conversion of descent into forward speed, the pitch-up trade at 3.2 to 1, the 10 percent steering pull, and the 0.99 by 0.98 drag, then adds the firework rocket boost from the rocket entity itself. From that it answers the questions players actually ask: how far you glide from a given height at a given pitch, how fast you cruise with rockets chained back to back, how many blocks one rocket buys, how many rockets and how much gunpowder and paper a trip to some X and Z costs, whether the Nether at 8 to 1 beats flying it, how long an elytra lasts and what Unbreaking, Mending, and phantom membranes do to that, and how much a rocket with firework stars hurts you when it goes off. Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.",
    how: "Pick a mode, then set the two or three numbers it needs. Glide mode wants a launch height and a pitch and draws the whole flight path tick by tick; positive pitch looks down, exactly like the F3 screen. Rocket cruise wants a firework flight duration of 1, 2, or 3 gunpowder and reports the steady speed plus the blocks and materials each rocket buys. The trip planner takes the X and Z you want to reach and prices the Overworld flight against the Nether shortcut. Durability mode takes the damage already on your elytra and the Unbreaking level and reports flight time, distance, Mending upkeep, and membranes to repair. Everything lives in the page address, so a link reproduces your exact setup.",
    why: "Search results for elytra calculators are thin pages that quote one speed with no version, no pitch, and no method. This one simulates the flight instead, and it is honest about where the numbers come from: elytra gliding is player bound and cannot be driven on a headless server, so the physics was reimplemented from the decompiled and unobfuscated game code for 1.16.5, 1.18.2, 1.20.6, 1.21.1, 1.21.11, and 26.2 rather than measured in a live world. The steady state speeds are then cross-checked two ways: against closed forms solved by hand from the same equations, and against the projectile physics this project did measure on real servers, which shares the same delta movement, drag, and float widening. The version changelog is in the FAQ below. It runs in your browser with no ads, and your files and inputs never leave your device.",
    faq: [
      {
        q: "How many fireworks do I need to fly 1000 blocks?",
        a: "About 23 plain rockets. A flight duration 1 rocket boosts for 26.5 ticks on average and cruising at level pitch runs at 1.673 blocks per tick, so one rocket carries you 44.3 blocks, with a real spread of 35 to 54 blocks because the rocket lifetime rolls 10 times its duration plus two small random amounts. Since one craft is 3 rockets from 1 paper and 1 gunpowder, 1000 blocks costs about 8 paper and 8 gunpowder. Duration 3 rockets carry 77.8 blocks each, which saves paper but costs slightly more gunpowder per block.",
      },
      {
        q: "How fast is an elytra, and why does a dive make me faster?",
        a: "Gliding at level pitch settles at 1.510 blocks per tick forward and 0.149 down, a glide ratio of about 10 to 1. Chaining firework rockets raises that to 1.673 blocks per tick, or 33.5 blocks per second, because the rocket pulls your velocity toward 1.7 times your look direction while drag and gravity pull back. A dive beats both for a while: the game converts a tenth of your downward speed into forward speed every tick, so after diving at 45 degrees for 5 seconds and then levelling off you peak near 2.12 blocks per tick, about 40 percent above the level glide terminal, before drag brings you back down.",
      },
      {
        q: "How long does an elytra last, and did any of this change between versions?",
        a: "An elytra takes 1 damage every 20 ticks of flight and refuses to glide with 1 durability left, so a fresh one carries 431 points, or 7 minutes 11 seconds of continuous flight, about 14,400 blocks at rocket cruise. Unbreaking multiplies that by level plus one, at the full non-armor rate: the elytra is not an armor item and is not in the enchantable armor tag, so it does not take the 60 percent penalty real armor takes. Only Unbreaking, Mending, and the two curses can go on it. As for versions, the flight equations are identical in all six checked. What did change: 1.16.5 read the lift cosine from the game's float sine table and 1.18.2 switched to a plain cosine, 1.20.6 moved gravity from a hardcoded 0.08 to the gravity attribute whose default is 0.08 and moved a rocket's flight duration from an NBT tag to an item component, and somewhere between 1.21.1 and 1.21.11 the elytra stopped being a hardcoded item and became a data driven glider component, which also changed its rarity to epic and lets the flight durability hit land on any equipped glider.",
      },
    ],
  },
};
