import type { ToolMeta } from "../types";

export const meta: ToolMeta = {
  slug: "print-cost-calculator",
  matrixSlug: "print-cost",
  icon: "Printer",
  name: "3D Print Cost Calculator",
  description:
    "Filament and electricity cost for a single print, with optional labor, machine wear, and markup.",
  category: "3D Printing",
  keywords: [
    "3d print cost calculator",
    "filament cost calculator",
    "how much does a 3d print cost",
    "pla cost per gram",
    "3d printing electricity cost",
    "resin print cost calculator",
  ],
  searchTerms: [
    "print price calculator",
    "3d printing quote",
    "filament weight cost",
    "prusaslicer cost estimate",
    "cura filament cost",
    "spool price per gram",
    "3d print markup calculator",
  ],
  input: "text/plain",
  output: "application/json",
  inputOptional: {
    label: "Quick entry",
    hint: 'Optional. Paste the summary your slicer prints, with lines like "filament used [g] = 24.6" and an estimated printing time, and the filament and print time options above are read from it instead. Every price option still applies.',
  },
  http: { method: "GET", contentType: "application/json" },
  options: [
    {
      kind: "number",
      id: "grams",
      label: "Filament used (g)",
      default: 25,
      min: 0,
      max: 5000,
      step: 0.1,
    },
    {
      kind: "number",
      id: "meters",
      label: "Filament used (m, alternative)",
      default: 0,
      min: 0,
      max: 100000,
      step: 0.1,
    },
    {
      kind: "select",
      id: "material",
      label: "Material",
      default: "pla",
      options: [
        { value: "pla", label: "PLA", synonyms: ["polylactic acid"] },
        { value: "petg", label: "PETG", synonyms: ["polyethylene terephthalate glycol"] },
        { value: "abs", label: "ABS", synonyms: ["acrylonitrile butadiene styrene"] },
        {
          value: "tpu",
          label: "TPU",
          synonyms: ["thermoplastic polyurethane", "flexible filament"],
        },
        { value: "asa", label: "ASA", synonyms: ["acrylonitrile styrene acrylate"] },
        { value: "nylon", label: "Nylon", synonyms: ["polyamide", "pa"] },
        { value: "pc", label: "PC", synonyms: ["polycarbonate"] },
        { value: "resin", label: "Resin", synonyms: ["sla", "msla", "dlp", "photopolymer resin"] },
        {
          value: "custom",
          label: "Custom",
          synonyms: ["other filament", "unknown material", "specify density"],
        },
      ],
    },
    {
      kind: "number",
      id: "customDensity",
      label: "Custom density (g/cm3)",
      default: 1.24,
      min: 0.01,
      max: 30,
      step: 0.01,
    },
    {
      kind: "number",
      id: "filamentDiameter",
      label: "Filament diameter (mm)",
      default: 1.75,
      min: 0.1,
      max: 10,
      step: 0.05,
    },
    {
      kind: "number",
      id: "spoolPrice",
      label: "Spool price",
      default: 20,
      min: 0,
      max: 100000,
      step: 0.5,
    },
    {
      kind: "number",
      id: "spoolGrams",
      label: "Spool weight (g)",
      default: 1000,
      min: 1,
      max: 100000,
      step: 10,
    },
    {
      kind: "number",
      id: "hours",
      label: "Print time (hours)",
      default: 2,
      min: 0,
      max: 2000,
      step: 1,
    },
    {
      kind: "number",
      id: "minutes",
      label: "Print time (minutes)",
      default: 0,
      min: 0,
      max: 59,
      step: 1,
    },
    {
      kind: "number",
      id: "printerWatts",
      label: "Average printer draw (W)",
      default: 120,
      min: 0,
      max: 20000,
      step: 5,
    },
    {
      kind: "number",
      id: "kwhPrice",
      label: "Electricity price ($/kWh)",
      default: 0.15,
      min: 0,
      max: 100,
      step: 0.01,
    },
    {
      kind: "select",
      id: "currency",
      label: "Currency",
      default: "USD",
      options: [
        { value: "USD", label: "USD ($)", synonyms: ["us dollar", "dollars", "usd"] },
        { value: "EUR", label: "EUR (€)", synonyms: ["euro", "euros"] },
        { value: "GBP", label: "GBP (£)", synonyms: ["pound", "pounds", "sterling"] },
        { value: "CAD", label: "CAD (CA$)", synonyms: ["canadian dollar", "canadian dollars"] },
        { value: "AUD", label: "AUD (AU$)", synonyms: ["australian dollar", "australian dollars"] },
      ],
    },
    {
      kind: "number",
      id: "markupPercent",
      label: "Markup percent",
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    {
      kind: "number",
      id: "failureRatePercent",
      label: "Failure rate percent",
      default: 0,
      min: 0,
      max: 50,
      step: 1,
    },
    {
      kind: "number",
      id: "laborRate",
      label: "Labor rate ($/hour)",
      default: 0,
      min: 0,
      max: 100000,
      step: 0.5,
    },
    {
      kind: "number",
      id: "laborMinutes",
      label: "Labor minutes",
      default: 0,
      min: 0,
      max: 100000,
      step: 1,
    },
    {
      kind: "number",
      id: "printerPrice",
      label: "Printer price",
      default: 0,
      min: 0,
      max: 1000000,
      step: 10,
    },
    {
      kind: "number",
      id: "printerLifeHours",
      label: "Printer life (hours)",
      default: 2000,
      min: 1,
      max: 1000000,
      step: 100,
    },
    {
      kind: "number",
      id: "postProcessingCost",
      label: "Post processing cost (flat)",
      default: 0,
      min: 0,
      max: 1000000,
      step: 0.5,
    },
  ],
  examples: [
    {
      label: "Pasted PrusaSlicer summary",
      input: "Filament used: 23.4g\nEstimated printing time: 3h 12m",
      opts: { material: "pla", spoolPrice: "20", spoolGrams: "1000", printerWatts: "120" },
    },
    {
      label: "PETG print with markup for a customer quote",
      input: "",
      opts: {
        grams: "48",
        material: "petg",
        hours: "4",
        minutes: "30",
        markupPercent: "40",
        failureRatePercent: "10",
      },
    },
  ],
  copy: {
    what: "Calculates what a single 3D print actually costs: filament by weight or length, electricity from your printer's average draw and the print time, plus optional machine wear, labor, post processing, a failure allowance, and a markup for quoting a customer. Paste a slicer summary from PrusaSlicer or Cura and it prefills the filament weight, length, and print time automatically.",
    how: "Enter grams of filament used, or a length in meters if that is what your slicer reports; pick the material so the density is right for the meters conversion. Set your spool price and weight, printer wattage, and electricity price, then add print time. Optional fields cover machine depreciation, labor, post processing, failure rate, and markup for a customer quote.",
    why: "Most print cost calculators only handle filament and skip electricity, machine wear, and failed prints entirely, so the number they give is not what the print actually costs you. This one covers the full cost stack, reads slicer output directly instead of making you retype numbers, and runs entirely on your device with no signup.",
    faq: [
      {
        q: "How is filament length converted to weight?",
        a: "Length in meters is converted to volume using the filament diameter, then multiplied by the material's density: grams = pi times (diameter / 2)^2 times length times density, with all lengths in centimeters. Filament weight, when known, is always used directly instead since it is more accurate than a length-based estimate.",
      },
      {
        q: "Why does the failure allowance depend on my failure rate?",
        a: "The allowance amortizes failed prints across the successful ones rather than just adding a flat cut: at a 10 percent failure rate, roughly one in ten prints fails, so the successful prints need to cover that lost material and time, which is a bigger multiplier than a simple 10 percent addition.",
      },
      {
        q: "Can I paste a slicer summary instead of typing numbers?",
        a: 'Yes. Paste PrusaSlicer or Cura output containing a filament weight or length line and a print time line, such as "Filament used: 23.4g" and "Estimated printing time: 3h 12m", or the raw G-code comments like "; filament used [g] = 23.4" and ";TIME:11520", and those values are used instead of the number fields.',
      },
    ],
  },
};
