// Generated by scripts/prepare-chem-data.mjs. Do not edit by hand.
// Rebuild with `node scripts/prepare-chem-data.mjs`. This file is a committed
// snapshot: Workers Builds will not refetch it, so the build imports what is
// in git and this script is the refresh path.

/**
 * Types and helpers for the broad chemistry dataset, which is fetched at
 * runtime rather than bundled.
 *
 * This module deliberately holds no data. `CHEMICALS` in ./chem-data is the
 * narrow tier: about 3,050 compounds that carry an NFPA rating or a GHS
 * classification, small enough to ship inside the tool's JavaScript. The broad
 * tier is 25,248 compounds, every English Wikipedia article with a
 * Chembox, a Drugbox or an Infobox drug, and it lives in 129 JSON files under
 * `/data/chem/`. Importing this module costs a couple of hundred bytes.
 *
 * The intended flow for a panel is two fetches:
 *
 *   1. `CHEM_INDEX_URL` once, for every compound's id, name, formula, CAS
 *      number, molar mass and up to a few alternative names. That is enough
 *      to run a search box that also answers to a synonym.
 *   2. `chemShardUrl(id)` for the one compound the person picked, which
 *      returns a 128th of the corpus and holds the full record.
 *
 * Neither is precached by the service worker: scripts/generate-sw.mjs skips
 * everything under `/data/`, so both are ordinary network fetches that the
 * browser's HTTP cache handles.
 *
 * This dataset is a reference, never a basis for a workplace safety decision.
 * Verify against the safety data sheet, NFPA 704 itself, and the authority
 * having jurisdiction.
 */

/** The compact index, one row per compound, sorted by id. */
export const CHEM_INDEX_URL = "/data/chem/index.json";

/** How many shards the full records are split across. */
export const CHEM_SHARD_COUNT = 128;

/**
 * A row in the index. A tuple rather than an object, because 25,248 objects
 * with seven named keys each is roughly three times the bytes over the wire.
 *
 *   [id, name, formula, cas, molarMass, flags, syn?]
 *
 * `formula` and `cas` are the empty string when unknown, and `molarMass`
 * is 0 when unknown, so that the JSON stays compact. `syn` is up to
 * 4 alternative names (PubChem's title when it differs from
 * `name`, a short IUPAC name, then the best of the compound's own gathered
 * synonyms), present only on a row that has one worth showing; an older 6
 * element row and a row this build chose to ship without one both simply
 * lack it, so read it as `row[6] ?? []` rather than assuming it is there.
 * This build shipped at most 2 per row: the full 4 would have exceeded index.json's own size budget.
 * Read every field through the helpers below rather than testing the
 * sentinels by hand.
 */
export type ChemIndexRow = [
  id: number,
  name: string,
  formula: string,
  cas: string,
  molarMass: number,
  flags: number,
  syn?: string[],
];

/** The parsed index: every row, in id order. */
export type ChemIndex = ChemIndexRow[];

/**
 * Bit flags in `ChemIndexRow[5]`. `Cid` says the id is a real PubChem CID;
 * a compound this build could not resolve to one keeps a synthetic id at or
 * above 900,000,000, which is well past PubChem's range.
 */
export const CHEM_FLAG_NFPA = 1;
export const CHEM_FLAG_GHS = 2;
export const CHEM_FLAG_DRUG = 4;
export const CHEM_FLAG_CID = 8;
export const CHEM_FLAG_WIKIPEDIA = 16;
export const CHEM_FLAG_DESCRIPTION = 32;

export const CHEM_SYNTHETIC_ID_BASE = 900000000;

/** The URL of the shard holding the full record for `id`. */
export function chemShardUrl(id: number): string {
  return `/data/chem/${id % CHEM_SHARD_COUNT}.json`;
}

/** A parsed shard, keyed by id as a string. */
export type ChemShard = Record<string, ChemRecord>;

/** The full record for `id` in a fetched shard, or undefined if absent. */
export function chemRecordFrom(shard: ChemShard, id: number): ChemRecord | undefined {
  return shard[String(id)];
}

export function chemHasNfpa(row: ChemIndexRow): boolean {
  return (row[5] & CHEM_FLAG_NFPA) !== 0;
}

export function chemHasGhs(row: ChemIndexRow): boolean {
  return (row[5] & CHEM_FLAG_GHS) !== 0;
}

export function chemIsDrug(row: ChemIndexRow): boolean {
  return (row[5] & CHEM_FLAG_DRUG) !== 0;
}

/** The PubChem CID, or undefined when this build could not resolve one. */
export function chemCid(row: ChemIndexRow): number | undefined {
  return (row[5] & CHEM_FLAG_CID) !== 0 ? row[0] : undefined;
}

export interface ChemNfpaRating {
  /** Blue quadrant, health. */
  h: 0 | 1 | 2 | 3 | 4;
  /** Red quadrant, flammability. */
  f: 0 | 1 | 2 | 3 | 4;
  /** Yellow quadrant, instability. */
  r: 0 | 1 | 2 | 3 | 4;
  /** White quadrant. W means no water, OX oxidiser, SA simple asphyxiant. */
  special: ("W" | "OX" | "SA")[];
  source: "Wikipedia";
}

/**
 * A GHS classification. Unlike `GhsClassification` in ./chem-data, the hazard
 * statements are codes without their text: the canonical wording of every code
 * is already in `H_STATEMENTS` from ./ghs-statements, which is bundled and
 * small, and repeating it per compound cost more than the whole index does.
 */
export interface ChemGhs {
  /** "GHS01" through "GHS09". */
  pictograms: string[];
  signal?: "Danger" | "Warning";
  /** Hazard codes, for example "H225". Text is in H_STATEMENTS. */
  h: string[];
  /** Precautionary codes, plain and combination, for example "P305+P351+P338". */
  p: string[];
}

export interface ChemRecordProperties {
  /** Free text as published, units included. */
  density?: string;
  meltingPoint?: string;
  boilingPoint?: string;
  flashPoint?: string;
}

/** A full record, as stored in a shard. The id is the shard's key. */
export interface ChemRecord {
  name: string;
  formula?: string;
  cas?: string;
  /** Grams per mole. */
  molarMass?: number;
  /** Monoisotopic mass, from PubChem. */
  exactMass?: number;
  /** Present only when the id is a real PubChem CID. */
  cid?: number;
  /** English Wikipedia article title, not a URL. */
  wikipedia?: string;
  /** One sentence from the article's lead. */
  description?: string;
  /** True when the article carried a Drugbox or an Infobox drug. */
  isDrug?: boolean;
  synonyms?: string[];
  nfpa?: ChemNfpaRating;
  ghs?: ChemGhs;
  props?: ChemRecordProperties;
}

export const CHEM_BROAD_META = {
  "builtAt": "2026-08-30",
  "narrowChemicals": 3050,
  "shards": 128,
  "columns": [
    "id",
    "name",
    "formula",
    "cas",
    "molarMass",
    "flags",
    "syn"
  ],
  "indexSynLimit": 4,
  "indexSynCap": 2,
  "counts": {
    "compounds": 25248,
    "withNfpa": 1774,
    "withGhs": 9087,
    "withoutGhs": 16161,
    "drugs": 10722,
    "withCid": 23597,
    "withCas": 23767,
    "withFormula": 24650,
    "withMolarMass": 24553,
    "withDescription": 25245,
    "withIndexSyn": 18920,
    "articlesRead": 26080
  },
  "ghsSweepComplete": true,
  "ghsPagesRead": 359,
  "ghsPagesTotal": 359,
  "droppedFields": [],
  "ghsSourcePriority": [
    "Regulation (EC) No 1272/2008 of the European Parliament and of the Council",
    "European Chemicals Agency (ECHA)",
    "Hazardous Substances Data Bank (HSDB)",
    "Hazardous Chemical Information System (HCIS), Safe Work Australia",
    "NITE-CMC"
  ],
  "sources": [
    {
      "name": "PubChem NFPA Hazard Classification annotations (HSDB and OSHA)",
      "url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/annotations/heading/NFPA%20Hazard%20Classification/JSON",
      "license": "Public domain (US National Library of Medicine)"
    },
    {
      "name": "PubChem GHS Classification",
      "url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/<CID>/JSON?heading=GHS+Classification",
      "license": "Public domain (US National Library of Medicine)"
    },
    {
      "name": "PubChem GHS reference (hazard statements, precautionary statements, pictograms)",
      "url": "https://pubchem.ncbi.nlm.nih.gov/ghs/",
      "license": "Public domain (US National Library of Medicine)"
    },
    {
      "name": "PubChem periodic table",
      "url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON",
      "license": "Public domain (US National Library of Medicine)"
    },
    {
      "name": "English Wikipedia Chembox parameters",
      "url": "https://en.wikipedia.org/",
      "license": "CC BY-SA 4.0"
    },
    {
      "name": "English Wikipedia Chembox, Drugbox and Infobox drug parameters, and article leads",
      "url": "https://en.wikipedia.org/",
      "license": "CC BY-SA 4.0"
    },
    {
      "name": "PubChem GHS Classification bulk annotations",
      "url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/annotations/heading/GHS%20Classification/JSON",
      "license": "Public domain (US National Library of Medicine)"
    },
    {
      "name": "PubChem compound properties and name resolution",
      "url": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/",
      "license": "Public domain (US National Library of Medicine)"
    }
  ],
  "notes": [
    "Reference only. Verify against the safety data sheet, NFPA 704 and the authority having jurisdiction.",
    "Wikipedia derived values are CC BY-SA 4.0 and must credit the article named in the wikipedia field.",
    "Hazard statements are codes only. H_STATEMENTS in ./ghs-statements holds the canonical wording."
  ]
} as const;
